### ISSUE TITLE
Fail on update of code

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1060]
There were some changes just now regarding Sorting of data on the Stock Page ( just background info..)
So to update to latest - I followed
**$ git pull origin master
$ invoke update**
Which failed as per below, and again when I try and start server
I can see some changes in the file ../inventree/InvenTree/common/migrations/0008_remove_inventreesetting_description.py which I suspect are relevant - but not up to speed on why.
(I'm running on a dev sqlite3 database as per the getting started path :) )
Not sure if I've done the right thing calling the update when nothing had changed in terms of the database.
Database integrity seems OK from checking with
**~/inventree$ sqlite3 inventree_default_db.sqlite3 "PRAGMA integrity_check"
ok**

![Clipboard01](https://user-images.githubusercontent.com/8358937/96533183-f3f1aa00-12d4-11eb-85d2-068d6cf8e400.jpg)

**Comment by SchrodingersGat** [comment]
Not ideal.

What happens if you run `invoke migrate` ?

**Comment by watarat** [comment]
Same :(
(inventree-env) richard@richard-VirtualBox:~/inventree$ invoke migrate
Running InvenTree database migrations...
========================================
2020-10-20 08:43:15,852 DEBUG Using selector: EpollSelector
InvenTree running in DEBUG mode
MEDIA_ROOT: /home/richard/inventree/inventree_media
STATIC_ROOT: /home/richard/inventree/inventree_static
Traceback (most recent call last):
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: common_inventreesetting.description

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/richard/inventree/InvenTree/common/apps.py", line 11, in ready
    self.add_instance_name()
  File "/home/richard/inventree/InvenTree/common/apps.py", line 46, in add_instance_name
    InvenTreeSetting.objects.create(
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: common_inventreesetting.description
(inventree-env) richard@richard-VirtualBox:~/inventree$ ^C
(inventree-env) richard@richard-VirtualBox:~/inventree$

**Comment by watarat** [comment]
oops - didnt preview - not shouting!!

**Comment by SchrodingersGat** [comment]
I believe I have found and fixed this bug now. When #1061 is merged please try that 👍

**Comment by watarat** [comment]
Dont know if you see comments on closed items.
But - YES!
Completes and runs server just fine :)
Sorting in STOCK also does exactly as expected.

Kudos, respect and thanks for your response!
Richard

**Comment by SchrodingersGat** [comment]
Great, thanks for letting me know. LMK if you find any other issues! I'm glad that you are enjoying using it :)
