### ISSUE TITLE
Part: Create Note Error 

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1065]
This is weird - I have (I think) only one part out of about 100 for which I can create a note.
Seemingly all others throw an error when I try and access the Notes tab for the part.
Sucess shown in Pic - and error log for rest of the parts.
(So I can sort of see that its having a problem (applying .strip) in the markdown display of an empty field, but I get confused when trying to chase it further through the code - would love to be able to help - but not yet :) )
At a total loss as to how one part manages to work - must be something different about my part creation sequence??

![Clipboard03](https://user-images.githubusercontent.com/8358937/96672062-e73f8580-13aa-11eb-9541-fde754dc1f1a.jpg)

```
Environment:
Request Method: GET
Request URL: http://192.168.31.111:8000/part/45/notes

Django Version: 3.0.7
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'django_filters',
 'dbbackup',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup',
 'qr_code',
 'mptt',
 'markdownx',
 'markdownify',
 'django_tex',
 'django_admin_shell']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware']

```

```
Template error:
In template /home/richard/inventree/InvenTree/templates/base.html, error at line 0
   'NoneType' object has no attribute 'strip'
   1 : {% load static %}
   2 : {% load i18n %}
   3 : {% load inventree_extras %}
   4 : 
   5 : <!DOCTYPE html>
   6 : <html lang="en">
   7 : <head>
   8 : 
   9 : <!-- Required meta tags -->
   10 : <meta charset="utf-8">


Traceback (most recent call last):
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 986, in render
    output = self.filter_expression.resolve(context)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 697, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/markdownify/templatetags/markdownify.py", line 46, in markdownify
    html = markdown.markdown(text, extensions=extensions)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/markdown/core.py", line 386, in markdown
    return md.convert(text)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/markdown/core.py", line 247, in convert
    if not source.strip():

Exception Type: AttributeError at /part/45/notes
Exception Value: 'NoneType' object has no attribute 'strip'

```

**Comment by watarat** [comment]
Further Info..
Not sure how this happens, but by looking at the database, I can see that some items have 'no entry' in the notes field, but the problematic ones seem to have "NULL".  You cant strip the leading/trailing from a NULL :)
Ones in Green I can add Notes to, Red I cant. Not sure how I managed to have some one way - some the other - perhaps to do with the entry method as they seem to be in a block (my IPN numbers are all clustered together)

![Clipboard03](https://user-images.githubusercontent.com/8358937/96675998-d6dfd880-13b3-11eb-9fdc-e0c9d4561291.jpg)

**Comment by eeintech** [comment]
@watarat When you create a new part and leave the `notes` field blank, does it show `notes` as empty string in database?
The `notes` model field is set with `null=True` so it shouldn't be...

Also, it is based on [django-markdownx](https://neutronx.github.io/django-markdownx/example/) which seems like [it can handle NULL based values](https://github.com/neutronX/django-markdownx/blob/master/markdownx/models.py). So there shouldn't be any problem either way...

**Comment by eeintech** [comment]
Ok found it, the template was trying to render the markdown even though `part.notes` was NULL

**Comment by watarat** [comment]
Thanks @eeintech for the fix 😀
Part->Create doesnt allow entering a comment, so I'm still confused as to how I managed to get a few parts with 'empty text' rather than NULL?

**Comment by eeintech** [comment]
> Part->Create doesnt allow entering a comment, so I'm still confused as to how I managed to get a few parts with 'empty text' rather than NULL?

If your database is older than end of September, previously the `null=True` constraint was not set on the `notes` field, so older part would have an empty string and new one have the `notes` field set to NULL. I do have a similar database as yours :wink:
