### ISSUE TITLE
Updating to latest: fails due to new currency updates?

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#1134]
Running migrations:
  Applying company.0026_auto_20201110_1011...Updating currency references for SupplierPriceBreak model...
Traceback (most recent call last):
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "USD" does not exist
LINE 1: ...PDATE part_supplierpricebreak set price_currency= "USD" wher...

I don't know how to recover from this.  When I updated my install at home, I had to run invoke update and tell it I wanted USD - twice.  This time I wasn't asked, it just failed.

**Comment by rco3** [comment]
Upon further examination, I find that the Inventree install is still at least somewhat operational despite the failed upgrade.  I determined that I did not have any currencies set at all, and promptly set USD as the base currency.  invoke update fails again with the same error.

**Comment by eeintech** [comment]
Weird, I had no problem migrating on both SQLite and PostgreSQL...
`psycopg2` line indicates that you are using PostgreSQL database and Python connector, is that correct?

Try this:
```
$ cd path/to/InvenTree
$ ./manage.py migrate company 0025_auto_20201110_1001
```

and if succeeds, re-run `invoke update`.

**Comment by rco3** [comment]
Hi, @eeintech, thanks for looking at this.

Sadly, that didn't fix it. Executing " ./manage.py migrate company 0025_auto_20201110_1001 " gave me the same error.

Running migrations:
  Applying company.0026_auto_20201110_1011...Updating currency references for SupplierPriceBreak model...
Traceback (most recent call last):
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "USD" does not exist
LINE 1: ...PDATE part_supplierpricebreak set price_currency= "USD" wher...

I also tried running the migration that failed (0026), directly from the command line, and failed that way as well.

**Comment by eeintech** [comment]
@rco3 Maybe try to reset migrations for the company app?
https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html

**Comment by rco3** [comment]
That tutorial says to start after all migrations are applied:
"If you see the message:

No changes detected
You are good to go."

I don't see that, my migrations are failing.  Should I continue anyway?  I really don't want to blow away my database.

**Comment by rco3** [comment]
Doesn't matter, "./manage.py migrate --fake company zero" now results in "django.db.migrations.exceptions.InconsistentMigrationHistory: Migration build.0021_auto_20201020_0908_squashed_0026_auto_20201023_1228 is applied before its dependency stock.0052_stockitem_is_building on database 'default'."

Any other ideas?

**Comment by eeintech** [comment]
@rco3 Please DO save your database beforehand! I'm sorry I should have mentioned this :grimacing: 
If you are using PostgreSQL take a look into `pg_dump` tool.

I don't have any idea at the moment, I'm so such an expert in database migration unfortunately...

**Comment by SchrodingersGat** [comment]
@rco3 can you please provide the full error trace?

> psycopg2.errors.UndefinedColumn: column "USD" does not exist
> LINE 1: ...PDATE part_supplierpricebreak set price_currency= "USD" wher...

This is very strange... "USD" is a value not the name of the column...

If you can provide the full error output that'd be great.

**Comment by rco3** [comment]
Sure, I just didn't want to dump too much garbage.  As I recall, my home install gave similar issues except it was "US" instead of "USD", and it asked me to give it a valid currency code - twice.  After the second time, the install completed normally.

I'm assuming this is what you're wanting?  Thank you both, again, for your help.

 This was the initial error when running `invoke update`.
```
Running InvenTree database migrations...
========================================
2020-11-18 12:52:36,331 INFO Loading SERCRET_KEY from /opt/inventree/InvenTree/secret_key.txt
2020-11-18 12:52:36,332 INFO InvenTree running in DEBUG mode
2020-11-18 12:52:36,332 INFO MEDIA_ROOT: '/opt/inventree/media'
2020-11-18 12:52:36,333 INFO STATIC_ROOT: '/opt/inventree/static'
2020-11-18 12:52:36,333 INFO Configuring database backend:
2020-11-18 12:52:36,333 INFO Database ENGINE: 'django.db.backends.postgresql_psycopg2'
2020-11-18 12:52:36,334 INFO Database NAME: 'inventree'
Checking Company image thumbnails
Using selector: EpollSelector
InvenTree: Checking Part image thumbnails
Loading action plugins...
Loading action plugins
Discovered 1 action plugins:
 - SimpleActionPlugin
No changes detected
2020-11-18 12:52:46,816 INFO Loading SERCRET_KEY from /opt/inventree/InvenTree/secret_key.txt
2020-11-18 12:52:46,817 INFO InvenTree running in DEBUG mode
2020-11-18 12:52:46,817 INFO MEDIA_ROOT: '/opt/inventree/media'
2020-11-18 12:52:46,818 INFO STATIC_ROOT: '/opt/inventree/static'
2020-11-18 12:52:46,818 INFO Configuring database backend:
2020-11-18 12:52:46,818 INFO Database ENGINE: 'django.db.backends.postgresql_psycopg2'
2020-11-18 12:52:46,819 INFO Database NAME: 'inventree'
Checking Company image thumbnails
Using selector: EpollSelector
InvenTree: Checking Part image thumbnails
Loading action plugins...
Loading action plugins
Discovered 1 action plugins:
 - SimpleActionPlugin
Operations to perform:
  Apply all migrations: admin, auth, authtoken, build, common, company, contenttypes, error_report, exchange, label, order, part, report, sessions, stock, users
Running migrations:
  Applying company.0026_auto_20201110_1011...Updating currency references for SupplierPriceBreak model...
Traceback (most recent call last):
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "USD" does not exist
LINE 1: ...PDATE part_supplierpricebreak set price_currency= "USD" wher...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/opt/invenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/inventree/InvenTree/company/migrations/0026_auto_20201110_1011.py", line 70, in migrate_currencies
    response = cursor.execute(f'UPDATE part_supplierpricebreak set price_currency= "{currency_code}" where id={pk};')
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/invenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "USD" does not exist
LINE 1: ...PDATE part_supplierpricebreak set price_currency= "USD" wher...

```

After this, I tried ``` ./manage.py migrate company 0025_auto_20201110_1001```, unsuccessfully, and then tried applying the failed migration (0026) directly, and now just about any migration activity (e.g., `manage.py makemigrations`) fails with:

```2020-11-18 14:37:42,205 INFO Loading SERCRET_KEY from /opt/inventree/InvenTree/secret_key.txt
2020-11-18 14:37:42,206 INFO InvenTree running in DEBUG mode
2020-11-18 14:37:42,206 INFO MEDIA_ROOT: '/opt/inventree/media'
2020-11-18 14:37:42,206 INFO STATIC_ROOT: '/opt/inventree/static'
2020-11-18 14:37:42,206 INFO Configuring database backend:
2020-11-18 14:37:42,207 INFO Database ENGINE: 'django.db.backends.postgresql_psycopg2'
2020-11-18 14:37:42,207 INFO Database NAME: 'inventree'
Checking Company image thumbnails
Using selector: EpollSelector
InvenTree: Checking Part image thumbnails
Loading action plugins...
Loading action plugins
Discovered 1 action plugins:
 - SimpleActionPlugin
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/invenv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor.loader.check_consistent_history(connection)
  File "/opt/invenv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 299, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration build.0021_auto_20201020_0908_squashed_0026_auto_20201023_1228 is applied before its dependency stock.0052_stockitem_is_building on database 'default'.
```

This db has been through several upgrades and migrations...

**Comment by SchrodingersGat** [comment]
Huh.

https://stackoverflow.com/questions/41396195/what-is-the-difference-between-single-quotes-and-double-quotes-in-postgresql

**Comment by SchrodingersGat** [comment]
Fix incoming.

**Comment by eeintech** [comment]
Ouch! Weird it did not fail on our PostgreSQL db 🤔

**Comment by rco3** [comment]
Was able to resolve the self-inflicted migration issue above by opening the PG DB with LibreOffice, deleting the table entry for that migration in the django_migrations (sp?) table, and then `invoke update` completed without a hitch.

Thanks again.
