### ISSUE TITLE
Inv migrate error

### ISSUE THREAD

**Issue by pawcio0928** [inventree/InvenTree#1204]
Hello I want to set up my InvenTree on Rpi4. I done installation and when I type `inc migrate` I get that:

``` Running InvenTree database migrations...
========================================
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/inventree-env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/pi/inventree-env/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/pi/inventree-env/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pi/inventree-env/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/pi/inventree-env/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/inventree/InvenTree/label/models.py", line 11, in <module>
    from blabel import LabelWriter
  File "/home/pi/inventree-env/lib/python3.7/site-packages/blabel/__init__.py", line 5, in <module>
    from .blabel import LabelWriter
  File "/home/pi/inventree-env/lib/python3.7/site-packages/blabel/blabel.py", line 6, in <module>
    from weasyprint import HTML
  File "/home/pi/inventree-env/lib/python3.7/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/home/pi/inventree-env/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/home/pi/inventree-env/lib/python3.7/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/home/pi/inventree-env/lib/python3.7/site-packages/weasyprint/text.py", line 11, in <module>
    import cairocffi as cairo
  File "/home/pi/inventree-env/lib/python3.7/site-packages/cairocffi/__init__.py", line 50, in <module>
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "/home/pi/inventree-env/lib/python3.7/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
```
The same error appears when I type `pythons manage.py migrate`.

Please help me with this issue.

**Comment by eeintech** [comment]
@pawcio0928 Please see the "Solving Cairo Error" note in the doc: https://inventree.readthedocs.io/en/latest/start/install/#create-admin-account

That should help you solve your problem :smiley:

**Comment by pawcio0928** [comment]
@eeintech Thank you for solving my issue.
