### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#1278]
I am currently running 
Inventree version 0.1.5
Dejango Version 3.0.7

When I open a part and select the stock tab.  Then select the Stock qty hyperlink I get the following error

Cannot resolve keyword 'name' into field. Choices are: allocations, attachments, batch, belongs_to, belongs_to_id, build, build_id, children, customer, customer_id, delete_on_deplete, expiry_date, id, infinite, installed_parts, is_building, items_to_install, level, lft, link, location, location_id, notes, owner, owner_id, parent, parent_id, part, part_id, purchase_order, purchase_order_id, purchase_price, purchase_price_currency, quantity, review_needed, rght, sales_order, sales_order_allocations, sales_order_id, serial, status, stocktake_date, stocktake_user, stocktake_user_id, supplier_part, supplier_part_id, test_results, tracking_info, tree_id, uid, updated

This happens with every part in my DB.  Any idea's?  I've looked through the issues and I don't see anything related.

When I was running 0.1.3 I did not see this

**Comment by SchrodingersGat** [comment]
can you please post the entire error message that appears?

**Comment by lookme2** [comment]
`

Request Method: | GET
-- | --
http://172.16.1.44:8000/stock/item/1206/
3.0.7
FieldError
Cannot resolve keyword 'name' into field. Choices are: allocations, attachments, batch, belongs_to, belongs_to_id, build, build_id, children, customer, customer_id, delete_on_deplete, expiry_date, id, infinite, installed_parts, is_building, items_to_install, level, lft, link, location, location_id, notes, owner, owner_id, parent, parent_id, part, part_id, purchase_order, purchase_order_id, purchase_price, purchase_price_currency, quantity, review_needed, rght, sales_order, sales_order_allocations, sales_order_id, serial, status, stocktake_date, stocktake_user, stocktake_user_id, supplier_part, supplier_part_id, test_results, tracking_info, tree_id, uid, updated
/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/sql/query.py in names_to_path, line 1483
/home/prism/Inventory/inventree-env/bin/python3
3.8.5
['/home/prism/Inventory/InvenTree-0.1.5/InvenTree',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf',  '/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/odf']
Mon, 8 Feb 2021 14:04:42 +0000

`

**Comment by lookme2** [comment]
`Environment:


Request Method: GET
Request URL: http://172.16.1.44:8000/stock/item/1206/

Django Version: 3.0.7
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'django_filters',
 'dbbackup',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup',
 'qr_code',
 'mptt',
 'markdownx',
 'markdownify',
 'django_tex',
 'django_admin_shell',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'error_report.middleware.ExceptionProcessor']


Template error:
In template /home/prism/Inventory/InvenTree-0.1.5/InvenTree/templates/base.html, error at line 116
   Cannot resolve keyword 'name' into field. Choices are: allocations, attachments, batch, belongs_to, belongs_to_id, build, build_id, children, customer, customer_id, delete_on_deplete, expiry_date, id, infinite, installed_parts, is_building, items_to_install, level, lft, link, location, location_id, notes, owner, owner_id, parent, parent_id, part, part_id, purchase_order, purchase_order_id, purchase_price, purchase_price_currency, quantity, review_needed, rght, sales_order, sales_order_allocations, sales_order_id, serial, status, stocktake_date, stocktake_user, stocktake_user_id, supplier_part, supplier_part_id, test_results, tracking_info, tree_id, uid, updated
   106 : 
   107 : <script type="text/javascript" src="{% static 'fullcalendar/main.js' %}"></script>
   108 : <script type="text/javascript" src="{% static 'script/select2/select2.js' %}"></script>
   109 : <script type='text/javascript' src="{% static 'script/moment.js' %}"></script>
   110 : 
   111 : <script type='text/javascript' src="{% static 'script/inventree/inventree.js' %}"></script>
   112 : <script type='text/javascript' src="{% static 'script/inventree/api.js' %}"></script>
   113 : <script type='text/javascript' src="{% static 'script/inventree/filters.js' %}"></script>
   114 : <script type='text/javascript' src="{% static 'script/inventree/tables.js' %}"></script>
   115 : <script type='text/javascript' src="{% static 'script/inventree/notification.js' %}"></script>
   116 : <script type='text/javascript' src="{% static 'script/invent ree/sidenav.js' %}"></script>
    117 : 
   118 : <script type='text/javascript' src="{% url 'barcode.js' %}"></script>
   119 : <script type='text/javascript' src="{% url 'bom.js' %}"></script>
   120 : <script type='text/javascript' src="{% url 'company.js' %}"></script>
   121 : <script type='text/javascript' src="{% url 'part.js' %}"></script>
   122 : <script type='text/javascript' src="{% url 'modals.js' %}"></script>
   123 : <script type='text/javascript' src="{% url 'label.js' %}"></script>
   124 : <script type='text/javascript' src="{% url 'report.js' %}"></script>
   125 : <script type='text/javascript' src="{% url 'stock.js' %}"></script>
   126 : <script type='text/javascript' src="{% url 'build.js' %}"></script>


Traceback (most recent call last):
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]

During handling of the above exception ('StockItem' object is not subscriptable), another exception occurred:
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/defaulttags.py", line 302, in render
    match = condition.eval(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/defaulttags.py", line 876, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/prism/Inventory/InvenTree-0.1.5/InvenTree/stock/models.py", line 1359, in has_test_reports
    return len(self.available_test_reports()) > 0
  File "/home/prism/Inventory/InvenTree-0.1.5/InvenTree/stock/models.py", line 1348, in available_test_reports
    if item_query.filter(**filters).exists():
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/prism/Inventory/inventree-env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "

Exception Type: FieldError at /stock/item/1206/
Exception Value: Cannot resolve keyword 'name' into field. Choices are: allocations, attachments, batch, belongs_to, belongs_to_id, build, build_id, children, customer, customer_id, delete_on_deplete, expiry_date, id, infinite, installed_parts, is_building, items_to_install, level, lft, link, location, location_id, notes, owner, owner_id, parent, parent_id, part, part_id, purchase_order, purchase_order_id, purchase_price, purchase_price_currency, quantity, review_needed, rght, sales_order, sales_order_allocations, sales_order_id, serial, status, stocktake_date, stocktake_user, stocktake_user_id, supplier_part, supplier_part_id, test_results, tracking_info, tree_id, uid, updated
`

**Comment by lookme2** [comment]
Let me know if you need anything else.

**Comment by SchrodingersGat** [comment]
Have you made any TestReport templates?

**Comment by lookme2** [comment]
I do have report listed under the Test Reports.  It's called Test.  I'm pretty sure I did not put it there.

**Comment by SchrodingersGat** [comment]
In the admin interface, try:

1) Set the "Test" test report as disabled

if (1) does not work

3) Delete the "Test" test report

Let me know if that resolves the issue

**Comment by SchrodingersGat** [comment]
Also if you can grab a screenshot of the "Test" report in the admin interface? If you did not put it there I'd like to know what the contents are

**Comment by lookme2** [comment]
So disabling the "Test" report did work.  After looking at it a little closer I realize that it was added by another person here.  Sorry for for the confusion.

**Comment by SchrodingersGat** [comment]
Glad you worked it out. But the issue you ran into should not have happened anyway!

so I give you https://github.com/inventree/InvenTree/pull/1283

**Comment by lookme2** [comment]
Thaks!
