### ISSUE TITLE
Windows installation, fails on `inv migrate`.

### ISSUE THREAD

**Issue by neoblizz** [inventree/InvenTree#1388]
I have tried `python` versions `3.7`, `3.8` and `3.9`, running on Windows 10 (Build 21301.1010). Very similar problem to this issue: https://github.com/inventree/InvenTree/issues/1033, but instead of running an existing server all this is new trying to get everything to install.

Here's the error;
```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-master> inv migrate
Running InvenTree database migrations...
========================================
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django  # NOQA
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

Here are all my system paths;
```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-master\InvenTree> python -c 'import sys; print(sys.path)'
['', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\python37.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0', 'C:\\Users\\neobl\\Downloads\\InvenTree-master\\inventree-env', 'C:\\Users\\neobl\\Downloads\\InvenTree-master\\inventree-env\\lib\\site-packages']
```

And in the `site-packages` I see bunch of `django`s:
```
...
d-----          3/3/2021  11:56 AM                diff_match_patch
d-----          3/3/2021  11:56 AM                diff_match_patch-20200713.dist-info
d-----          3/3/2021  11:56 AM                django
d-----          3/3/2021  11:56 AM                Django-3.0.7.dist-info
d-----          3/3/2021  11:56 AM                djangorestframework-3.10.3.dist-info
d-----          3/3/2021  11:56 AM                django_admin_shell
d-----          3/3/2021  11:56 AM                django_admin_shell-0.1.2.dist-info
d-----          3/3/2021  11:56 AM                django_cleanup
d-----          3/3/2021  11:56 AM                django_cleanup-5.1.0.dist-info
d-----          3/3/2021  11:56 AM                django_cors_headers-3.2.0.dist-info
d-----          3/3/2021  11:56 AM                django_crispy_forms-1.8.1.dist-info
d-----          3/3/2021  11:56 AM                django_dbbackup-3.3.0-py3.7.egg-info
d-----          3/3/2021  11:56 AM                django_debug_toolbar-2.2.dist-info
d-----          3/3/2021  11:56 AM                django_error_report-0.2.0-py3.7.egg-info
d-----          3/3/2021  11:56 AM                django_filter-2.2.0.dist-info
d-----          3/3/2021  11:56 AM                django_filters
d-----          3/3/2021  11:56 AM                django_import_export-2.0.dist-info
d-----          3/3/2021  11:56 AM                django_js_asset-1.2.2.dist-info
d-----          3/3/2021  11:56 AM                django_markdownify-0.8.0-py3.7.egg-info
d-----          3/3/2021  11:56 AM                django_markdownx-3.0.1.dist-info
d-----          3/3/2021  11:56 AM                django_money-1.1.dist-info
d-----          3/3/2021  11:56 AM                django_mptt-0.11.0.dist-info
d-----          3/3/2021  11:56 AM                django_sql_utils-0.5.0.dist-info
d-----          3/3/2021  11:56 AM                django_stdimage-5.1.1.dist-info
d-----          3/3/2021  11:56 AM                django_test_migrations
d-----          3/3/2021  11:56 AM                django_test_migrations-1.1.0.dist-info
d-----          3/3/2021  11:56 AM                django_weasyprint
d-----          3/3/2021  11:56 AM                django_weasyprint-1.0.1.dist-info
d-----          3/3/2021  11:56 AM                djmoney
...
```

No error on `python -c 'import django'`.

Directly trying `manage.py` doesn't work either;
```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-master\InvenTree> python3 .\manage.py migrate    
Traceback (most recent call last):
  File ".\manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\manage.py", line 14, in <module>
    import django  # NOQA
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

Useful version related stuff within the virtual-env:
```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-master\InvenTree> django-admin --version        
3.0.7
```

```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-master\InvenTree> python --version
Python 3.7.9
```

What could I be doing wrong? Any help is appreciated!

**Comment by neoblizz** [comment]
Btw, this works perfectly fine too...
```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-0.1.6> python -c 'import django.core.management'
```

**Comment by neoblizz** [comment]
Hmmm, using `python` instead of `python3` somewhat worked. Now I am at;

```
(inventree-env) PS C:\Users\neobl\Downloads\InvenTree-0.1.6> python .\InvenTree\manage.py migrate
OSError: no library called "cairo" was found
cannot load library 'libcairo-2.dll': error 0x7e
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
You may require some further system packages to be installed.
```

**Comment by SchrodingersGat** [comment]
Check out the installation instructions page: https://inventree.readthedocs.io/en/latest/start/install/

![image](https://user-images.githubusercontent.com/10080325/109876690-2a4d2600-7cc6-11eb-94b9-3ee6e41187dc.png)

Note that Weasyprint will (in their next major release) drop their requirement for libcairo, which will make InvenTree *much* easier to install! It is currently a bit burdensome on Windows.

**Comment by neoblizz** [comment]
I saw that little comment, trying to get that working now. Thank you! :)

**Comment by neoblizz** [comment]
I followed the installation steps specified by `weasyprint`, in my command-line, I see `echo %PATH%`

```
C:\Users\neobl>echo %PATH%
...;C:\Program Files\GTK3-Runtime Win64\bin;...
```

It's still not finding the `cairo` files. Is there a specific way I should be setting these paths up within the virtual environment of python to get weasy to recognize them?

**Comment by neoblizz** [comment]
Should I be using `mingw` and not PowerShell or CMD by any chance?

**Comment by eeintech** [comment]
@neoblizz In my little experience with Python on Windows, I found MinGW terminal to be much more friendly than the CMD. Have not tried PowerShell.

**Comment by neoblizz** [comment]
@eeintech thank you, I'll give that a try. I just find it weird that the global PATH variable sees GTK and all of its libraries, but within the python virtual environment somehow it is not seeing that. And I don't know if that is a `venv` thing, or if I need to additionally set some paths there as well.

I'll try `MinGW`, really also hoping for Weasyprint dropping `cairo` as @SchrodingersGat pointed out. :)

**Comment by SchrodingersGat** [comment]
@neoblizz any word?

If you are still having trouble, I would suggest installing InvenTree under [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by neoblizz** [comment]
I got it to work through WSL a little while ago. But I'll probably wait for the `libcairo` requirement to be dropped to actually adopt/try it out.
