### ISSUE TITLE
Items in stock not showing

### ISSUE THREAD

**Issue by WHTLY** [inventree/InvenTree#1419]
Hi! 
Items in stock is disappeared, but they still remain in csv report and can be seen in django admin view.

InvenTree Version 0.1.8 pre
Django Version 3.0.7
Commit Hash  5a5e76e0
Commit Date 2021-03-25

Console error 500:
GET | http://inv01.nccme.local/api/stock/?search=&offset=0&limit=25&location=3&part_detail=true&location_detail=true

Gunicorn log:

> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: Internal Server Error: /api/stock/
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: Traceback (most recent call last):
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return Database.Cursor.execute(self, query, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: sqlite3.OperationalError: no such column: order_salesorder.responsible_id
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: The above exception was the direct cause of the following exception:
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: Traceback (most recent call last):
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = get_response(request)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = self.process_exception_by_middleware(e, request)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return view_func(*args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.dispatch(request, *args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = self.handle_exception(exc)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self.raise_uncaught_exception(exc)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     raise exc
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = handler(request, *args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/generics.py", line 239, in get
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.list(request, *args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree/InvenTree/stock/api.py", line 384, in list
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     page = self.paginate_queryset(queryset)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.paginator.paginate_queryset(queryset, self.request, view=self)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/pagination.py", line 385, in paginate_queryset
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return list(queryset[self.offset:self.offset + self.limit])
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._fetch_all()
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1263, in _fetch_all
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._prefetch_related_objects()
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 782, in _prefetch_related_objects
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1651, in prefetch_related_objects
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1781, in prefetch_one_level
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     all_related_objects = list(rel_qs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._fetch_all()
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._result_cache = list(self._iterable_class(self))
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return super().execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return executor(sql, params, many, context)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     raise dj_exc_value.with_traceback(traceback) from exc_value
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return Database.Cursor.execute(self, query, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: django.db.utils.OperationalError: no such column: order_salesorder.responsible_id
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: Internal Server Error: /api/stock/
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: Traceback (most recent call last):
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return Database.Cursor.execute(self, query, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: sqlite3.OperationalError: no such column: order_salesorder.responsible_id
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: The above exception was the direct cause of the following exception:
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: Traceback (most recent call last):
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = get_response(request)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = self.process_exception_by_middleware(e, request)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return view_func(*args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.dispatch(request, *args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = self.handle_exception(exc)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self.raise_uncaught_exception(exc)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     raise exc
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     response = handler(request, *args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/generics.py", line 239, in get
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.list(request, *args, **kwargs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree/InvenTree/stock/api.py", line 384, in list
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     page = self.paginate_queryset(queryset)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.paginator.paginate_queryset(queryset, self.request, view=self)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/rest_framework/pagination.py", line 385, in paginate_queryset
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return list(queryset[self.offset:self.offset + self.limit])
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._fetch_all()
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1263, in _fetch_all
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._prefetch_related_objects()
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 782, in _prefetch_related_objects
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1651, in prefetch_related_objects
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1781, in prefetch_one_level
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     all_related_objects = list(rel_qs)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._fetch_all()
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     self._result_cache = list(self._iterable_class(self))
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return super().execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return executor(sql, params, many, context)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     raise dj_exc_value.with_traceback(traceback) from exc_value
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return self.cursor.execute(sql, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:   File "/opt/inventree/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]:     return Database.Cursor.execute(self, query, params)
> Mar 25 09:59:53 inv01.nccme.local gunicorn[6054]: django.db.utils.OperationalError: no such column: order_salesorder.responsible_id

**Comment by WHTLY** [comment]
Ah, never mind. My bad, forgot to make migrations:)
