### ISSUE TITLE
Error exporting BOM in YAML format

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1443]
The error is:

![Error](https://user-images.githubusercontent.com/14631/113969183-5db13200-97e9-11eb-918c-c84d23a8eb21.png "Error")

**Comment by eeintech** [comment]
Quick investigation leads to a lack of representation for decimal format in the PyYAML library, and `safe_dump` fails.

To reproduce:
``` python
>>> import yaml, decimal
>>> dec = decimal.Decimal('7')
>>> print(dec)
7
>>> type(dec)
<class 'decimal.Decimal'>
>>> yaml.safe_dump(dec)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/yaml/__init__.py", line 216, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/yaml/representer.py", line 229, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', Decimal('7'))
```
