### ISSUE TITLE
Error when viewing supplier price breaks in Admin view

### ISSUE THREAD

**Issue by wengtad** [inventree/InvenTree#1526]
I'm using demo site https://inventree.polarize.xyz hosted by eeintech to test.
Hitting this when click one of the item in the item list.

```
Environment:


Request Method: GET
Request URL: https://inventree.polarize.xyz/admin/company/supplierpricebreak/7/change/

Django Version: 3.2
Python Version: 3.7.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django_filters',
 'dbbackup',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownx',
 'markdownify',
 'django_admin_shell',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'error_report.middleware.ExceptionProcessor']



Traceback (most recent call last):
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1658, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1538, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/eeintech/virtualenv/inventree/3.7/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1630, in _changeform_view
    'subtitle': str(obj) if obj else None,
  File "InvenTree/company/models.py", line 678, in __str__
    return f'{self.part.MPN} - {self.price} @ {self.quantity}'

Exception Type: AttributeError at /admin/company/supplierpricebreak/7/change/
Exception Value: 'SupplierPart' object has no attribute 'MPN'

```

**Comment by matmair** [comment]
@wengtad this was fixed yesterday with #1525

**Comment by wengtad** [comment]
oops, didn't notice this.

**Comment by eeintech** [comment]
@wengtad I just updated the demo instance, let us know if you find any other issue while using it. Remember the database is reset every week (Sunday) and every time I manually update it.

**Comment by wengtad** [comment]
@eeintech sure, if i find any issue will create an issue. thanks.
