### ISSUE TITLE
[BUILD] Part allocation/order improvements

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1531]
* Should let user decide to allocate parts for either incomplete build outputs (this was possible before) or the full build order
* Should let user create a "batch" purchase order of all parts used in the build, for either incomplete build outputs or the full build order
* Unallocating a single item should show which item will be unallocated

![image](https://user-images.githubusercontent.com/4020546/116436813-c5700100-a81a-11eb-83cf-bac2f4591054.png)

**Comment by matmair** [comment]
@eeintech there was a lot of work done on allocation - is this still valid?

**Comment by eeintech** [comment]
> @eeintech there was a lot of work done on allocation - is this still valid?

I'll take a look this week, thanks for letting me know 👍

**Comment by matmair** [comment]
@eeintech I think I am not getting what you mean by the requests 1 and 2 - I will let Oliver handle that as he self-assigned.

**Comment by SchrodingersGat** [comment]
@eeintech regarding 1) in particular, I have been thinking about fixing this for my own workplace, as it would fit our workflow better. Hopefully I have some time to allocate to this soon

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/issues/3012

**Comment by SchrodingersGat** [comment]
@eeintech can you confirm if you think this has now been completed in latest master?

**Comment by eeintech** [comment]
@SchrodingersGat I will look into this soon, bear with me busy busy right now :sweat_smile:

**Comment by eeintech** [comment]
@SchrodingersGat I seem to can't get around a migration issue:

``` bash
Backing up InvenTree database...
Backing Up Database: inventree
DumpError: A host name is required
  File "env-inventree/lib/python3.10/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "env-inventree/lib/python3.10/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
    self._save_new_backup(database)
  File "env-inventree/lib/python3.10/site-packages/dbbackup/management/commands/dbbackup.py", line 106, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "env-inventree/lib/python3.10/site-packages/dbbackup/db/base.py", line 92, in create_dump
    return self._create_dump()
  File "env-inventree/lib/python3.10/site-packages/dbbackup/db/postgresql.py", line 106, in _create_dump
    cmd = cmd + create_postgres_uri(self)
  File "env-inventree/lib/python3.10/site-packages/dbbackup/db/postgresql.py", line 13, in create_postgres_uri
    raise DumpError("A host name is required")
```

I don't understand why is it asking me a hostname, I tried with the hostname but no success.

cc @matmair

**Comment by eeintech** [comment]
This seems to be related to using PostGreSQL as backend :confused: 

If I create a new database and run `inv migrate` it gives the same error...

**Comment by eeintech** [comment]
Ok so running Django migration works fine so it is indeed the `dbbackup` library which is adding unnecessary requirement.

I commented those two lines in `dbbackup/postgresql.py`:
``` python
    if not host:
        raise DumpError("A host name is required")
```

and it works fine now... not sure why this became a requirement?

**Comment by eeintech** [comment]
Ok so next issue is:

``` bash
inv import-records -f main_data/main_database.json
Importing database records from 'InvenTree/main_data/main_database.json'
Traceback (most recent call last):
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "common_inventreesetting_key_key"
DETAIL:  Key (key)=(INVENTREE_DEFAULT_CURRENCY) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "InvenTree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: Problem installing fixture 'InvenTree/main_data/main_database.json.tmp.json': Could not load common.InvenTreeSetting(pk=37): duplicate key value violates unique constraint "common_inventreesetting_key_key"
DETAIL:  Key (key)=(INVENTREE_DEFAULT_CURRENCY) already exists.
```

I cannot seem to find a way to import data from our company instance to my local database...

**Comment by SchrodingersGat** [comment]
> ```shell
> DumpError: A host name is required
> ```

@matmair any thoughts on this one?

**Comment by SchrodingersGat** [comment]
```
inv import-records -f main_data/main_database.json
```

Add the `-c` option to ensure that you start with a clean database.

```
inv import-records -c -f main_data/main_database.json
```

**Comment by eeintech** [comment]
@SchrodingersGat 

## 0.8.x branch
``` bash
$ inv import-records -c -f main_data/main_database.json
Deleting all data from InvenTree database...
Importing database records from 'main_data/main_database.json'
Installed 8044 object(s) from 1 fixture(s)
Data import completed
Rebuilding Part objects
Rebuilding PartCategory objects
Rebuilding StockItem objects
Rebuilding StockLocation objects
Rebuilding Build objects
```

## Switch to master

``` bash
$ git checkout master
Switched to branch 'master'
$ git pull upstream master 
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 23 (delta 7), reused 12 (delta 2), pack-reused 0
Unpacking objects: 100% (23/23), 70.38 KiB | 1.08 MiB/s, done.
From github.com:inventree/InvenTree
 * branch                master     -> FETCH_HEAD
   b9de7e548..824a44a48  master     -> upstream/master
Updating 58f4cebe4..824a44a48
Fast-forward
 InvenTree/InvenTree/tests.py                 |   32 ++-
 InvenTree/config_template.yaml               |    4 +-
 InvenTree/locale/cs/LC_MESSAGES/django.po    |  801 +++++++++++++++++++++++++++++++++--------------------------------
...
 InvenTree/templates/js/translated/helpers.js |    6 +-
 README.md                                    |    1 +
 30 files changed, 11639 insertions(+), 10965 deletions(-)
```

## Master branch

``` bash
$ inv import-records -c -f main_data/main_database.json
Deleting all data from InvenTree database...
Importing database records from 'InvenTree/main_data/main_database.json'
Traceback (most recent call last):
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "barcode_data" of relation "part_supplierpart" does not exist
LINE 1: UPDATE "part_supplierpart" SET "barcode_data" = '', "barcode...
                                       ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "InvenTree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "InvenTree/env-inventree/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture 'InvenTree/main_data/main_database.json.tmp.json': Could not load company.SupplierPart(pk=1): column "barcode_data" of relation "part_supplierpart" does not exist
LINE 1: UPDATE "part_supplierpart" SET "barcode_data" = '', "barcode...
```

Any idea what's happening?

**Comment by SchrodingersGat** [comment]
Don't forget to run `invoke update`

**Comment by eeintech** [comment]
> Don't forget to run `invoke update`

Ouch right, migrations...

Ok so now I'm on master but none of the original requests are met:

> Should let user decide to allocate parts for either incomplete build outputs (this was possible before) or the full build order

I don't see how this is currently possible.

> Should let user create a "batch" purchase order of all parts used in the build, for either incomplete build outputs or the full build order

A batch of part can be allocated but not ordered.

> Unallocating a single item should show which item will be unallocated

Still the same as before.

Am I missing something? Isn't master where I should be looking into?

**Comment by SchrodingersGat** [comment]
Closing this one out as it has languished for three years now
