### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by martin323232** [inventree/InvenTree#1604]
Hi, 

tried to install Inventree using Docker on Windows 10. 
When pressing run in Docker Desktop, this is what happens.

> Creating directory /home/inventree/data/media

mkdir: can't create directory '/home/inventree/data/media': No such file or directory

Copying config file to /home/inventree/data/config.yaml

cp: can't create '/home/inventree/data/config.yaml': No such file or directory

Starting InvenTree server...

InvenTree configuration file 'config.yaml' not found - creating default file

Traceback (most recent call last):

File "/home/inventree/src/InvenTree/manage.py", line 22, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 855, in exec_module

File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

File "/home/inventree/src/InvenTree/InvenTree/settings.py", line 77, in <module>

shutil.copyfile(cfg_template, cfg_filename)

File "/usr/local/lib/python3.9/shutil.py", line 264, in copyfile

with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

FileNotFoundError: [Errno 2] No such file or directory: '/home/inventree/data/config.yaml'

Running InvenTree database migrations and collecting static files...

InvenTree configuration file 'config.yaml' not found - creating default file

Traceback (most recent call last):

File "/home/inventree/src/InvenTree/manage.py", line 22, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 855, in exec_module

File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

File "/home/inventree/src/InvenTree/InvenTree/settings.py", line 77, in <module>

shutil.copyfile(cfg_template, cfg_filename)

File "/usr/local/lib/python3.9/shutil.py", line 264, in copyfile

with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

FileNotFoundError: [Errno 2] No such file or directory: '/home/inventree/data/config.yaml'

**Comment by SchrodingersGat** [comment]
Hey @martin323232 first impression is that maybe you are trying to mount the "data" directory to an invalid location.

Did you read through the docker install guide? Where are you pointing the data directory to on your local machine?

**Comment by martin323232** [comment]
Hi @SchrodingersGat

I've read trough the docker install guide. Was not much help

> mount the "data" directory to an invalid location.
Problem is that I'm not sure where docker installed inventree. 
After searching, it could be in ProgramData, Public Documents and App/local folder.

Was not able to find anything there. 

Does it say in docker install guide how to change data location?

**Comment by martin323232** [comment]
Still no luck installing, found this: https://stackoverflow.com/questions/30741995/cannot-execute-run-mkdir-in-a-dockerfile/30742013
Can that be the problem?

Other docker images seems to install correctly.

**Comment by SchrodingersGat** [comment]
@martin323232 are you using a docker-compose script as per this install instructions?

If you can run through the precise series of steps you are using, that would be very helpful. I've not seen this issue before and would like to get to the bottom of it.

**Comment by SchrodingersGat** [comment]
@martin323232 if you have any further feedback on this please let me know. Otherwise closing due to inactivity.
