### ISSUE TITLE
"permission denied" error when starting background worker

### ISSUE THREAD

**Issue by BansheePrime** [inventree/InvenTree#1737]
I'm followint the  docker development server setup guide and when I say:
`docker-compose -f docker-compose.dev.yml up -d inventree-dev-worker`

I got:
```
Starting inventree-dev-worker ... error

ERROR: for inventree-dev-worker  Cannot start service inventree-dev-worker: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/home/inventree/docker/start_dev_worker.sh": permission denied: unknown

ERROR: for inventree-dev-worker  Cannot start service inventree-dev-worker: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/home/inventree/docker/start_dev_worker.sh": permission denied: unknown
ERROR: Encountered errors while bringing up the project.
```

I'm only learning and your help will be much appreciated.

**Comment by SchrodingersGat** [comment]
Have you copied the `docker-compose.yml` file exactly, or have you made alterations?

**Comment by BansheePrime** [comment]
> Have you copied the `docker-compose.yml` file exactly, or have you made alterations?

`docker-compose.yml` is changed by me in {volumes}  section with path to local data. As I understand error with `permission denied` is result of attempt to execute script  `start_dev_worker.sh` in container and there we acting as root or I missing something very obvious? Local sudo'ing gives same error. I'm working with WSL2 on Win10 so let me try to setting up project on my unix-box.

Thank you for taking your time to answer my questions. I'm learning and definitely missing something here.

**Comment by SchrodingersGat** [comment]
As with https://github.com/inventree/InvenTree/issues/1735 - are you manually building the dockerimage or downloading from dockerhub?

The inventree-worker and inventree-server contains should normally run "out of the box" without such issues...

**Comment by SchrodingersGat** [comment]
can you please try again now that #1735 has been fixed?

**Comment by BansheePrime** [comment]
Please excuse me for interrupting your work with weekend ahead. 
Right now in app Dockerfile line 1 is:
`FROM alpine:3.13 as base`

It worked for me only if I write:
`FROM python:alpine3.13 as base`

If you don't mind I'll take little more time to properly check things out.

**Comment by SchrodingersGat** [comment]
Ok, let me know what you discover!

**Comment by SchrodingersGat** [comment]
@BansheePrime did you ever get anywhere with this?

**Comment by BansheePrime** [comment]
> @BansheePrime did you ever get anywhere with this?

I'll do my best to show you results in a few days.

**Comment by BansheePrime** [comment]
@SchrodingersGat 
so today I started with setting up Inventree Docker Production Server on fresh and updated Fedora 34 server. Following your documentation I reached Database Migration step.
`[***@fedora inventree]$ sudo docker-compose run inventree-server invoke migrate`

output was:
```
Running InvenTree database migrations...
========================================
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/inventree/InvenTree/InvenTree/settings.py", line 90, in <module>
    CONFIG.get('debug', True)
AttributeError: 'NoneType' object has no attribute 'get'
ERROR: 1
```

Later I'll try to set Development Server and create image based of git source. If you want I can change from Fedora to Ubuntu.

**Comment by SchrodingersGat** [comment]
It looks like `settings.py` cannot find your config file. Have you edited settings.py or changed the default location of the configuration file

Can you share some more of the log?

**Comment by matmair** [comment]
@BansheePrime there were some updates to the docker setup - do you mind checking your config against the changes and reporting back if it works now?
