### ISSUE TITLE
Exception downloading BOM list

### ISSUE THREAD

**Issue by StijnLoeys1999** [inventree/InvenTree#1794]
Hey all,

When I tried to download the BOM list for an end product, i got an error. Does anyone know if I did something wrong, or if it was a bug?

ERROR message:
Environment:

Request Method: GET
Request URL: https://ivt.arcsec.space/part/10/bom-download?file_format=xls&cascade=True&parameter_data=True&stock_data=True&supplier_data=True&manufacturer_data=True&levels=2

Django Version: 3.2
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownx',
 'markdownify',
 'django_admin_shell',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'error_report.middleware.ExceptionProcessor']

Traceback (most recent call last):
  File "/home/inventree_prod/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/inventree_prod/src/InvenTree/part/views.py", line 1872, in get
    manufacturer_data=manufacturer_data,
  File "/home/inventree_prod/src/InvenTree/part/bom.py", line 324, in ExportBom
    data = dataset.export(fmt)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/tablib/core.py", line 427, in export
    return fmt.export_set(self, **kwargs)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/tablib/formats/_xls.py", line 47, in export_set
    cls.dset_sheet(dataset, ws)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/tablib/formats/_xls.py", line 129, in dset_sheet
    ws.write(i, j, col, bold)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "/home/inventree_prod/env/lib/python3.7/site-packages/xlwt/Row.py", line 254, in write
    raise Exception("Unexpected data type %r" % type(label))

Exception Type: Exception at /part/10/bom-download
Exception Value: Unexpected data type <class 'django.utils.functional.lazy.<locals>.__proxy__'>

![exception](https://user-images.githubusercontent.com/61249962/125038620-e912bb80-e095-11eb-82e4-ae62fd6e57d7.PNG)

**Comment by SchrodingersGat** [comment]
I can replicate this issue, it only seems to occur when:

- The format is set to `.xls` (`.xlsx` seems to work fine)
- "include stock data" is set to True

**Comment by eeintech** [comment]
@SchrodingersGat You beat me to it, I was not able to reproduce but with your conditions it does create this error indeed.
