### ISSUE TITLE
docker upgrade problematic

### ISSUE THREAD

**Issue by tkornack** [inventree/InvenTree#1994]
I'm running with docker and I tried pulling to the latest version 8646c73 (2021-08-20) using `docker-compose pull` and noticed two issues: 

1. The worker was broken. The error I'm seeing is a little garbled:  
  ERROR: for inventree-worker  Cannot start service inventree-worker: failed to create shim: OCI runtiCreating inventree-proxy  ... done
ker.sh": stat ./start_prod_worker.sh: no such file or directory: unknown

2. and during a run of the `docker-compose run inventree-server invoke update` the follow error appeared: 
```
  Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/home/inventree/.local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 338, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/inventree/.local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 291, in delete_file
    self.storage.delete(prefixed_path)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/files/storage.py", line 311, in delete
    os.remove(name)
PermissionError: [Errno 13] Permission denied: '/home/inventree/data/static/i18n/ru.label.js'
```

I've tried manually deleting the file in question, but that leads to other issues. 

anyone else seeing trouble here? Is there an easy fix or should I return to a backup?

**Comment by SchrodingersGat** [comment]
Some of the docker entrypoint functionality was changed in https://github.com/inventree/InvenTree/pull/1970

You should update your docker-compose file to match this - https://github.com/inventree/InvenTree/blob/master/docker/docker-compose.yml

That should solve issue 1. Not sure about 2, but maybe that will be fixed too?

**Comment by tkornack** [comment]
Thanks! Yes, issue #1 is solved and the site seems to work fine.

Issue #2 persists. I'm running on stock ubuntu 20.04.3 LTS. It appears right after logging `rendered all files in /home/inventree/InvenTree/templates/js/translated`.

**Comment by matmair** [comment]
@tkornack seems to be a permission problem form the log-message. Can you pls check that those are set right?

**Comment by SchrodingersGat** [comment]
Where have you mapped `/home/inventree/data/` to on your local drive?

**Comment by tkornack** [comment]
Thank you both @marmair and @SchrodingersGat for your help! 

As you suggested, I looked at the permissions on my /path/to/inventree_data and it was a patchwork of ownership by systemd-network and systemd-coredump. Easily fixed, and now the `invoke update` runs through perfectly. 

is this why some don't like systemd?

**Comment by matmair** [comment]
@tkornack I would say so but permissions are something everybody struggles with sometimes. No matter what system or service.

If you find anything in the docs that could have been phrased better or something that is missing feel free to create an issue or PR!

**Comment by tkornack** [comment]
I guess one doesn't normally test new installations very often, but I think it's possible that new installations on stock Ubuntu may indeed need to pay attention to the permissions in the data directory after the initialization and first run and set things straight if required.

**Comment by wudi-ayuan** [comment]
@tkornack  what is the user you change ownership to? I have the same issue but the unaccessible files are owned by root.

**Comment by tkornack** [comment]
I think it was a `docker` user in my case.
