### ISSUE TITLE
[BUG] After updating Error in start

### ISSUE THREAD

**Issue by AntoWkill** [inventree/InvenTree#2087]
Hello after updating i can't start the server 

ERROR: ModuleNotFoundError: No module named 'django_q'

`(inventree-env) root@xxx:/var/www/html/inventory/inventree/InvenTree# gunicorn -c gunicorn.conf.py InvenTree.wsgi
[2021-09-30 17:14:41 +0200] [2054610] [INFO] Starting gunicorn 20.1.0
[2021-09-30 17:14:41 +0200] [2054610] [INFO] Listening at: http://xxx:8001 (2054610)
[2021-09-30 17:14:41 +0200] [2054610] [INFO] Using worker: sync
[2021-09-30 17:14:41 +0200] [2054612] [INFO] Booting worker with pid: 2054612
[2021-09-30 17:14:41 +0200] [2054613] [INFO] Booting worker with pid: 2054613
[2021-09-30 17:14:42 +0200] [2054614] [INFO] Booting worker with pid: 2054614
[2021-09-30 17:14:42 +0200] [2054612] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/inventory/inventree/InvenTree/InvenTree/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_q'
[2021-09-30 17:14:42 +0200] [2054612] [INFO] Worker exiting (pid: 2054612)
[2021-09-30 17:14:42 +0200] [2054613] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/inventory/inventree/InvenTree/InvenTree/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_q'
[2021-09-30 17:14:42 +0200] [2054613] [INFO] Worker exiting (pid: 2054613)
[2021-09-30 17:14:43 +0200] [2054610] [WARNING] Worker with pid 2054613 was terminated due to signal 15
[2021-09-30 17:14:43 +0200] [2054614] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/inventory/inventree/InvenTree/InvenTree/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_q'
[2021-09-30 17:14:43 +0200] [2054614] [INFO] Worker exiting (pid: 2054614)
Traceback (most recent call last):
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/inventory/inventree/inventree-env/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>`

**Comment by matmair** [comment]
Hi @AntoWkill please use the templates when reporting bugs as the information asked there is needed for fast triage.

Seems to me that the requirements were not installed. Have you run 'inv update' after updating? Did you use GitHub to pull and what commit are you on? Did you restart the webserver and worker after upgrading?

**Comment by AntoWkill** [comment]
Last commit, i do inv update and restart webserver. 

I see error: ModuleNotFoundError: No module named 'django_q'
