### ISSUE TITLE
[BUG] User with no permissions generates exceptions

### ISSUE THREAD

**Issue by tambry** [inventree/InvenTree#2124]
**Describe the bug**
An user with no permissions only sees a blank page and exceptions are generated.

**To Reproduce**
1. Create an user
2. Don't assign any groups/roles
3. Login

```
Internal Server Error: /api/part/parameter/template/
Traceback (most recent call last):
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/opt/inventree/InvenTree/InvenTree/permissions.py", line 70, in has_permission
    result = users.models.RuleSet.check_table_permission(user, table, permission)
  File "/opt/inventree/InvenTree/users/models.py", line 214, in check_table_permission
    logger.info(f"User '{user.name}' failed permission check for {table}.{permission}")
  File "/opt/inventree/env/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'name'
```

**Expected behavior**
No errors, ideally maybe even an error message that the user has no permissions.

**Screenshots**
![2021-10-10_16-40-56_chrome](https://user-images.githubusercontent.com/1827708/136698231-8132222a-8d90-417d-930b-b2907ecbb672.png)

**Deployment Method**
Bare Metal

**Version Information**
8dddb200c7dcd9e979054e2d7a4ff295070a3a1d

**Comment by SchrodingersGat** [comment]
@tambry where are you seeing the error message? I have attempted to replicate by making a user without any permissions. I see the empty home screen, but no error message.

**Comment by tambry** [comment]
@SchrodingersGat In the server log. In my case in journalctl since I'm using systemd. But they also appear in the admin panel "Errors" page.

**Comment by SchrodingersGat** [comment]
Fixed in https://github.com/inventree/InvenTree/pull/2145
