### ISSUE TITLE
[BUG] column stock_stockitem.scheduled_for_deletion does not exist

### ISSUE THREAD

**Issue by r0l1** [inventree/InvenTree#2174]
**Describe the bug**
After updating from 0.4.5 to 0.5.1 following error occurs. I tried this multiple times and it's always the same problem.

```
inventree-db | 2021-10-17 19:32:57.456 UTC [38] ERROR:  column stock_stockitem.scheduled_for_deletion does not exist at character 913
inventree-db | 2021-10-17 19:33:27.807 UTC [191] ERROR:  column stock_stockitem.scheduled_for_deletion does not exist at character 59
inventree-db | 2021-10-17 19:33:27.807 UTC [191] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "stock_stockitem" WHERE "stock_stockitem"."scheduled_for_deletion"
inventree-worker | 19:33:27 [Q] INFO Processed [moon-arizona-bacon-west]
inventree-worker | 19:33:27 [Q] ERROR Failed [chicken-beer-grey-pip] - column stock_stockitem.scheduled_for_deletion does not exist
inventree-worker | LINE 1: ...OUNT(*) AS "__count" FROM "stock_stockitem" WHERE "stock_sto...
inventree-worker |                                                              ^
inventree-worker |  : Traceback (most recent call last):
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
inventree-worker |     return self.cursor.execute(sql, params)
inventree-worker | psycopg2.errors.UndefinedColumn: column stock_stockitem.scheduled_for_deletion does not exist
inventree-worker | LINE 1: ...OUNT(*) AS "__count" FROM "stock_stockitem" WHERE "stock_sto...
inventree-worker |                                                              ^
inventree-worker |
inventree-worker |
inventree-worker | The above exception was the direct cause of the following exception:
inventree-worker |
inventree-worker | Traceback (most recent call last):
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
inventree-worker |     res = f(*task["args"], **task["kwargs"])
inventree-worker |   File "/home/inventree/InvenTree/stock/tasks.py", line 33, in delete_old_stock_items
inventree-worker |     if items.count() > 0:
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 412, in count
inventree-worker |     return self.query.get_count(using=self.db)
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 519, in get_count
inventree-worker |     number = obj.get_aggregation(using, ['__count'])['__count']
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 504, in get_aggregation
inventree-worker |     result = compiler.execute_sql(SINGLE)
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
inventree-worker |     cursor.execute(sql, params)
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
inventree-worker |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
inventree-worker |     return executor(sql, params, many, context)
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
inventree-worker |     return self.cursor.execute(sql, params)
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
inventree-worker |     raise dj_exc_value.with_traceback(traceback) from exc_value
inventree-worker |   File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
inventree-worker |     return self.cursor.execute(sql, params)
inventree-worker | django.db.utils.ProgrammingError: column stock_stockitem.scheduled_for_deletion does not exist
inventree-worker | LINE 1: ...OUNT(*) AS "__count" FROM "stock_stockitem" WHERE "stock_sto...
inventree-worker |                                                              ^
inventree-worker |
inventree-worker |
inventree-worker | 19:35:27 [Q] INFO Process-1:3 processing [chicken-beer-grey-pip]
```

**Deployment Method**
Official Docker images

**Version Information**
0.5.1

**Comment by SchrodingersGat** [comment]
@r0l1 looks like there was a step missing from the documentation, for the docker upgrade process. I've added it in now:

https://inventree.readthedocs.io/en/latest/start/docker_prod/#update-database

You'll need to run this command before re-starting the server!

**Comment by SchrodingersGat** [comment]
Interesting @r0l1 - have not run into this one before.

https://github.com/inventree/InvenTree/blob/860cf46cb0083ffbd76d29bd3dbb0d58e8394320/docker/Dockerfile#L98

This line is in the dockerfile - should this not be sufficient?

**Comment by SchrodingersGat** [comment]
Ah ok that makes sense. 

As the docker container is running under the `inventree` user, would it even have privileges required to chown the data directory?
