### ISSUE TITLE
[BUG] sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by cdwilson** [inventree/InvenTree#2437]
**Describe the bug**
I occasionally see the following error in the `inv worker` logs:

```
16:39:39 [Q] ERROR Failed [tennessee-angel-one-echo] - database is locked : Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/Users/chris/Projects/inventree/InvenTree/InvenTree/tasks.py", line 268, in update_exchange_rates
    backend.update_rates(base_currency=base)
  File "/Users/chris/Projects/inventree/InvenTree/InvenTree/exchange.py", line 32, in update_rates
    super().update_rates(base=base_currency, symbols=symbols)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/djmoney/contrib/exchange/backends/base.py", line 61, in update_rates
    backend, _ = ExchangeBackend.objects.update_or_create(name=self.name, defaults={"base_currency": base_currency})
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/query.py", line 613, in update_or_create
    obj.save(using=self.db)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/envs/inventree/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
```

**Steps to Reproduce**

1. `inv server`
2. `inv worker`

**Expected behavior**
I'm not sure if this is something that is benign or not (I would assume not since it shows up as an `ERROR` in the logs)

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.5
Commit Hash: 88840e6ad
Commit Date: 2021-12-08
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False

**Comment by matmair** [comment]
Deploying to production with sqlite3 is not recommended. Both the UI and the worker need to access the DB at the same time. Sqlite3 locks the db when something is being written so this can happen. I suggest you deploy with Postgres or sql. We also provide a docker image, which has all the infra needed in the docker-compose included. Please consult the deployment docs for more information

**Comment by matmair** [comment]
Sqlite3 is mostly there for devs for easy developing and test deploying

**Comment by matmair** [comment]
@cdwilson if you require further information or want a second opinion please post here, else pls close 👍

**Comment by SchrodingersGat** [comment]
@cdwilson seconded. SQLite is not sufficient for a production database, and doubly so if you have more than one user.

![image](https://user-images.githubusercontent.com/10080325/145291932-aadd71fb-fb70-4114-bd69-46459b4fbc07.png)

**Comment by cdwilson** [comment]
@matmair @SchrodingersGat thanks for the pointers.  Some context: I am currently only using inventree for hobby use on my personal laptop, and I'm only using it as a single user (I initially didn't want to have to deal with running a real database)  I'll take a look into migrating to a more supported setup moving forward.  

> Sqlite3 locks the db when something is being written so this can happen. I suggest you deploy with Postgres or mysql.

In the mean time, are these errors something that could cause data integrity issues/data loss, or will the workers just keep retrying until the database is unlocked?  I just want to make sure that this is something that's safe to live with for now until I figure out how to migrate to a different database.

**Comment by SchrodingersGat** [comment]
I don't think that this will cause data integrity issues, but it may mean that certain operations are not performed if the worker or server processes cannot access the database.

**Comment by matmair** [comment]
@cdwilson for migration: we have data import/export commands included. Those support transferring a whole database via a single file.

**Comment by SchrodingersGat** [comment]
https://inventree.readthedocs.io/en/latest/start/migrate/
