### ISSUE TITLE
[BUG] <config_dir>/maintenance_mode_state.txt is written to

### ISSUE THREAD

**Issue by tambry** [inventree/InvenTree#2457]
**Describe the bug**
InvenTree tries to write to `<config_dir>/maintenance_mode_state.txt`.
<details>
<summary>log</summary>

```
[2021-12-14 23:13:39 +0200] [3310469] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/inventree/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/inventree/InvenTree/InvenTree/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/inventree/InvenTree/plugin/apps.py", line 17, in ready
    plugins.load_plugins()
  File "/opt/inventree/InvenTree/plugin/registry.py", line 64, in load_plugins
    set_maintenance_mode(True)
  File "/opt/inventree/env/lib/python3.9/site-packages/maintenance_mode/core.py", line 75, in set_maintenance_mode
    backend.set_value(value)
  File "/opt/inventree/env/lib/python3.9/site-packages/maintenance_mode/backends.py", line 66, in set_value
    write_file(settings.MAINTENANCE_MODE_STATE_FILE_PATH, value)
  File "/opt/inventree/env/lib/python3.9/site-packages/maintenance_mode/io.py", line 26, in write_file
    handler = open(file_path, 'w+')
OSError: [Errno 30] Read-only file system: '/opt/inventree/InvenTree/maintenance_mode_state.txt'
```
</details>

In my setup I'm using systemd to sandbox InvenTree to limit potential compromise of the machine.
<details>
<summary>inventree.service</summary>

```
[Unit]
Description=InvenTree Inventory Management System
Documentation=https://inventree.readthedocs.io/

[Service]
ExecStart=/opt/inventree/env/bin/gunicorn -c gunicorn.conf.py InvenTree.wsgi -b '[::1]:4000' -w 3

User=inventree
WorkingDirectory=/opt/inventree/InvenTree
StateDirectory=inventree

Restart=on-failure

CapabilityBoundingSet=
DevicePolicy=closed
IPAddressAllow=localhost
IPAddressDeny=any
LockPersonality=yes
NoNewPrivileges=yes
ProcSubset=pid
PrivateDevices=yes
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible
ProtectSystem=strict
PrivateTmp=yes
PrivateUsers=yes
RemoveIPC=yes
RestrictAddressFamilies=AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
UMask=077

[Install]
WantedBy=multi-user.target
```
</details>

The option responsible is `ProtectSystem=strict`. Relaxing it (removing it) allows InvenTree to work.

The previous version I was at (189db604faf5ae0e44e1c14a6ef8f537a8974177) didn't seem to write to the config directory. It seems logical for it not to do that.  
Is this considered working as intended or a supported configuration, but I simply ought to change `MAINTENANCE_MODE_STATE_FILE_PATH`?

**Steps to Reproduce**
Have the config directory on a read-only filesystem and observe InvenTree's failure to start.

**Expected behavior**
InvenTree never tries to write to the config directory.

**Deployment Method**
- [ ] Docker
- [x] Bare Metal

**Version Information**
597d26d3d409b1eb202203af521ca26d87f07cf2

**Comment by matmair** [comment]
@tambry InvenTree now contains a method to send the server into a maintenance mode. For this, the file you mentioned is used. We need a writeable directory for this and as it is a configuration file it is written to the config dir. You can change where the file is to your liking. Our example configs assume that the config dir is writeable, maybe we should change that.

**Comment by tambry** [comment]
Seems like an useful feature and logical. `django-maintenance-mode` mentions the case of the default one not being writable:
```
# by default, a file named "maintenance_mode_state.txt" will be created in the settings.py directory
# you can customize the state file path in case the default one is not writable
```
I'll try changing mine to the state directory (`/var/lib/inventree`) later today and seems like defaulting to that might be a better choice to make such sandboxing easier by default.

**Comment by matmair** [comment]
>
> I'll try changing mine to the state directory (`/var/lib/inventree`) later today and seems like defaulting to that might be a better choice to make such sandboxing easier by default.

I think for most configs it makes more sense to keep it in the config dir as we do not really know where ppl place their installs and I know of multiple institutions that have multiple installs on the same server. That would not work out of the box if we set a static dir that is always the same.

**Comment by tambry** [comment]
Hardcoding the one I use definitely wouldn't be a sensible default. If there were some `state_root` we could default to below that. My "state root" is `/var/lib/inventree` so I have `/var/lib/inventree/database.sqlite3`, `/var/lib/inventree/media` and `/var/lib/inventree/static`.

**Comment by tambry** [comment]
Thank you.

I edited `MAINTENANCE_MODE_STATE_FILE_PATH` to point where I need it to and all's good. Closing as there's nothing to change without introducing a base state directory path to use as a default for this and likely others too.

> InvenTree now contains a method to send the server into a maintenance mode.
Is there a way for an admin to trigger this? Reading the code I don't see any.
