### ISSUE TITLE
[BUG] Demo: Error 500 when accessing Widget assemblies

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#2530]
In the demo, clicking on "Widget Assembly" and "Widget Assembly Variants" parts result in 500 server error.

![image](https://user-images.githubusercontent.com/4020546/148767343-736ee38f-d40d-45a2-a96f-f6e1056f5080.png)

![image](https://user-images.githubusercontent.com/4020546/148767376-0377219c-461a-4a59-8fc3-919b625fe30d.png)

![image](https://user-images.githubusercontent.com/4020546/148767413-11716d1f-399a-4876-a15a-81671bec76fa.png)

**Comment by SchrodingersGat** [comment]
```

Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
return super().dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
context = self.get_context_data(object=self.object)

File "/home/inventree/InvenTree/part/views.py", line 397, in get_context_data
ctx = self.get_pricing(self.get_quantity())

File "/home/inventree/InvenTree/part/views.py", line 413, in get_pricing
ctx = PartPricing.get_pricing(self, quantity, currency)

File "/home/inventree/InvenTree/part/views.py", line 1232, in get_pricing
purchase_price = part.get_bom_price_range(quantity, purchase=True)

File "/home/inventree/InvenTree/part/models.py", line 1716, in get_bom_price_range
prices = item.sub_part.get_price_range(q * i, internal=internal, purchase=purchase)

File "/home/inventree/InvenTree/part/models.py", line 1760, in get_price_range
purchase_price = self.get_purchase_price(quantity)

File "/home/inventree/InvenTree/part/models.py", line 1835, in get_purchase_price
prices = [convert_money(item.purchase_price, currency).amount for item in self.stock_items.all() if item.purchase_price]

File "/home/inventree/InvenTree/part/models.py", line 1835, in <listcomp>
prices = [convert_money(item.purchase_price, currency).amount for item in self.stock_items.all() if item.purchase_price]

File "/home/inventree/.local/lib/python3.8/site-packages/djmoney/contrib/exchange/models.py", line 108, in convert_money
amount = value.amount * get_rate(value.currency, currency)

File "/home/inventree/.local/lib/python3.8/site-packages/djmoney/contrib/exchange/models.py", line 49, in get_rate
result = _get_rate(source, target, backend)

File "/home/inventree/.local/lib/python3.8/site-packages/djmoney/contrib/exchange/models.py", line 60, in _get_rate
raise MissingRate("Rate %s -> %s does not exist" % (source, target))

djmoney.contrib.exchange.exceptions.MissingRate: Rate USD -> EUR does not exist
```

**Comment by SchrodingersGat** [comment]
This will need to be fixed before release!

**Comment by eeintech** [comment]
Found another: https://demo.inventree.org/part/85/

**Comment by SchrodingersGat** [comment]
Error is gone now, must have been as a result of someone changing a setting on the server?

**Comment by matmair** [comment]
@SchrodingersGat maybe we should restrict changes on that install?
