### ISSUE TITLE
[BUG] Docker Container not able to start

### ISSUE THREAD

**Issue by jkalousek** [inventree/InvenTree#2724]
**Describe the bug**/**Steps to Reproduce**
I'm trying to run :stable inventree using portainer stack - which should in general be regular docker-compose:
```
version: "3.8"

services:
    inventree-db:
        container_name: inventree-db
        image: postgres:13
        # ports:
        #    - 5432/tcp
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=inventree
            - POSTGRES_PASSWORD=<REDACTED>
        volumes:
            - data-db:/var/lib/postgresql/data/
        restart: unless-stopped
        networks:
          - default

    # InvenTree web server services
    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:stable

        ports:
            - 890:8000
        depends_on:
            - inventree-db
        volumes:
            - data:/home/inventree/data
        env_file:
            - stack.env
        restart: unless-stopped
        networks:
          - default

    # Background worker process handles long-running or periodic tasks
    inventree-worker:
        container_name: inventree-worker
        image: inventree/inventree:stable
        command: invoke worker
        depends_on:
            - inventree-db
            - inventree-server
        volumes:
            - data:/home/inventree/data
        env_file:
            - stack.env
        restart: unless-stopped
        networks:
          - default

volumes:
    data:
    data-db:

networks:
  default:
```

Proxy is missing because its functions are handled by other server.
Files are created correctly in specified folders but then I get following errors and constant restart loop...

```
InvenTree translation coverage: 15%
Waiting for database...
Database connection sucessful!
Traceback (most recent call last):
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/inventree/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/label/apps.py", line 39, in ready
    self.create_labels()  # pragma: no cover
  File "/home/inventree/InvenTree/label/apps.py", line 45, in create_labels
    self.create_stock_item_labels()
  File "/home/inventree/InvenTree/label/apps.py", line 121, in create_stock_item_labels
    if StockItemLabel.objects.filter(label=filename).exists():
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 552, in has_results
    return compiler.has_results()
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
3/home/inventree/data/config.yaml exists - skipping
```

I did try to do [Create Database](https://inventree.readthedocs.io/en/latest/start/docker_prod/#create-database) step from docs but I got message `database "inventree" already exists`. So container does setup database automatically now?

I also tried to remove everything and go from clean state multiple times but no luck.

Any Ideas what I could do? Thank You.

**Deployment Method**
- [ x ] Docker
- [ ] Bare Metal

**Comment by jkalousek** [comment]
Ok I figure it out as I'm using portainer, I'm not able to run regular docker-compose or create containers one by one during install. I had to add `command: invoke update` to inventree-server, let it update and than watch output until migrations were finished, than remove command and than inventree started.
Please consider to maybe run update once automatically after each start of container?
