### ISSUE TITLE
[BUG] Uploading image not working

### ISSUE THREAD

**Issue by pawcio0928** [inventree/InvenTree#2799]
Hi, I have problem with Inventree version [0.6.3] when I trying upload image from file or from link. After selected image file and clicking Submit I always get error:
 Unhandled Error Code
Error code: 500
URL: /api/part/2008/

I have deployment on Docker. I also tested adding file as attachment to ensure that my configuration of media folder is correct.

Hope that is easy to fix.
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/5786244/161397535-c4cbe9b7-a740-4f2e-be53-a4d527d4a426.png">

**Comment by matmair** [comment]
Hi there @pawcio0928 !
Could you add the version information from the version modal (upper right corner) and look into the logs for an error message? Error 500 is something on the server but not very descriptive. There is a [help page](https://inventree.readthedocs.io/en/latest/settings/logs/) on that.

**Comment by SchrodingersGat** [comment]
Yep @pawcio0928 as @matmair says we'll need to see what the error message actually is :)

**Comment by pawcio0928** [comment]
Thank you @matmair  and @SchrodingersGat. 

I miss that errors in admin panel.


Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/generics.py", line 288, in patch
return self.partial_update(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 82, in partial_update
return self.update(request, *args, **kwargs)

File "/home/inventree/InvenTree/part/api.py", line 586, in update
response = super().update(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 68, in update
self.perform_update(serializer)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 78, in perform_update
serializer.save()

File "/home/inventree/InvenTree/InvenTree/serializers.py", line 183, in save
super().save(**kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 200, in save
self.instance = self.update(self.instance, validated_data)

File "/home/inventree/InvenTree/InvenTree/serializers.py", line 195, in update
instance = super().update(instance, validated_data)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 983, in update
instance.save()

File "/home/inventree/InvenTree/part/models.py", line 457, in save
super().save(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/mptt/models.py", line 1014, in save
super(MPTTModel, self).save(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
self.save_base(using=using, force_insert=force_insert,

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
updated = self._save_table(

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 855, in _save_table
values = [(f, None, (getattr(self, f.attname) if raw else f.pre_save(self, False)))

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 855, in <listcomp>
values = [(f, None, (getattr(self, f.attname) if raw else f.pre_save(self, False)))

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 302, in pre_save
file.save(file.name, file.file, save=False)

File "/home/inventree/.local/lib/python3.8/site-packages/stdimage/models.py", line 29, in save
super().save(name, content, save)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/fields/files.py", line 89, in save
self.name = self.storage.save(name, content, max_length=self.field.max_length)

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/files/storage.py", line 54, in save
name = self._save(name, content)

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/files/storage.py", line 279, in _save
fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)

PermissionError: [Errno 13] Permission denied: '/home/inventree/data/media/part_images/448692_1.png'


# Version Information:
InvenTree-Version: 0.6.3
Django Version: 3.2.12
Commit Hash: 86b0b50
Commit Date: 2022-03-30
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

I checked in a folder on a server but file is not added.

**Comment by SchrodingersGat** [comment]
It would appear that the server (running inside the docker container application) does not have write permission to the /media directory.

Did you set that up according to the docs? How / where are you storing the uploaded media files?

**Comment by pawcio0928** [comment]
@SchrodingersGat I found out that I migrated from old version I just copied folder with part_images and this made problem in my configuration. Thank you for your help. 

I have one suggestion to add webp image as supported format.
