### ISSUE TITLE
[BUG] BOM Import from XLSX

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#2940]
**Describe the bug**
I'm trying to import a fairly long BOM using an excel spreadsheet and I get the attached error

**Steps to Reproduce**

Upload the attached file into the BOM

**Expected behavior**
BOM is imported

<img width="803" alt="image" src="https://user-images.githubusercontent.com/96780897/167268579-cfed26e3-400c-4116-a4a0-6cc9e89f632e.png">

**Deployment Method**
- [ x] Docker
- [ ] Bare Metal

**Version Information**
0.63.0
[InvenTree_BOM_Template (1).xlsx](https://github.com/inventree/InvenTree/files/8645811/InvenTree_BOM_Template.1.xlsx)

**Comment by spectre-ns** [comment]
Works with CSV if this is expected behavior apologies and I will close

**Comment by SchrodingersGat** [comment]
It should work with `.xlsx` - please find the error log in the admin interface and post here. Ref: https://inventree.readthedocs.io/en/latest/settings/logs/

**Comment by spectre-ns** [comment]
See Error log below:
Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
return self.create(request, *args, **kwargs)

File "/home/inventree/InvenTree/part/api.py", line 1573, in create
data = serializer.extract_data()

File "/home/inventree/InvenTree/InvenTree/serializers.py", line 471, in extract_data
match = self.match_column(header, model_field_names, exact=True)

File "/home/inventree/InvenTree/InvenTree/serializers.py", line 424, in match_column
column_name = column_name.strip()

AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by spectre-ns** [comment]
Appears to be calling a method witch is not present in the XLSX file parser.

**Comment by matmair** [comment]
@spectre-ns are you sure all columns are defined in the file you are uploading? So each column that has data also has a heading in the first row?

**Comment by SchrodingersGat** [comment]
It would be interesting to know if the datasets are the same between the .csv and .xlsx files!

**Comment by spectre-ns** [comment]
I thought that they were when I did it. Maybe there is something subtle. Is it possible that the XLSX file has an extra row with no data in it? I've had instances in excel where the dimensions aren't automatically cleaned up so the file size balloons with tons of empty rows and columns that are still expressed in the file even though they are infact blank. 

Also I'm really sorry for all the messages on multiple threads I feel like I'm causing a chaos but I really like what you guys have done here and I'm wishing I could throw tons of dev time at this project unfortunately I work for a start up that is very resource contained... Hopefully we can give back provided we find success long term.

**Comment by SchrodingersGat** [comment]
@spectre-ns thanks for providing feedback and raising error reports - this does help us immensely! 

If you or your company do have the ability to contribute back to this project, either with dev time or financial support, that would be greatly appreciated! Our dev team is very small and there's a lot of work to be done to support all the great ideas our users want to see implemented!

**Comment by SchrodingersGat** [comment]
@spectre-ns please check latest master and see if your import issue is resolved.

**Comment by spectre-ns** [comment]
Thanks I will give it a try in a bit! You guys are so fast.
