### ISSUE TITLE
[BUG] PO Upload Results in "Internal Server Error"

### ISSUE THREAD

**Issue by spectre-ns** [inventree/InvenTree#2941]
**Describe the bug**
Attempting to upload a ~~BOM~~ PurchaseOrder results in a white screen with bold fond saying "Internal Server Error"

**Steps to Reproduce**
Create a Purchase order
Click "Upload File"

**Expected behavior**
System allows input of multiple parts with an upload.

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/96780897/167269135-f816eb44-830a-4e3c-919f-f89f82ebe461.png">

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/96780897/167269160-63ed1647-74c9-4695-ad6e-11bb25053e9b.png">

**Deployment Method**
- [ X] Docker
- [ ] Bare Metal

**Version Information**
0.63.0

**Logs**
Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
compile_func = self.tags[command]

KeyError: 'order.status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
template = self.resolve_template(self.template_name)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/response.py", line 65, in resolve_template
return get_template(template, using=self.using)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
return engine.get_template(template_name)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
return Template(self.engine.get_template(template_name), self)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
template, origin = self.find_template(template_name)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
template = loader.get_template(name, skip=skip)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 58, in get_template
template = super().get_template(template_name, skip)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
return Template(

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
self.nodelist = self.compile_nodelist()

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
return parser.parse()

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
nodelist = parser.parse()

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
nodelist = parser.parse(('endblock',))

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
self.invalid_block_tag(token, command, parse_until)

File "/home/inventree/.local/lib/python3.8/site-packages/django/template/base.py", line 522, in invalid_block_tag
raise self.error(

django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 14: 'order.status', expected 'endblock'. Did you forget to register or load this tag?

**Comment by SchrodingersGat** [comment]
@eeintech I believe you worked on the PO importer last - any thoughts here?

**Comment by eeintech** [comment]
Looks like an issue with the templates, I can look at it soon, I remembered the BOM import had a similar issue

**Comment by eeintech** [comment]
@SchrodingersGat The fix is in #2812 but is not part of the `0.6.3` release. Should you release `0.6.4` soon, do you mind cherry picking that one too? Then OP issue will be fixed, thanks!

**Comment by spectre-ns** [comment]
@eeintech Should I close this ticket? Sounds like it has been addressed?

**Comment by eeintech** [comment]
@spectre-ns I would wait til `0.6.4` is relased and your issue solved :wink:

**Comment by spectre-ns** [comment]
Ok. sounds good didn't know the gitflow being used here. Other places merging to master would close it. Thanks for the heads up!

**Comment by matmair** [comment]
@spectre-ns our normal flow would be to close this after merging but when a backport is in order we normally leave it open till that is done. @SchrodingersGat can close when the backport is in as he is in @inventree/triage (and is @inventree/maintainer )

**Comment by SchrodingersGat** [comment]
Release branch for [0.6.4 is here](https://github.com/inventree/InvenTree/pull/2963)

**Comment by eeintech** [comment]
@spectre-ns Should work now with `0.6.4` :smiley:
