### ISSUE TITLE
[BUG] Can't allocate same line item to multiple shipments

### ISSUE THREAD

**Issue by maksimstojkovic** [inventree/InvenTree#2987]
**Describe the bug**

Attempting to allocate a line item to multiple shipments fails, returning a 500 error code in the console.

**Steps to Reproduce**

1. Create SO and add line item with quantity > 1.
2. Create 2 shipments.
3. Allocate 1 unit to shipment 1.
4. Allocate non-zero number of units to shipment 2.

**Expected behavior**

Line item should increase Allocated count and additional list item should be added to left-hand side '+' dropdown menu.

However, nothing happens and the a 500 status error appears in the console.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/18454392/168203478-438cd8e0-a970-448a-b24f-3c44c39e5c0e.png">

**Deployment Method**
- [x] Docker
- [ ] Bare Metal
- [x] Demo Server

**Version Information**

InvenTree-Version: 0.7.0 dev
Django Version: 3.2.13
Commit Hash: a68db90
Commit Date: 2022-05-12
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

**Comment by SchrodingersGat** [comment]
Can you please post the content of the 500 error message? You can access historical error logs via the admin interface

https://inventree.readthedocs.io/en/latest/settings/logs/

**Comment by maksimstojkovic** [comment]
```
Type:
IntegrityError

Path:
http://localhost:8000/api/order/so/5/allocate/

Info:
(1062, "Duplicate entry '8-5' for key 'order_salesorderallocation_line_id_item_id_bb8750cc_uniq'")

When:
May 13, 2022, 11:49 a.m.

Data:
Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 320, in _query
self._do_get_result(db)

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
self._result = result = self._get_result()

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 352, in _get_result
return self._get_db().store_result()

MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '8-5' for key 'order_salesorderallocation_line_id_item_id_bb8750cc_uniq'")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/home/inventree/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
return self.create(request, *args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
self.perform_create(serializer)

File "/home/inventree/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
serializer.save()

File "/home/inventree/InvenTree/order/serializers.py", line 1007, in save
order.models.SalesOrderAllocation.objects.create(

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
obj.save(force_insert=True, using=self.db)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
self.save_base(using=using, force_insert=force_insert,

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
updated = self._save_table(

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
return manager._insert(

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
cursor.execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
return super().execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 320, in _query
self._do_get_result(db)

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
self._result = result = self._get_result()

File "/usr/lib/python3.8/site-packages/MySQLdb/cursors.py", line 352, in _get_result
return self._get_db().store_result()

django.db.utils.IntegrityError: (1062, "Duplicate entry '8-5' for key 'order_salesorderallocation_line_id_item_id_bb8750cc_uniq'")
```

**Comment by SchrodingersGat** [comment]
Cheers, will look into this one.

**Comment by SchrodingersGat** [comment]
@maksimstojkovic this has now been fixed in master :)
