### ISSUE TITLE
[BUG] could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by KenwoodFox** [inventree/InvenTree#3160]
**Describe the bug**
Some items failure to serialize and throw a 500 error on browsing

```
Internal Server Error: /api/part/category/tree/
Traceback (most recent call last):
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inventree/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/home/inventree/.local/lib/python3.9/site-packages/user_sessions/middleware.py", line 56, in process_response
    request.session.save()
  File "/home/inventree/.local/lib/python3.9/site-packages/user_sessions/backends/db.py", line 81, in save
    obj.save(force_insert=must_create, using=using)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/inventree/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: could not serialize access due to concurrent update
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31870999/172514716-63b0c3db-c15b-4202-bd67-0e12fb1b5bbc.png)

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
```
# Version Information:
InvenTree-Version: 0.7.0
Django Version: 3.2.13
Commit Hash: 044315a
Commit Date: 2022-05-24
Database: postgresql
Debug-Mode: False
Deployed using Docker: True
```

**Comment by KenwoodFox** [comment]
Looks like the action i spawned failed :sweat:

**Comment by SchrodingersGat** [comment]
@KenwoodFox have you seen this issue multiple times, is it repeatable? I have never seen this issue before, so we need to be able to replicate it :)

**Comment by KenwoodFox** [comment]
On a few parts yeah, i should note also I used `kintree` to generate the parameters and manufacturer information, via the api.

Im not sure i see a pattern with what parts it seems to affect, ill admit its not super.. consistant, affecing about 1 in 3 page loads for affected parts, and never occuring on some parts.

**Comment by KenwoodFox** [comment]
Just confirmed, it happens with parts created entirely via the web interface, nothing fancy at all.

**Comment by SchrodingersGat** [comment]
Did you make any changes during the install process? In particular, did you adjust any database configuration settings?

**Comment by KenwoodFox** [comment]
No i did not, just installed an hour ago, pretty stock stuff, anything i can check?

**Comment by SchrodingersGat** [comment]
Nothing that immediately jumps to mind. Please see what else you can find in the logs (if anything). This is a new one! 

If you can find any rhyme or reason to which pages the failure occurs on, or any other "common" points of failure, that would be a great start for debugging.

**Comment by KenwoodFox** [comment]
Ill do some sluething! I noticed a log level env variable in the `.env` file, maybe turning that to `DEBUG` would be a good place to start?

**Comment by matmair** [comment]
@KenwoodFox could you [check the logs]( https://inventree.readthedocs.io/en/latest/settings/logs/) and post us the content of one?

**Comment by matmair** [comment]
We found the same issue on the demo server. It is connected to the serialize setting in your setup (only if you use Postgres).
As we did not here back for more then 2 weeks I am closing this now. Feel free to reopen if you want to add anything @KenwoodFox

**Comment by KenwoodFox** [comment]
Sorry about the delay, glad to hear that it shows up somewhere, its just a settings issue then? Is that a fix or, should i work on making a PR, iirc i do use postgres.

**Comment by matmair** [comment]
@KenwoodFox this is expected behaviour by Postgres and Django; Read more here and set the setting in your `config.yaml` accordingly
https://docs.djangoproject.com/en/dev/ref/databases/#isolation-level

**Comment by SchrodingersGat** [comment]
@matmair given that this is explicitly the default behaviour (in `settings.py`) for a postgres DB I don't think it is correct for us to close this out. Either we change the default behaviour (breaking change) or work out how to handle such errors

**Comment by matmair** [comment]
@SchrodingersGat I am not sure in what straight forward way one should handle this error. There would be a lot to take into account and edge cases to consider will crop up for a long time in production if we start fiddling this low in the stack.

My recommendation is to switch the default behaviour. My guess is that the majority of admins do not even know this setting is there - this only matters on huge, cached instances.
Let's add  a breaking release note so the few using it can reconfigure.

**Comment by KenwoodFox** [comment]
> 

So this is the solution, and its expected behavior? I guess thats good for me but i would agree with @matmair that this is weird, i had a stock install, and followed all the docs and still eneded up with an error that did not make sense or lead me to know what tp add to the config.yaml, setting it as default makes sense to me?

**Comment by matmair** [comment]
@KenwoodFox the default will lead to not reproducible API results in some corner cases. That is why it is setup that way currently. You only run into errors if you have a bunch of concurrent access.
