### ISSUE TITLE
[BUG] Cannot import parts

### ISSUE THREAD

**Issue by jkanaka** [inventree/InvenTree#3234]
Hi,

I am unable to import Parts from file using procedure from the manual. 

**Steps to Reproduce**
1. Go to InvenTree Admin \Parts \ Import
2. Select Excel file (previously prepared by Export option)
3. Press import

Cannot call get_descendants on unsaved Part instances
1, None, None, None, None, None, None, None, None, None, None, None, Test, None, Description, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None

Traceback (most recent call last):
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 644, in import_row
diff = self.get_diff_class()(self, original, new)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 204, in __init__
self.left = self._export_resource_fields(resource, instance)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 225, in _export_resource_fields
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 225, in <listcomp>
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/resources.py", line 845, in export_field
return field.export(obj)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/fields.py", line 122, in export
value = self.get_value(obj)
File "/home/inventree/.local/lib/python3.9/site-packages/import_export/fields.py", line 98, in get_value
value = value()
File "/home/inventree/InvenTree/part/models.py", line 1403, in allocation_count
self.build_order_allocation_count(**kwargs),
File "/home/inventree/InvenTree/part/models.py", line 1327, in build_order_allocation_count
query = self.build_order_allocations(**kwargs).aggregate(
File "/home/inventree/InvenTree/part/models.py", line 1313, in build_order_allocations
variants = self.get_descendants(include_self=True)
File "/home/inventree/.local/lib/python3.9/site-packages/mptt/models.py", line 391, in _fn
raise ValueError(
ValueError: Cannot call get_descendants on unsaved Part instances

**Deployment Method**
Docker

**Version Information**
0.7.0

**Comment by SchrodingersGat** [comment]
Hey @jkanaka thanks for reporting. This will be fixed in the upcoming 0.8.0 release - see https://github.com/inventree/InvenTree/pull/3235

Please note that the whole import process will be overhauled in the near future - https://github.com/inventree/InvenTree/issues/3101
