### ISSUE TITLE
[BUG] Dev version - Update Master Failed - AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Bbillyben** [inventree/InvenTree#3421]
**Describe the bug**
I would update from github/master branch, already in master, I launch the update command, lands to a failed with error.

**Steps to Reproduce**

1. cd in InvenTree folder
2. git fectch/pull
3. run : `docker-compose run inventree-dev-server invoke update`

**Expected behavior**
end without error

error : 
```
Added plugin directory: '/home/inventree/dev/plugins'
Loading plugins from directory 'plugin.builtin'
Loading plugins from directory 'plugin.samples'
Loading plugins from directory 'plugins'
Loading plugins from directory '/home/inventree/dev/plugins'
Traceback (most recent call last):
  File "/usr/lib/python3.9/pkgutil.py", line 416, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/inventree/dev')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/inventree/dev/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/inventree/dev/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/inventree/dev/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/inventree/dev/env/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/plugin/apps.py", line 46, in ready
    registry.collect_plugins()
  File "/home/inventree/InvenTree/plugin/registry.py", line 258, in collect_plugins
    modules = get_plugins(importlib.import_module(plugin), InvenTreePlugin, path=parent_path)
  File "/home/inventree/InvenTree/plugin/helpers.py", line 215, in get_plugins
    modules = get_modules(pkg, path=path)
  File "/home/inventree/InvenTree/plugin/helpers.py", line 183, in get_modules
    for loader, name, _ in pkgutil.walk_packages(path):
  File "/usr/lib/python3.9/pkgutil.py", line 88, in walk_packages
    for info in iter_modules(path, prefix):
  File "/usr/lib/python3.9/pkgutil.py", line 130, in iter_modules
    for i in importers:
  File "/usr/lib/python3.9/pkgutil.py", line 420, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1601, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1476, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'

```

full update log : 
[update_master.log](https://github.com/inventree/InvenTree/files/9196499/update_master.log)

finding maybe some related info :
https://stackoverflow.com/questions/48195727/running-collectstatic-on-server-attributeerror-posixpath-object-has-no-attr

**Deployment Method**
- [x] Docker
- [ ] Bare Metal

**Version Information**
VM : Debian GNU/Linux 10 (buster) / Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
Docker version 20.10.17, build 100c701
docker-compose version 1.29.2, build 5becea4c
git version 2.20.1

**Comment by SchrodingersGat** [comment]
@Bbillyben thanks for reporting. This is probably due to a [recent PR](https://github.com/inventree/InvenTree/pull/3392). I'll look into it.

**Comment by Bbillyben** [comment]
not at all (as far I can tell)

I'm just playing with the API since yesterday

I've done a `git reset --hard origin/master` and run the update,
and exactly the same issue

**Comment by Bbillyben** [comment]
After a `git fetch origin pull/3423/head && git checkout FETCH_HEAD` related to pull https://github.com/inventree/InvenTree/pull/3423

seems working (but i've lost my test data in the process, I should have save them!)
