### ISSUE TITLE
[Error] Admin panel doesn't load after upgrade: Reverse for 'app_list' with keyword arguments '{'app_label': 'common'}' not found.

### ISSUE THREAD

**Issue by Zontex** [inventree/InvenTree#3476]
**Describe the bug**

After upgrading from 0.7.4 to 0.8.0 the admin panel doesn't load, and shows the following data:
```
Environment:

Request Method: GET
Request URL: https://www.example.com/admin/

Django Version: 3.2.14
Python Version: 3.10.4
Installed Applications:
['build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'plugin.apps.PluginAppConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'user_sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'maintenance_mode',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownify',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'allauth_2fa',
 'sslserver']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'x_forwarded_for.middleware.XForwardedForMiddleware',
 'user_sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'InvenTree.middleware.InvenTreeRemoteUserMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'InvenTree.middleware.CustomAllauthTwoFactorMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'InvenTree.middleware.Check2FAMiddleware',
 'maintenance_mode.middleware.MaintenanceModeMiddleware',
 'InvenTree.middleware.InvenTreeExceptionProcessor']



Traceback (most recent call last):
  File "/home/inventree/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/inventree/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 522, in index
    app_list = self.get_app_list(request)
  File "/home/inventree/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 505, in get_app_list
    app_dict = self._build_app_dict(request)
  File "/home/inventree/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 487, in _build_app_dict
    'app_url': reverse(
  File "/home/inventree/env/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/inventree/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /admin/
Exception Value: Reverse for 'app_list' with keyword arguments '{'app_label': 'common'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>part|build|order|stock)/$']
```

**Steps to Reproduce**

1. Download the clean version of 0.8.0 and invoke the update from 0.7.4
2. Go to the web panel and get this error

**Expected behavior**

Admin panel load as expected.

**Deployment Method**
- [ ] Docker
- [X] Bare Metal

# Version Information:

InvenTree-Version: 0.8.0
Django Version: 3.2.14
Commit Hash: 6118d1319
Commit Date: 2022-08-01
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by Zontex** [comment]
Duplicate #3355

**Comment by SchrodingersGat** [comment]
@Zontex I'm going to re-open this as #3355 was closed out. Looks like this is somewhat reproducible.

Can you run through step-by-step the commands you ran to get to this point?

**Comment by SchrodingersGat** [comment]
Ah I see you have commented over there. Ok I'll close this one.
