### ISSUE TITLE
[BUG] Label printing with brother plugin fails

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3554]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

This started today - yesterday, I ran the plugin successfully.
Since then, I deleted my test setup and re-created it on the newest version. I'm not sure why this didn't occur then..

### Steps to Reproduce

1. Attempt to print a label using the brother plugin, by going to eg `api/label/part/3/print/?part[]=100&plugin=brother`
2. See error below

### Expected behavior

Label printed, no error ;)

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.15
Commit Hash: b9f83eefc
Commit Date: 2022-08-16
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: [{'name': 'Brother Labels', 'slug': 'brother', 'version': '0.4.0'}]

### Relevant log output

```shell
Traceback (most recent call last):

File "/home/inventree/data/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/InvenTree/label/api.py", line 499, in get
return self.print(request, parts)

File "/home/inventree/InvenTree/label/api.py", line 132, in print
pdf = output.get_document().write_pdf()

AttributeError: 'SafeString' object has no attribute 'get_document'
```

**Comment by miggland** [comment]
OK, I'm being a bit stupid (but only a bit...)

I had debug mode on. The error message didn't help me in figuring this out, but other than that it's OK.
