### ISSUE TITLE
[BUG] Not starting with Python 3.8

### ISSUE THREAD

**Issue by AntoWkill** [inventree/InvenTree#3820]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Im trying to updating my inventree, when i try to do invoke update there an errore and all update fail. Server is not starting of course.

### Steps to Reproduce

1) git pull origin master
2) Activate virtual env
3) git pull origin master

 
### Expected behavior

finish updating 

### Deployment Method

- [ ] Docker
- [x] Bare metal

### Version Information

5.0.0 to last.

### Relevant log output

Requirement already satisfied: zopfli==0.2.1 in ./inventree-env/lib/python3.8/site-packages (from -r requirements.txt (line 257)) (0.2.1)
Requirement already satisfied: setuptools in ./inventree-env/lib/python3.8/site-packages (from django-money==2.1.1->-r requirements.txt (line 99)) (44.0.0)
Installing plugin packages from '/var/www/html/inventory/inventree/InvenTree/plugins.txt'
Backing up InvenTree database...
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/html/inventory/inventree/inventree-env/lib/python3.8/site-packages/django/apps/config.py", line 212, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/inventory/inventree/InvenTree/InvenTree/apps.py", line 14, in <module>
    import InvenTree.tasks
  File "/var/www/html/inventory/inventree/InvenTree/InvenTree/tasks.py", line 154, in <module>
    class TaskRegister:
  File "/var/www/html/inventory/inventree/InvenTree/InvenTree/tasks.py", line 156, in TaskRegister
    task_list: list[ScheduledTask] = []
TypeError: 'type' object is not subscriptable

**Comment by SchrodingersGat** [comment]
@matmair with regard to the type hinting in your recent PR - is this a python 3.9 feature? @AntoWkill is using 3.8 and throwing an error here

**Comment by AntoWkill** [comment]
@SchrodingersGat so you suggest to update my python?

**Comment by SchrodingersGat** [comment]
@AntoWkill update python to 3.9 and see if the problem goes away. If so, we'll have to update the docs for our minimum required python version :)

**Comment by matmair** [comment]
@SchrodingersGat type hinting was introduced in PEP 484, which should be in python 3.5. This kind of direct reference is only in available in 3.9, I will roll back to syntax 3.8 can run. Sorry about that, I thought our CI runs 3.8 but it uses 3.9.

@AntoWkill if you want to update right now you could update your python, the release of the fix might take a bit.

**Comment by matmair** [comment]
@SchrodingersGat so no backport to support 3.8? 3.9 starts shipping in Debian 11, Ubuntu 22.04 so we would drop some older OS versions likely.

**Comment by AntoWkill** [comment]
there are easyier solution? Im trying to update python but is not working in virtual evn..

**Comment by AntoWkill** [comment]
> If you think we can easily drop back to 3.8 (and downgrade our CI accordingly) then I'd rather do that :)

Please let me know when or how will work with 3.8

**Comment by matmair** [comment]
@SchrodingersGat I just looked into the requirements and 3.9 is our documented minium version. Should we move it back down or ask @AntoWkill to update to a newer version?

**Comment by SchrodingersGat** [comment]
If we already have specified 3.9 then let us keep that. @AntoWkill you'll need to setup a new virtual environment

**Comment by AntoWkill** [comment]
Im trying do to a fresh installation. All works fine the process but i can't see my installation on the port 80 or 6000 as default. Also chaning i alwaise see "bad gateway" by the "quick script installation"
Any suggestion?

**Comment by matmair** [comment]
> 
> Also here is Python 3.8 declared https://inventree.readthedocs.io/en/stable/start/install/

This seems to be an error, the whole CI and the [shipped docs](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#target-version) point to 3.9; I will create a PR to fix this

**Comment by matmair** [comment]
> Im trying do to a fresh installation. Any suggestion?

@AntoWkill Have you removed the old version of InvenTree, the old user and the old home directory? They might interfere with the installer.


> All works fine the process but i can't see my installation on the port 80 or 6000

Not sure what you mean here. Do you see the webserver process running? The web process needs to run and the set port must be free ( you can check that with ´inventree config`).



> Also chaning i alwaise see "bad gateway" by the "quick script installation"

Again not entirely sure what you mean. If you change the port inventree runs at you also need to change the nginx config to proxy the same port.
