### ISSUE TITLE
Can't add links as attachments [BUG]

### ISSUE THREAD

**Issue by papgrap** [inventree/InvenTree#3844]
## Bug description
When trying to add a link as an attachment in inventree I get the following error:

```
Traceback (most recent call last):

File "/opt/inventree/InvenTree_prod/inv_venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/opt/inventree/InvenTree_prod/inv_venv/lib/python3.10/site-packages/rest_framework/generics.py", line 242, in post
return self.create(request, *args, **kwargs)

File "/opt/inventree/InvenTree_prod/InvenTree/InvenTree/mixins.py", line 18, in create
self.perform_create(serializer)

File "/opt/inventree/InvenTree_prod/InvenTree/InvenTree/api.py", line 199, in perform_create
attachment = serializer.save()

File "/opt/inventree/InvenTree_prod/InvenTree/InvenTree/serializers.py", line 149, in save
super().save(**kwargs)

File "/opt/inventree/InvenTree_prod/inv_venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
self.instance = self.create(validated_data)

File "/opt/inventree/InvenTree_prod/inv_venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 962, in create
instance = ModelClass._default_manager.create(**validated_data)

File "/opt/inventree/InvenTree_prod/inv_venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/opt/inventree/InvenTree_prod/inv_venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
obj.save(force_insert=True, using=self.db)

File "/opt/inventree/InvenTree_prod/InvenTree/InvenTree/models.py", line 388, in save
if self.attachment.name.lower().endswith('.svg'):

AttributeError: 'NoneType' object has no attribute 'lower'
```

It doesn't matter if I add the link (attachment) to a part, purchase order or build order.
Actual files as attachments do work.

## Steps to reproduce
1. Open a purchase order.
2. In the menu on the left side click on attachments.
3. Click the button "Add Link".
4. A red error message should appear on the top.
5. The link has not been added as an attachment.

## Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b149c
Commit Date: 2022-09-23
Database: mysql
Debug-Mode: False
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
@papgrap thanks for reporting, this has already been fixed in https://github.com/inventree/InvenTree/pull/3818
