### ISSUE TITLE
Parameters in label tempates don't support spaces

### ISSUE THREAD

**Issue by Gherkin** [inventree/InvenTree#3891]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

It seems like part parameters are only usable in label templates if they don't contain spaces due to the fact that you address elements in the dict by dot-notation, i.e `parameters.length`. This seems to be a well known bug in Django with a (seemingly) [easy fix.](https://stackoverflow.com/questions/1906129/dict-keys-with-spaces-in-django-templates)  

I have my part parameters auto-created by ki-ntree, so using parameters without spaces would be hard.

### Steps to Reproduce

create a part parameter with a space, create a label template that tries to read it

```
{% block content %}


<div class='part'>
    {{ parameters.'Package Type' }}
</div>

{% endblock %}
```
fails with
```
Could not parse the remainder: ''Package Type'' from 'parameters.'Package Type''
```

```
{% block content %}


<div class='part'>
    {{ parameters["Package Type"] }}
</div>

{% endblock %}
```
fails with 
```
Could not parse the remainder: '["Package Type"]' from 'parameters["Package Type"]'
```

### Expected behavior

Label templates should have the same criteria for part parameters names that already exists.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.4
Django Version: 3.2.15
Commit Hash: ca1fbf9
Commit Date: 2022-10-20
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

### Relevant log output

```shell
Traceback (most recent call last):

File "/root/.local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/InvenTree/label/api.py", line 499, in get
return self.print(request, parts)

File "/home/inventree/InvenTree/label/api.py", line 132, in print
pdf = output.get_document().write_pdf()

File "/root/.local/lib/python3.9/site-packages/django_weasyprint/views.py", line 76, in get_document
string=super().rendered_content,

File "/root/.local/lib/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
template = self.resolve_template(self.template_name)

File "/root/.local/lib/python3.9/site-packages/django/template/response.py", line 63, in resolve_template
return select_template(template, using=self.using)

File "/root/.local/lib/python3.9/site-packages/django/template/loader.py", line 42, in select_template
return engine.get_template(template_name)

File "/root/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
return Template(self.engine.get_template(template_name), self)

File "/root/.local/lib/python3.9/site-packages/django/template/engine.py", line 143, in get_template
template, origin = self.find_template(template_name)

File "/root/.local/lib/python3.9/site-packages/django/template/engine.py", line 125, in find_template
template = loader.get_template(name, skip=skip)

File "/root/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 58, in get_template
template = super().get_template(template_name, skip)

File "/root/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 29, in get_template
return Template(

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 155, in __init__
self.nodelist = self.compile_nodelist()

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 193, in compile_nodelist
return parser.parse()

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/root/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 278, in do_extends
nodelist = parser.parse()

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/root/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 216, in do_block
nodelist = parser.parse(('endblock',))

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 449, in parse
raise self.error(token, e)

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 447, in parse
filter_expression = self.compile_filter(token.contents)

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 563, in compile_filter
return FilterExpression(token, self)

File "/root/.local/lib/python3.9/site-packages/django/template/base.py", line 662, in __init__
raise TemplateSyntaxError("Could not parse the remainder: '%s' "

django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''Package Type'' from 'parameters.'Package Type''
```

**Comment by SchrodingersGat** [comment]
@Gherkin an interesting problem! I think a template tag which allows string-based lookup (as per the stackoverflow post you linked) would be a good solution. We will need to document it, so that other users can find the answer too!

**Comment by matmair** [comment]
@Gherkin do you want to develop this?
