### ISSUE TITLE
Message: OperationalError(1226, "User has exceeded the 'max_connections_per_hour' resource (current value: 500)")

### ISSUE THREAD

**Issue by quezon** [inventree/InvenTree#4183]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hi Team,
I ran **"docker compose up -d"** after database seeding. My MySQL database resides in **Hostinger** which prevents maximum connections exceeding **500 per hour**. Is there a way to specify in .env or other configuration files to limit the number of maximum connections made by inventree-server? No issues with database seeding only with inventree-server exceeding 500 connections per hour.
Thanks!
Gabriel

### Steps to Reproduce

0. docker volume rm -f inventree-production_inventree_data
1. cd /home/ubuntu && mkdir inventree-data
2. cd <dir to production docker>
3. nano .env 
added external mysql host, db name, user, password and port
4. nano docker-compose.override.yml
added override for inventree-db and inventree-proxy
5. docker-compose up -d
6. docker logs inventree-server
// showed the issue above on the logs

### Relevant log output

```bash
Message: OperationalError(1226, "User has exceeded the 'max_connections_per_hour' resource (current value: 500)")
Arguments: ('Traceback (most recent call last):\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection\n    self.connect()\n  File "/root/.local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner\n    return func(*args, **kwargs)\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File "/root/.local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner\n    return func(*args, **kwargs)\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection\n    connection = Database.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect\n    return Connection(*args, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__\n    super().__init__(*args, **kwargs2)\nMySQLdb.OperationalError: (1226, "User \'u581858203_supply_bukirin\' has exceeded the \'max_connections_per_hour\' resource (current value: 500)")\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/root/.local/lib/python3.9/site-packages/django_q/cluster.py", line 345, in pusher\n    task_set = broker.dequeue()\n  File "/root/.local/lib/python3.9/site-packages/django_q/brokers/orm.py", line 64, in dequeue\n    tasks = self.get_connection().filter(key=self.list_key, lock__lt=_timeout())[\n  File "/root/.local/lib/python3.9/site-packages/django_q/brokers/orm.py", line 20, in get_connection\n    if transaction.get_autocommit(\n  File "/root/.local/lib/python3.9/site-packages/django/db/transaction.py", line 25, in get_autocommit\n    return get_connection(using).get_autocommit()\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 389, in get_autocommit\n    self.ensure_connection()\n  File "/root/.local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner\n    return func(*args, **kwargs)\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection\n    self.connect()\n  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection\n    self.connect()\n  File "/root/.local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner\n    return func(*args, **kwargs)\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File "/root/.local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner\n    return func(*args, **kwargs)\n  File "/root/.local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection\n    connection = Database.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect\n    return Connection(*args, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__\n    super().__init__(*args, **kwargs2)\ndjango.db.utils.OperationalError: (1226, "User has exceeded the \'max_connections_per_hour\' resource (current value: 500)")\n',)
```

**Comment by SchrodingersGat** [comment]
> Is there a way to specify in .env or other configuration files to limit the number of maximum connections made by inventree-server?

No, the number of required DB connections depends on how heavily the system is being used. 

This problem seems outside of scope for us.

**Comment by matmair** [comment]
@SchrodingersGat I will close this as it is out of scope.
