### ISSUE TITLE
Error no module named dbbackup after update

### ISSUE THREAD

**Issue by Fluxus00** [inventree/InvenTree#4198]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

Hello there,

i just updated InvenTree to the newest Version a few days ago. This included the function of doing a backup. Since then I am not able to start InvenTree, or to be more precisely, the workers failed to boot.
As far as I can see, the system is not able to use the Django package dbbackup. My Django version is up to date (3.2.16). So my guess is, that I might have missed a configuration step, which is relevant after the update. Furthermore I checked the files requirements.txt and config.yaml but thex looked good.
I will keep looking, but would be glad if someone would lend me a hand.

Thanks in advance.

### Steps to Reproduce

1. Stopped all Gunicorn instances
2. Used git pull origin master to update the source code
3. Added a backup directory
4. Use invoke update
5. Tried to start Gunicorn again
6. Failed to start with shown Error below

Sorry it really was not more than this.  

### Expected behavior

InvenTree worker and Gunicorn webserver should start. 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.9.2

### Relevant log output

```shell
Traceback (most recent call last):
File "/usr/local/bin/gunicorn", line 8, in
sys.exit(run())
File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 231, in run
super().run()
File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 72, in run
Arbiter(self).run()
File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 58, in init
self.setup(app)
File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 118, in setup
self.app.wsgi()
File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
mod = importlib.import_module(module)
File "/usr/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 992, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/home/bstadmin/inventree/src/InvenTree/InvenTree/wsgi.py", line 15, in
application = get_wsgi_application() # pragma: no cover
File "/usr/local/lib/python3.10/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
django.setup(set_prefix=False)
File "/usr/local/lib/python3.10/dist-packages/django/init.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 91, in populate
app_config = AppConfig.create(entry)
File "/usr/local/lib/python3.10/dist-packages/django/apps/config.py", line 224, in create
import_module(entry)
File "/usr/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dbbackup'
```

**Comment by matmair** [comment]
@Fluxus00
1. Are you using a custom settings.py?
2. Are you sure you activated the right environment before running InvenTree? This is a very common problem when upgrading

**Comment by Fluxus00** [comment]
@matmair 
Thank you for your reply!
1. No I do not not. I just wanted to check if the file is corrupted or anything else is missing.
2. Yes I am, actually I did in the virtual environment  and outside of it to make sure.

Can I provide something that would help you?

**Comment by matmair** [comment]
@Fluxus00 can you checked if dbbackup is in your requirements.txt?
Debugging bare metal installs often presents a challenge - this is in part why we created packaged installs.

**Comment by Fluxus00** [comment]
@matmair 
So it is in my requirements.txt mentioned, and also a installation via Docker is in my case almost impossible so it wasn't really a option.
But it seems like several System restarts have fixed the problem. Because I still do not understand why this problem occurred and why it is fixed now, I would like to keep this issue open for 1 or 2 days in case it  happens again. If not I will close it manually.
I wish I could buy you a coffee or something as an excuse for such a stupid question by me.

**Comment by matmair** [comment]
@Fluxus00 first of all there are no stupid questions. It would not be the first time that we have flaky bugs.

Regarding the install method I was not talking about docker. With 0.9.0 we started shipping Debian (and Ubuntu) packages.
You actually can buy us a coffee via sponsoring.

**Comment by matmair** [comment]
@Fluxus00 that is in the pipeline for the next release and already merged in master

**Comment by Fluxus00** [comment]
@matmair So if I understand this correct I just have to wait for the next release and update my software when the time comes right?

**Comment by matmair** [comment]
You can turn off backups in the next release
