### ISSUE TITLE
Error while dublicating part with category parameter templates and part templates

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#4353]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I get a server error when I try to duplicate a part in case the category has parameter templates and the part has pemplates and both switches are on. 

### Steps to Reproduce

Add part category parameter template to a category (e.g. CAP) in the admin interface (e.g. Capacitance)
Select a part in the normal site from that category that already has the parameter Capacitance
Select part duplicate
Fill name IPN and description with proper values
Leave all switches in their default position specially: Copy Category Parameters ON and Copy Parameters ON
Duplicate fill fail with message 
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

### Expected behaviour

Duplicate should work.
Somehow it is logical that this cannot work. We need to set a priority here. I would expect that the Copy Category Parameters is ignored in that case, or warning please switch OFF. 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

Development server 
DEBUG on

InvenTree Version 	[0.11.0 dev]
Commit Hash	216fb8d15
Commit Date	2023-02-16

### Relevant log output

```shell
Traceback (most recent call last):

File "/home/konrad/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/konrad/.local/lib/python3.10/site-packages/rest_framework/generics.py", line 242, in post
return self.create(request, *args, **kwargs)

File "/usr/lib/python3.10/contextlib.py", line 79, in inner
return func(*args, **kwds)

File "/home/konrad/src/InvenTree/part/api.py", line 1231, in create
part.save(**{'add_category_templates': copy_templates})

File "/home/konrad/src/InvenTree/part/models.py", line 483, in save
for template in category.get_parameter_templates():

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
self._fetch_all()

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
self._result_cache = list(self._iterable_class(self))

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
cursor.execute(sql, params)

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
return super().execute(sql, params)

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 78, in _execute
self.db.validate_no_broken_transaction()

File "/home/konrad/.local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 447, in validate_no_broken_transaction
raise TransactionManagementError(

django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by SchrodingersGat** [comment]
@SergeoLacruz thanks for reporting - I can replicate this one locally. Will have to look into it.
