### ISSUE TITLE
Unknown column 'stock_stocklocation.external' in 'field list

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#4418]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After the latest update when I add stock to a part I get a error 

Type: OperationalError
Path: /api/stock/location/tree/
Info: (1054, "Unknown column 'stock_stocklocation.external' in 'field list'")

This was working previosly so must be some new issue after updating in the last 48 hours

### Steps to Reproduce

1. Create new part
2. Add stock to part: Qty 1, Price blank

### Expected behaviour

Not sure what this effect but stock is updated.  Error is raised in notifications

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.16
Commit Hash: 5037e427b
Commit Date: 25/02/2023
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

### Relevant log output

```shell
Traceback (most recent call last):

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
db.query(q)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
_mysql.connection.query(self, query)

MySQLdb.OperationalError: (1054, "Unknown column 'stock_stocklocation.external' in 'field list'")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
return self.list(request, *args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
return Response(serializer.data)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
ret = super().data

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
self._data = self.to_representation(self.instance)

File "/home/inventree/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
return [

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
self._fetch_all()

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
self._result_cache = list(self._iterable_class(self))

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
cursor.execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
return super().execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
with self.db.wrap_database_errors:

File "/home/inventree/env/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)

File "/home/inventree/env/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
return self.cursor.execute(query, args)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
res = self._query(query)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
db.query(q)

File "/home/inventree/env/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
_mysql.connection.query(self, query)

django.db.utils.OperationalError: (1054, "Unknown column 'stock_stocklocation.external' in 'field list'")
```

**Comment by SchrodingersGat** [comment]
Did you run `invoke update` as part of your update process? Looks like this has been missed

**Comment by StormTrooper** [comment]
Ah yes, thanks. Sorry about that. Closing issue.

Ran update - all good now.
