### ISSUE TITLE
sqlite3 database schema not initialized during first run

### ISSUE THREAD

**Issue by ResRipper** [inventree/InvenTree#4426]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

InvenTree seems not able to initialize the database while using docker-compose with sqlite3 as database.

Tested on environments below, both produce the same error:
- MacOS 13.2 (M1 chip) + docker 20.10.22 + docker-compose 2.15.1
- Ubuntu 22.04.2 (x86_64) + docker 20.10.12 + docker-compose 1.29.2

docker-compose file (Only mount point are changed between each machine):
```yml
services:

    inventree-server:
        container_name: inventree-server
        image: inventree/inventree:0.10.1
        env_file:
            - stack.env
        networks:
            - dev
        volumes:
            - inventree-app:/home/inventree/data
        
    inventree-worker:
        container_name: inventree-worker
        image: inventree/inventree:0.10.1
        command: invoke worker
        depends_on:
            - inventree-server
        env_file:
            - stack.env
        networks:
            - dev
        volumes:
            - inventree-app:/home/inventree/data

networks:
    dev:
        name: dev
        external: true

volumes:
    inventree-app:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/docker/dev/inventree
```

`stack.env` file:
```
INVENTREE_WEB_PORT=1337
INVENTREE_DEBUG=True
INVENTREE_LOG_LEVEL=DEBUG
INVENTREE_DB_ENGINE=sqlite3
INVENTREE_DB_NAME=/home/inventree/data/db.sqlite3
INVENTREE_GUNICORN_TIMEOUT=30
INVENTREE_PLUGINS_ENABLED=False
```

Same error log were produced on both machine:

inventree-server
```
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: part_partpricing
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inventree/InvenTree/InvenTree/wsgi.py", line 15, in <module>
    application = get_wsgi_application()  # pragma: no cover
  File "/root/.local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/part/apps.py", line 21, in ready
    self.reset_part_pricing_flags()
  File "/home/inventree/InvenTree/part/apps.py", line 55, in reset_part_pricing_flags
    if items.count() > 0:
  File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 528, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: part_partpricing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

inventree-worker
```
Loading config file : /home/inventree/data/config.yaml
File “/home/inventree/InvenTree/locale/el/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/sv/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/sl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/tr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ru/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/vi/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/es_MX/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/no/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/th/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/da/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/fr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/zh/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/hu/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/nl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/en/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/he/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/id/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ko/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/fa/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/ja/LC_MESSAGES/django.po” is already compiled and up to date.
File “/home/inventree/InvenTree/locale/pt_br/LC_MESSAGES/django.po” is already compiled and up to date.
InvenTree translation coverage: 23%
Waiting for database...
Database connection sucessful!
/home/inventree/InvenTree/label/apps.py:44: UserWarning: Database was not ready for creating labels
  warnings.warn('Database was not ready for creating labels')
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: part_partpricing
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/root/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/part/apps.py", line 21, in ready
    self.reset_part_pricing_flags()
  File "/home/inventree/InvenTree/part/apps.py", line 55, in reset_part_pricing_flags
    if items.count() > 0:
  File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 528, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: part_partpricing
```

sqlite database did created under the data folder, but the size was 0B:
```
total 28
drwxr-xr-x 2 root root 4096 Feb 28 08:21 backup
-rw-r--r-- 1 root root 7562 Feb 28 08:21 config.yaml
-rw-r--r-- 1 root root    0 Feb 28 08:21 db.sqlite3
drwxr-xr-x 3 root root 4096 Feb 28 08:21 media
-rw-r--r-- 1 root root   53 Feb 28 08:21 plugins.txt
-rw-r--r-- 1 root root  100 Feb 28 08:21 secret_key.txt
drwxr-xr-x 2 root root 4096 Feb 28 08:21 static
```

After mounting the data folder into a new InvenTree container with the same env file, then run `python manage.py migrate`, the database schema will be create and I can bring up the stack with no error.

### Steps to Reproduce

1. Put `docker-compose.yml` and `stack.env` under same folder
2. Run `docker-compose up`

### Expected behaviour

InvenTree can run without issue

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

InvenTree version: 0.10.1

Hosts:
- MacOS 13.2 (M1 chip) + docker 20.10.22 + docker-compose 2.15.1
- Ubuntu 22.04.2 (x86_64) + docker 20.10.12 + docker-compose 1.29.2

**Comment by SchrodingersGat** [comment]
You need to run `invoke update` first:

https://docs.inventree.org/en/latest/faq/#errors-during-inventree-update

https://docs.inventree.org/en/latest/start/docker_dev/#perform-initial-setup

**Comment by ResRipper** [comment]
> You need to run `invoke update` first:
> 
> https://docs.inventree.org/en/latest/faq/#errors-during-inventree-update
> 
> https://docs.inventree.org/en/latest/start/docker_dev/#perform-initial-setup

It works, thanks a lot for your help!
