### ISSUE TITLE
ValidationError at /settings/

### ISSUE THREAD

**Issue by DS1705** [inventree/InvenTree#4546]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

if i activate the plugin CupsLabel in the admin page, my setting page doesn't work anymore

### Steps to Reproduce

1. add this line to plugins.txt git+https://github.com/wolflu05/inventree-cups-plugin
2. in the plugin settings i have check that plugins are installed on startup enabled 
3. if i activate the plugin CupsLabel from the admin page
4. i go to the settings page then i get the ValidationError at /settings/

### Expected behaviour

the settings page must show normally and not an error page

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 3d4b64d03
Commit Date: 2023-03-29
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Label Printer', 'slug': 'samplelabel', 'version': '0.2'}, {'name': 'CupsLabels', 'slug': 'cups', 'version': '0.1.0'}]

### Relevant log output

```shell
Environment:


Request Method: GET
Request URL: http://172.27.6.4:8000/settings/

Django Version: 3.2.18
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'plugin.apps.PluginAppConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'user_sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'maintenance_mode',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownify',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools',
 'dbbackup',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'allauth_2fa',
 'django_ical',
 'sslserver']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'x_forwarded_for.middleware.XForwardedForMiddleware',
 'user_sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'InvenTree.middleware.InvenTreeRemoteUserMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'InvenTree.middleware.CustomAllauthTwoFactorMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'InvenTree.middleware.Check2FAMiddleware',
 'maintenance_mode.middleware.MaintenanceModeMiddleware',
 'InvenTree.middleware.InvenTreeExceptionProcessor']


Template error:
In template /home/dieter/src/InvenTree/templates/InvenTree/settings/setting.html, error at line 5
   Chosen value is not a valid option
   1 : {% load inventree_extras %}
   2 : {% load i18n %}
   3 : 
   4 : {% if plugin %}
   5 :  {% setting_object key cache=False plugin=plugin as setting %} 
   6 : {% elif user_setting %}
   7 : {% setting_object key cache=False user=request.user as setting %}
   8 : {% elif notification_setting %}
   9 : {% setting_object key cache=False method=method user=request.user as setting %}
   10 : {% else %}
   11 : {% setting_object key cache=False as setting %}
   12 : {% endif %}
   13 : 
   14 : <tr>
   15 :     <td>


Traceback (most recent call last):
  File "/home/dieter/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/dieter/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/dieter/env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/dieter/src/InvenTree/part/templatetags/inventree_extras.py", line 329, in setting_object
    return PluginSetting.get_setting_object(key, plugin=plugin, cache=cache)
  File "/home/dieter/src/InvenTree/common/models.py", line 411, in get_setting_object
    setting.save(**kwargs)
  File "/home/dieter/src/InvenTree/common/models.py", line 103, in save
    self.clean(**kwargs)
  File "/home/dieter/src/InvenTree/common/models.py", line 543, in clean
    raise ValidationError(_("Chosen value is not a valid option"))

Exception Type: ValidationError at /settings/
Exception Value: ['Chosen value is not a valid option']
```

**Comment by SchrodingersGat** [comment]
@wolflu05 it is *possible* this is related to the plugin itself, rather than InvenTree, but I'm not sure. I'll try to dig in but I don't have a setup at the moment where I can test this plugin specifically.

**Comment by wolflu05** [comment]
Yeah, sorry I missed that one. I guess this is related to printer selection @SchrodingersGat, I utilized the [get_choices](https://github.com/wolflu05/inventree-cups-plugin/blob/main/inventree_cups/cups_plugin.py#L58) method to scan for printers. Through in retrospect this implementation is not ideal. I think I need some mechanism to handle that case, that an already selected printer which is not available anymore can't cause a template error. 

Is there actually a method to update a setting manually via a plugin, so I can implement my own select in the settings via a custom html template?

**Comment by wolflu05** [comment]
@DS1705 please open this as an issue on my [plugin's repo](https://github.com/wolflu05/inventree-cups-plugin/issues/new) and referee to this one?
