### ISSUE TITLE
Migration error during update

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#4582]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I was updating from v0.7.0-371-gb13e0c313 to v0.7.0-685-g508dd5425. My installation is bare metal on linux.
During the database migration this error poped up:
```
Applying part.0101_bomitem_validated... OK
  Applying part.0102_auto_20230314_0112...Traceback (most recent call last):
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: part_bomitem.metadata

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/inventree/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/data/inventree/inventree/InvenTree/part/migrations/0102_auto_20230314_0112.py", line 18, in update_bom_item
    for item in BomItem.objects.all():
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/inventree/inventree-env/lib64/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: part_bomitem.metadata
```
I have no idea how the django migrations are supposed to work but I did find the mentioned InvenTree/part/migrations/0102_auto_20230314_0112.py and I noticed that the "next" file 0103_auto_20230317_0816.py is adding the mentioned field. 
So I renamed these two files (swapped 0102 a 0103) and fixed the dependencies inside the files and the migration did succeed.

### Steps to Reproduce

I am not sure how to reproduce the issue as it may be related to my local installation.

### Expected behaviour

Update task to update the system :-)

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 508dd5425
Commit Date: 2023-04-05
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Active plugins: False

**Comment by SchrodingersGat** [comment]
@Kedarius thanks for reporting, I can see how this has happened, I'll see what I can do.

**Comment by elmo2k3** [comment]
Seems I ran into the same issue. Just tried to upgrade my docker installation that is currently on commit e730b5c. Neither upgrading to latest, stable or even 0.10.0 worked. Always getting the migration error ```no such column: part_bomitem.metadata```

**Comment by SchrodingersGat** [comment]
@elmo2k3 thanks, there is a definite bug I need to fix here, which I'll get to with priority this week.
