### ISSUE TITLE
pg_dump error: connection to database "inventree" failed

### ISSUE THREAD

**Issue by AlexPerni** [inventree/InvenTree#4809]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I'm following the guide to install InvenTree production through docker ([Link](https://docs.inventree.org/en/stable/start/docker_prod/))
After only configuring the .env file and running "docker compose run inventree-server invoke update", I get an error from the setup server, that it can not connect to the inventree-db container. 
On Portainer I can see the inventree-db container running without problems, but the inventree-server one shuts  down due to this error. 
I've tried to "docker volume rm -f inventree-production_inventree_data" but the error persists. 

I've noticed that the inventree-db container has log entries, that ownership of a path could not be changed. Not sure, if that is part of the problem. I'll attach the relevant logs at the end of the log output, separated from the terminal output. 

### Steps to Reproduce

1. download production directory from the repo with .env, docker-compose.yml and nginx.prod.conf files
2. configure only the .env file
3. switch to su
4. run command "docker compose run inventree-server invoke update"

### Relevant log output

```bash
Backing up InvenTree database...
Backing Up Database: inventree
CommandConnectorError: Error running:  pg_dump --dbname=postgresql://myuser:mypw@inventree-db:5432/inventree --format=custom
pg_dump: error: connection to database "inventree" failed: could not translate host name "inventree-db" to address: Name or service not known

  File "/root/.local/lib/python3.9/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
...

Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  ...
  File "/root/.local/lib/python3.9/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump --dbname=postgresql://myuser:mypw@inventree-db:5432/inventree --format=custom
pg_dump: error: connection to database "inventree" failed: could not translate host name "inventree-db" to address: Name or service not known


-------- inventree-db container log ------------------------------------------------------------------
Data page checksums are disabled.
initdb: error: could not change permissions of directory "/var/lib/postgresql/data/pgdb": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data/pgdb ... w2023-05-14T09:38:30.029166260Z chmod: changing permissions of '/var/lib/postgresql/data/pgdb': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
 
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
```

**Comment by AlexPerni** [comment]
Here is my .env file, in case you want to check if I did something stupid in the config. 
Only changed the user names and passwords.

[env.txt](https://github.com/inventree/InvenTree/files/11471588/env.txt)

**Comment by matmair** [comment]
This sounds like your Postgres does not have full write permissions on the data directory.

**Comment by AlexPerni** [comment]
Indeed it was (again) a problem of permission. 
[This article](https://medium.com/@panda1100/solutions-for-operation-not-permitted-error-when-postgresql-is-running-on-docker-using-vagrants-3db360ca2c03) helped me to understand the problem, as I was mounting to my network storage. 
In the end, the easiest solution is to change the external volume mounting point to some directory, that has the correct permissions to write. And in case you are clueless as me in the beginning, you can just use chmod a+rw, in case it helps anyone in the future.
