### ISSUE TITLE
printing part parameters on order report

### ISSUE THREAD

**Issue by mabroens** [inventree/InvenTree#4925]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Is it possible to loop over part parameters and print them on th report, i have following parameters that i would like to print 

![image](https://github.com/inventree/InvenTree/assets/130482028/ff8bc757-3e79-4862-bf52-8e3c46ad2f97)

so i was thinking of checking i the param ECCN exists and if so print it
```
{% for line in lines.all %}
  {% if line.part.part.parameters["ECCN"] %} 
     ECCN: {{ line.part.part.parameters["ECCN"] }}
  {% endif %}
  {% if line.part.part.parameters["HTS"] %} 
     HTS : {{ line.part.part.parameters["HTS"] }}
  {% endif %}
```

but i get:
![image](https://github.com/inventree/InvenTree/assets/130482028/3c15cd30-afcf-490c-a195-67c75a9e4df2)

any suggestions

Br Martijn

### Suggested solution

?

### Describe alternatives you've considered

 none

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by SchrodingersGat** [comment]
The templating language doesn't let you do dict lookup that way. There are two options here:

### Use dot notation

```
{% if line.part.part.parameters.ECCN %}
```

### Use helper function

```
{% with getkey part.part.parameters "ECCN" as value %}
{% if value %}
...
{% endif %}
{% endwith %}
```

https://docs.inventree.org/en/latest/report/helpers/#key-access

**Comment by SchrodingersGat** [comment]
@mabroens can you try:

```
{% with getkey my_container key as value %}
{{ value }}
{% endwith %}
```

**Comment by mabroens** [comment]
sorry does not work for me:
this is my report:
```
{% for line in lines.all %}
  <tr>
    <td>
      <div class='thumb-container'>
      <img src='{% part_image line.part.part %}' class='part-thumb'>
      </div>
    </td>
  <td>
    <div class='part-text'>
    {% if line.part.part.revision %} 
    <strong>{{ line.part.part.IPN }} {{line.part.part.revision}}-Sample</strong>
    {% else %} 
       <strong>{{ line.part.part.name }}</strong>
    {% endif %}
    <br><br>
    {{ line.part.part.description }}
    
    <br><br>
      <ul>
      # for key,val in dict: print(key,val)
      {% for key in keys %}
         <li>Key: {% getkey part.part key %}</li>
      {% endfor %}
      
      # Test2 using getkey
      {% with getkey line.part.part.name key as value %}
         {{ value }}
      {% endwith %}
      
      </ul>
    </div>
  </td>
  </tr>
{% endfor %}
```

This results in following error:
![image](https://github.com/inventree/InvenTree/assets/130482028/e77832bd-65a3-492a-89e3-dc077e770a4c)

Traceback:

Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/opt/inventree/InvenTree/report/api.py", line 263, in get
return self.print(request, items)

File "/opt/inventree/InvenTree/report/api.py", line 228, in print
doc = output.get_document()

File "/opt/inventree/env/lib/python3.8/site-packages/django_weasyprint/views.py", line 76, in get_document
string=super().rendered_content,

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
template = self.resolve_template(self.template_name)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
return select_template(template, using=self.using)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
return engine.get_template(template_name)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
return Template(self.engine.get_template(template_name), self)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
template, origin = self.find_template(template_name)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
template = loader.get_template(name, skip=skip)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loaders/cached.py", line 58, in get_template
template = super().get_template(template_name, skip)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
return Template(

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
self.nodelist = self.compile_nodelist()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
return parser.parse()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
nodelist = parser.parse()

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
nodelist = parser.parse(('endblock',))

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 817, in do_for
nodelist_loop = parser.parse(('empty', 'endfor',))

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
raise self.error(token, e)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
compiled_result = compile_func(self, token)

File "/opt/inventree/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 1483, in do_with
raise TemplateSyntaxError("%r expected at least one variable "

django.template.exceptions.TemplateSyntaxError: 'with' expected at least one variable assignment

**Comment by SchrodingersGat** [comment]
Your `#test2` block is outside the `{% for %}` loop so "value" is not accessible.

Try

```html
      {% for key in keys %}
         <li>Key: {{ key }}</li>
         <li>Test1: {% getkey part.part key %}</li>
      {% with getkey line.part.part.name key as value %}
         <li>Test2: {{ value }}</li>
      {% endwith %}
      {% endfor %}

```

**Comment by mabroens** [comment]
good point. I had not tought that one should also be in the loop.
triet it with this:
```
      <tr>
         <td colspan='2'><strong>Part</strong></td> 
         <td style="width: 30px;"><strong>Qty</strong></td>
         <td style="width: 70px;"><strong>Unit Price</strong></td>
         <td style="width: 70px;"><strong>Total Price</strong></td>
      </tr>

      {% for line in lines.all %}
      <tr>
         <td>
            <div class='thumb-container'>
               <img src='{% part_image line.part.part %}' class='part-thumb'>
            </div>
         </td>
         <td>
            <div class='part-text'>
               {% if line.part.part.revision %} 
                 <strong>{{ line.part.part.IPN }} {{line.part.part.revision}}-Sample</strong>
               {% else %} 
                 <strong>{{ line.part.part.name }}</strong>
               {% endif %}
               <br><br>
               {{ line.part.part.description }}

               <br><br>
               <ul>
                  # for key,val in dict: print(key,val)
                  

                  {% for key in keys %}
                     <li>Key: {{ key }}</li>
                     <li>Test1: {% getkey part.part key %}</li>
                     {% with getkey line.part.part.name key as value %}
                        <li>Test2: {{ value }}</li>
                     {% endwith %}
                  {% endfor %}
               </ul>
            </div>
         </td>
      </tr>
      {% endfor %}
```

but unfortunately its still not printing the keys
![image](https://github.com/inventree/InvenTree/assets/130482028/3ea252fc-5888-4c4e-9a83-319af2ad58a3)

while the params are ther:
![image](https://github.com/inventree/InvenTree/assets/130482028/f5945b0b-a071-4bc0-ac48-4cbe1252c163)

**Comment by SchrodingersGat** [comment]
The following approach works for me (note the differences)

```html
{% extends "report/inventree_test_report_base.html" %}

{% load report %}

{% block page_content %}

Part: {{ part.name }} - {{ part.description }}

<br>
<h4>Parameters:</h4>

<ul>
{% for key in parameters %}
{% getkey parameters key as value %}
<li>{{ key }} = {{ value }}</li>
{% endfor %}
</ul>


{% endblock page_content %}
```

**Comment by SchrodingersGat** [comment]
@mabroens check out the latest docs here, I've added some new features to make parameter printing easier:

- https://docs.inventree.org/en/latest/report/helpers/#part-parameters
- https://docs.inventree.org/en/latest/report/labels/part_labels/#parameter-data
