### ISSUE TITLE
AppMixin documentation needs some touch up

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#5046]
### Body of the issue

I would like to add a model to my plugin but in doing so, Inventree complains.

I tried using the normal app structure but without any success. Is there any way to add some more elaborated sample than the [sample.py](https://github.com/inventree/InvenTree/blob/2322a9806883a310826e1d43dc1c451a31dcf53d/InvenTree/plugin/samples/integration/sample.py) or extend the [docs](https://docs.inventree.org/en/latest/extend/plugins/app/)?

```
class TestPlugin(InvenTreePlugin, AppMixin):
    AUTHOR = "Author"

    DESCRIPTION = "Test app"

    VERSION = PLUGIN_VERSION

    NAME = "Test Plugin"class TestPlugin(InvenTreePlugin, AppMixin):
    AUTHOR = "Author"

    DESCRIPTION = "Test app"

    VERSION = PLUGIN_VERSION

    NAME = "Test Plugin"
    SLUG = "testapp"
    TITLE = "Test Plugin"
    PUBLISH_DATE = datetime.date(2023, 6, 9)
    WEBSITE = "https://www.test.com"

    MIN_VERSION = '0.11.0'
```

Model:
```
 class EnabledCategory(models.Model):
        category = models.ForeignKey(PartCategory, related_name='get_all', on_delete=models.CASCADE)
```

Error Message:
Model class testapp.testapp.EnabledCategory doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by matmair** [comment]
This is a very advanced topic with good opportunities to wreck a (or if it is released many) InvenTree instances so I am more than hesitant to encourage general usage of this mixin. The samples are for CI testing, not instruction.

For real-world use, you can look at [this plugin](https://github.com/matmair/inventree-shopify).

**Comment by afkiwers** [comment]
Thanks @matmair

**Comment by afkiwers** [comment]
@matmair I just checked you code and can't tell the difference to my testapp structure

I still get that error: Model class testapp.testapp.EnabledCategory doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

Any idea why that is?

**Comment by wolflu05** [comment]
Had the same issue, still asking me why it works for @matmair , but to fix this issue you need these lines: https://github.com/wolflu05/inventree-bulk-plugin/blob/main/inventree_bulk/models.py#L24-L25

**Comment by matmair** [comment]
@afkiwers @wolflu05 most likely a namespace issue. AppMixins get loaded into Django's app and model registry by the package name (or subdirectory name when using the folder based loading mechanism). If you use subpages after that the applabel will not match and raise that issue.
The proposed fix also works.

**Comment by afkiwers** [comment]
@wolflu05 thanks a lot for you example.

@wolflu05 @matmair I am still trying to understand the mechanism.

Do I need to define an admin.py file to display the model? does inventree does the starts the makemigration step or do I have to do that manually upfront? When is the database table actually created; before after enabling the plugin?

Cheers

**Comment by matmair** [comment]
No, your namespace is wrong. Your model is loaded as `testapp.testapp.EnabledCategory` so you probably have a double reference somewhere in the packaging. If you can share a link and I will provide you with a patch - that is probably the fastest solution.

It works like any other Django app - the only thing InvenTree does is insert the plugin name into the app registry. From there everything is 100% Django behaviour. Your URL pattern is inserted into a subpath so that you do not need to modify the base urls.py.

**Comment by afkiwers** [comment]
@matmair below the link to the repository. I am keen to see what you have to change to make it work.

https://github.com/afkiwers/inventree_kicad

**Comment by afkiwers** [comment]
@matmair I encountered just another error. Any advice? It seems to not be able to locate Django.

[17/Jun/2023 09:49:08] "OPTIONS /api/plugins/install/?context=true HTTP/1.1" 200 793
  Running command git clone --filter=blob:none --quiet https://github.com/afkiwers/inventree-kicad-plugin 'C:\Users\Andre Iwers\AppData\Local\Temp\pip-install-w75miu65\inventree-kicad-plugin_92fad9e5a1fb4277b2b7466f547135e0'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [10 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Andre Iwers\AppData\Local\Temp\pip-install-w75miu65\inventree-kicad-plugin_92fad9e5a1fb4277b2b7466f547135e0\setup.py", line 5, in <module>
      from inventree_kicad.version import PLUGIN_VERSION
    File "C:\Users\Andre Iwers\AppData\Local\Temp\pip-install-w75miu65\inventree-kicad-plugin_92fad9e5a1fb4277b2b7466f547135e0\inventree_kicad\__init__.py", line 3, in <module>
      from .KiCadLibraryPlugin import KiCadLibraryPlugin
    File "C:\Users\Andre Iwers\AppData\Local\Temp\pip-install-w75miu65\inventree-kicad-plugin_92fad9e5a1fb4277b2b7466f547135e0\inventree_kicad\KiCadLibraryPlugin.py", line 11, in <module>
      from django.conf.urls import url
  ModuleNotFoundError: No module named 'django'
  [end of output]

**Comment by afkiwers** [comment]
Not stale

**Comment by SchrodingersGat** [comment]
not stale

**Comment by SchrodingersGat** [comment]
Not stle

**Comment by SchrodingersGat** [comment]
Still not stale - docs definitely need some work

**Comment by wolflu05** [comment]
Maybe with the mkdocstrings integration introduced with #4824 plugin docs can be drastically improved by auto inferring the documentation from the code docstrings.

**Comment by SchrodingersGat** [comment]
not stale
