### ISSUE TITLE
Error exporting part categories

### ISSUE THREAD

**Issue by adomigar** [inventree/InvenTree#5073]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi!

I am trying to export the part categories from one Inventree server to another from the Django administration with a .xlsx file.

An error occurs because the descriptions are empty, when it is an optional field.

Log:
```
Line number: 2 - null value in column "description" of relation "part_partcategory" violates not-null constraint DETAIL: Failing row contains (17, Componentes electrónicos, null, null, 1, null, 0, 1, 2, 2, null, Componentes electrónicos, , t).
17, Componentes electrónicos, None, None, None, 1, None, Componentes electrónicos, 0, 1
Traceback (most recent call last):
File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "description" of relation "part_partcategory" violates not-null constraint
DETAIL: Failing row contains (17, Componentes electrónicos, null, null, 1, null, 0, 1, 2, 2, null, Componentes electrónicos, , t).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/root/.local/lib/python3.9/site-packages/import_export/resources.py", line 668, in import_row
self.save_instance(instance, using_transactions, dry_run)
File "/root/.local/lib/python3.9/site-packages/import_export/resources.py", line 446, in save_instance
instance.save()
File "/home/inventree/InvenTree/InvenTree/models.py", line 542, in save
super().save(*args, **kwargs)
File "/root/.local/lib/python3.9/site-packages/mptt/models.py", line 1014, in save
super(MPTTModel, self).save(*args, **kwargs)
File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
self.save_base(using=using, force_insert=force_insert,
File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
updated = self._save_table(
File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
return manager._insert(
File "/root/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
cursor.execute(sql, params)
File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "description" of relation "part_partcategory" violates not-null constraint
DETAIL: Failing row contains (17, Componentes electrónicos, null, null, 1, null, 0, 1, 2, 2, null, Componentes electrónicos, , t).
```

### Steps to Reproduce

1. Export part categories (.xlsx).
2. Import part categories (.xlsx)

### Expected behaviour

Import part categories without description.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.11.3

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@adomigar can you check if the process works with a different file format (e.g. 'csv')

**Comment by adomigar** [comment]
Solved adding descriptions.
