### ISSUE TITLE
`invoke install` fails in Docker: mysqlclient: pkg-config can not be found

### ISSUE THREAD

**Issue by ssterling** [inventree/InvenTree#5089]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

While following the [Docker quickstart guide](https://docs.inventree.org/en/latest/start/docker_dev/#quickstart-guide) to the letter, something fails and halts the entire process.  See logs.

### Steps to Reproduce

1. Run `git clone https://github.com/inventree/InvenTree.git && cd InvenTree`.
2. Run `docker compose run inventree-dev-server invoke install`.

### Expected behaviour

Successful completion of `invoke install`.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

693d24b

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
[+] Running 1/0
 ✔ Container inventree-dev-db  Running                                     0.0s 
[+] Running 1/1
 ! inventree-dev-server Warning                                            1.0s 
[+] Building 85.5s (11/12)                                                      
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 5.08kB                                     0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim         0.8s
 => [internal] load build context                                          0.0s
 => => transferring context: 386B                                          0.0s
 => [inventree_base 1/7] FROM docker.io/library/python:3.9-slim@sha256:00  0.0s
 => => resolve docker.io/library/python:3.9-slim@sha256:0074c6241f2ff1755  0.0s
 => => sha256:0074c6241f2ff175532c72fb0fb37264e8a1ac68f97 1.86kB / 1.86kB  0.0s
 => => sha256:458de07c635e7b842b821d3d3668f3b2ab71090707d 1.37kB / 1.37kB  0.0s
 => => sha256:326a3a036ed2b15e825d1c131b205e5e1534581121c 6.91kB / 6.91kB  0.0s
 => [inventree_base 2/7] RUN apt-get update                                4.0s
 => [inventree_base 3/7] RUN apt-get install -y  --no-install-recommends  71.0s
 => [inventree_base 4/7] RUN pip install --upgrade pip                     4.0s 
 => [inventree_base 5/7] RUN    if [ `dpkg --print-architecture` = "armhf  0.3s 
 => [inventree_base 6/7] COPY ./docker/requirements.txt base_requirements  0.0s 
 => ERROR [inventree_base 7/7] RUN pip install --disable-pip-version-chec  5.2s 
------                                                                          
 > [inventree_base 7/7] RUN pip install --disable-pip-version-check -U -r base_requirements.txt:                                                                
#0 0.749 Collecting invoke>=1.4.0 (from -r base_requirements.txt (line 4))      
#0 0.955   Downloading invoke-2.1.3-py3-none-any.whl (160 kB)
#0 1.050      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.4/160.4 kB 1.9 MB/s eta 0:00:00
#0 1.187 Collecting pyyaml>=6.0 (from -r base_requirements.txt (line 5))
#0 1.230   Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
#0 1.477      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 kB 2.7 MB/s eta 0:00:00
#0 1.848 Collecting setuptools==65.6.3 (from -r base_requirements.txt (line 6))
#0 1.893   Downloading setuptools-65.6.3-py3-none-any.whl (1.2 MB)
#0 2.291      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.1 MB/s eta 0:00:00
#0 2.298 Requirement already satisfied: wheel>=0.37.0 in /usr/local/lib/python3.9/site-packages (from -r base_requirements.txt (line 7)) (0.40.0)
#0 2.553 Collecting psycopg2>=2.9.1 (from -r base_requirements.txt (line 10))
#0 2.600   Downloading psycopg2-2.9.6.tar.gz (383 kB)
#0 2.742      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.0/384.0 kB 2.9 MB/s eta 0:00:00
#0 2.802   Preparing metadata (setup.py): started
#0 3.061   Preparing metadata (setup.py): finished with status 'done'
#0 3.165 Collecting mysqlclient>=2.0.3 (from -r base_requirements.txt (line 11))
#0 3.201   Downloading mysqlclient-2.2.0.tar.gz (89 kB)
#0 3.244      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.5/89.5 kB 2.5 MB/s eta 0:00:00
#0 3.269   Installing build dependencies: started
#0 4.926   Installing build dependencies: finished with status 'done'
#0 4.927   Getting requirements to build wheel: started
#0 5.038   Getting requirements to build wheel: finished with status 'error'
#0 5.049   error: subprocess-exited-with-error
#0 5.049   
#0 5.049   × Getting requirements to build wheel did not run successfully.
#0 5.049   │ exit code: 1
#0 5.049   ╰─> [24 lines of output]
#0 5.049       Trying pkg-config --exists mysqlclient
#0 5.049       /bin/sh: 1: pkg-config: not found
#0 5.049       Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
#0 5.049       Trying pkg-config --exists mariadb
#0 5.049       /bin/sh: 1: pkg-config: not found
#0 5.049       Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
#0 5.049       Traceback (most recent call last):
#0 5.049         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 5.049           main()
#0 5.049         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 5.049           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 5.049         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#0 5.049           return hook(config_settings)
#0 5.049         File "/tmp/pip-build-env-eaki81eu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
#0 5.049           return self._get_build_requires(config_settings, requirements=['wheel'])
#0 5.049         File "/tmp/pip-build-env-eaki81eu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
#0 5.049           self.run_setup()
#0 5.049         File "/tmp/pip-build-env-eaki81eu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
#0 5.049           exec(code, locals())
#0 5.049         File "<string>", line 154, in <module>
#0 5.049         File "<string>", line 48, in get_config_posix
#0 5.049         File "<string>", line 27, in find_package_name
#0 5.049       Exception: Can not find valid pkg-config name.
#0 5.049       Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
#0 5.049       [end of output]
#0 5.049   
#0 5.049   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 5.052 error: subprocess-exited-with-error
#0 5.052 
#0 5.052 × Getting requirements to build wheel did not run successfully.
#0 5.052 │ exit code: 1
#0 5.052 ╰─> See above for output.
#0 5.052 
#0 5.052 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c pip install --disable-pip-version-check -U -r base_requirements.txt" did not complete successfully: exit code: 1
```

**Comment by matmair** [comment]
@ssterling on which OS and architecture are you running the command?

**Comment by SchrodingersGat** [comment]
@ssterling if you're still interested, please try again. We recently updated the docker image entirely.

**Comment by ssterling** [comment]
> @ssterling on which OS and architecture are you running the command?

Gentoo x86_64.  Also, my apologies for the delayed reply; I forgot to check my GitHub notifications.

> @ssterling if you're still interested, please try again. We recently updated the docker image entirely.

I’ve still got the same issue, somehow.

**Comment by Nerexbcd** [comment]
Got the same issue on a Bare Metal Installation

What solved my issue was running this command:
```shell
sudo apt-get install pkg-config python3-dev default-libmysqlclient-dev build-essential
```

Awnser found in: [StackOverflow](https://stackoverflow.com/questions/76585758/mysqlclient-cannot-install-via-pip-cannot-find-pkg-config-name-in-ubuntu)
