### ISSUE TITLE
[bug] "About InvenTree" button does not work on 0.12.0

### ISSUE THREAD

**Issue by T0jan** [inventree/InvenTree#5133]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

hi,

After updating to 0.12.0 bare metal the `About Inventree` Button does not work anymore. Detailed error message below.

### Steps to Reproduce

1. update server to 0.12.0 via bare metal update method
2. click `About InvenTree` in the profile drop down

### Expected behaviour

The version page should be shown

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.12.0

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Traceback (most recent call last):

File "/home/inventree/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
return super().dispatch(request, *args, **kwargs)

File "/home/inventree/env/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)

File "/home/inventree/src/InvenTree/InvenTree/views.py", line 320, in get
return self.renderJsonResponse(request)

File "/home/inventree/src/InvenTree/InvenTree/views.py", line 290, in renderJsonResponse
data['html_form'] = render_to_string(

File "/home/inventree/env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
return template.render(context, request)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/loader_tags.py", line 195, in render
return template.render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 172, in render
return self._render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/home/inventree/env/lib/python3.10/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/home/inventree/src/InvenTree/part/templatetags/inventree_extras.py", line 299, in inventree_branch
return version.inventreeBranch()

File "/home/inventree/src/InvenTree/InvenTree/version.py", line 165, in inventreeBranch
branch = main_repo.refs.follow(b'HEAD')[0][1].decode()

IndexError: list index out of range
```

**Comment by SchrodingersGat** [comment]
It seems to work fine on the demo server (production docker) and my local setup (development docker). But may well be related to running bare-metal. @matmair can you reproduce?

**Comment by gunstr** [comment]
Maybe the [same problem as I had](https://github.com/inventree/InvenTree/discussions/5066#discussioncomment-6216843)? I missed the requirement to upgrade to Python 3.9 and with 3.8 the about dialog cannot be opened...

**Comment by LavissaWoW** [comment]
Works on my prod server, running bare.

```
# Version Information:
InvenTree-Version: 0.12.0
Django Version: 3.2.19
Commit Hash: 1d18b48
Commit Date: 2023-06-30
Commit Branch: stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: False
```

**Comment by T0jan** [comment]
seems to be more like a git related problem. if I checkout the stable branch which also points to 0.12.0 rn everything works like expected. with detached HEAD mode at 0.12.0 the error appears.

**Comment by SchrodingersGat** [comment]
@LavissaWoW what version of python are you running? Looks like @T0jan is running `3.10`
