### ISSUE TITLE
Issue with Re-install failing with KeyError: 'dbbackup'

### ISSUE THREAD

**Issue by bcdaus** [inventree/InvenTree#5249]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

While running the installer to re-install after updating Python to 3.9 to correct an issue with POs failing, I am now getting the following Error:
```
# inv update| Requirement already satisfied: setuptools in ./env/lib/python3.9/site-packages (from django-money==2.1.1->Traceback (most recent call last):
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
**KeyError: 'dbbackup'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/inventree/InvenTree/InvenTree/settings.py", line 504, in <module>
    from psycopg2.extensions import (ISOLATION_LEVEL_READ_COMMITTED,
ModuleNotFoundError: No module named 'psycopg2'
-r requirements.txt (line 115)) (44.0.0)
# inv update| Backing up InvenTree database...
# inv update| load version from file
# inv update| load version from file
# Set permissions for data dir and media: /opt/inventree/data
# Starting InvenTree
```

~~~~~
The installer then looks like it has fully completed the install, but the web page shows a 502 Bad Gateway message.
It looks like the installer error is not getting caught and the rest of the install tries to run, but will not work.

I am not a Python or Linux master so do not know the next steps.  I have run:
```
bill@DM1:~$ pip3 install psycopg2
Requirement already satisfied: psycopg2 in ./.local/lib/python3.9/site-packages (2.9.6)
```

so I am not sure what the next steps are.

Running on Ubuntu 20.04.5 LTS.  Python is 3.9.5.

Thanks,
Bill


### Steps to Reproduce

 sudo apt remove inventree
Follow guide at https://docs.inventree.org/en/latest/start/installer/#quick-script to reinstall:
wget -qO install.sh https://get.inventree.org && bash install.sh 
Churn Churn.  Error

### Relevant log output

_No response_

**Comment by SchrodingersGat** [comment]
Likely is an issue with the virtual environment not being set correctly after changing python versions, but hard to say from this error message alone.

**Comment by bcdaus** [comment]
Any hints on how to resolve this?  I have purged my opt/inventree folder and the /bin/inventree folder (backing up the DATA folder first and the config.yaml file) after uninstalling in the hope that a full reinstall might clean things up, but am getting stuck at the same place.

**Comment by SchrodingersGat** [comment]
You can safely remove the entire venv directory and re-create it from scratch. There is no application data in there.

**Comment by bcdaus** [comment]
Getting further on.  I can reinstall and make use of the defaults which works fine, but as soon as I set the config to use my current Postgresql data base I get the "ModuleNotFoundError: No Module named 'psycopg2'" error in the inventree-worker-1.service.log.
At this stage I am looking to stay with the default sqlite db.  Is there anyway to restore the data from the etc/inventree/data/backup folder to a sqlitedb?  Otherwise I can still get to my postgresql db if its possible to do a JSON export that could then be imported in the Invoke Import command.

**Comment by bcdaus** [comment]
Closing - ran up Ubuntu on another old laptop - installed Docker and learned how to use it.
Linked Docker Inventree image back to current Postgresql database.  All good.
