### ISSUE TITLE
invoke update failing with error

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#5311]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I'm running a version that is a few weeks old. Did a sync to github and trying to ```invoke update``` and getting a error:

```
inventree@inventree:~/src$ invoke update
Traceback (most recent call last):
  File "/usr/bin/invoke", line 11, in <module>
    load_entry_point('invoke==1.4.1', 'console_scripts', 'invoke')()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python3/dist-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/inventree/src/tasks.py", line 326, in <module>
    def update(c, skip_backup=False, no_frontend: bool = False, frontend: bool = False):
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 338, in inner
    obj = klass(
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
  File "/usr/lib/python3.10/inspect.py", line 1245, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
```

### Steps to Reproduce

1. git pull origin master

inventree@inventree:~/src$ git log -1
commit 4e0f22aa00d92638ef69372d4afe4b9ad661301a (HEAD -> master, origin/master, origin/HEAD)

Run ```invoke update```

### Expected behaviour

invoke update should upgrade the version. 

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: 370021b
Commit Date: 15/07/2023
Commit Branch: master
Database: mysql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by wolflu05** [comment]
Hello @StormTrooper ,

which version of invoke do you have installed? You could check that via `pip freeze | grep invoke`. Maybe this is related: https://github.com/pyinvoke/invoke/issues/357

**Comment by StormTrooper** [comment]
```
inventree@inventree:~/src$ pip freeze | grep invoke
invoke==1.4.1
```

Thanks, will look into the link

**Comment by StormTrooper** [comment]
Looks like invoke 1.4.1 is the latest on Ubuntu 23.04

Downloaded 2.2.0 from source and manually installed. This has fixed the issue.

**Comment by Kedarius** [comment]
I've run into the same issue and I can confirm that
`pip install --upgrade invoke`
solved the issue for me.
