### ISSUE TITLE
Crash when creating Build Output for a serialized item

### ISSUE THREAD

**Issue by Polsaker** [inventree/InvenTree#5376]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When I try to create a Build Output for a serialized item (ticking the "Auto Allocate Serial Numbers" box) I get the following error:

```
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/generics.py", line 190, in post
return self.create(request, *args, **kwargs)

File "/opt/inventree/InvenTree/InvenTree/mixins.py", line 22, in create
self.perform_create(serializer)

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
serializer.save()

File "/opt/inventree/InvenTree/build/serializers.py", line 355, in save
build.create_build_output(

File "/usr/lib/python3.9/contextlib.py", line 79, in inner
return func(*args, **kwds)

File "/opt/inventree/InvenTree/build/models.py", line 723, in create_build_output
BuildItem.objects.create(

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 451, in create
obj = self.model(**kwargs)

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/base.py", line 503, in __init__
raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))

TypeError: BuildItem() got an unexpected keyword argument 'build'
```

I managed to replicate this in the demo site 

### Steps to Reproduce

1. Create a build order for an item that has a serialized component
2. Allocate stock, etc
3. Create a new build output with the serial number of an existing component and tick the `Auto Allocate Serial Numbers
` box

### Expected behaviour

The build output should be created instead of crashing

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: 36d669d7
Commit Date: None
Commit Branch: master
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.15.74-1-pve-x86_64-with-glibc2.31
Installer: PKG
Target: debian:11
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.7.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@Polsaker thanks for reporting :)
