### ISSUE TITLE
Can't get Inventree working with Docker

### ISSUE THREAD

**Issue by E-Hain** [inventree/InvenTree#5462]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

I have tried multiple times to get Inventree working with docker. I have followed documentation as close as possible. I originally tried changing somethings. I wasn't able to get Inventree up and running at all. So I went back to the documentation and decided to leave everything as default as possible. I am able to get Postgres and Nginx running successfully. (As far as I can tell) However Inventree Server and Worker containers both keep restarting. I can confirm this both from Portainer and from the CLI. (using sudo docker ps) I cannot figure out why they both keep restarting. I cannot think of anything that I have configured that would conflict with Inventree.

### Steps to Reproduce

0. Follow Production Documentation For Docker https://docs.inventree.org/en/latest/start/docker_prod/

### Relevant log output

```bash
if model.objects.filter(label=filename).exists():
  File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 561, in has_results
    return compiler.has_results()
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
[2023-08-21 03:12:08 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/root/.local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/root/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inventree/InvenTree/InvenTree/wsgi.py", line 15, in <module>
    application = get_wsgi_application()  # pragma: no cover
  File "/root/.local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/label/apps.py", line 41, in ready
    self.create_labels()  # pragma: no cover
  File "/home/inventree/InvenTree/label/apps.py", line 53, in create_labels
    self.create_labels_category(
  File "/home/inventree/InvenTree/label/apps.py", line 144, in create_labels_category
    self.create_template_label(model, src_dir, ref_name, label)
  File "/home/inventree/InvenTree/label/apps.py", line 180, in create_template_label
    if model.objects.filter(label=filename).exists():
  File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 808, in exists
    return self.query.has_results(using=self.db)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 561, in has_results
    return compiler.has_results()
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1145, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "label_stockitemlabel" does not exist
LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...
                               ^
[2023-08-21 03:12:08 +0000] [8] [WARNING] Worker with pid 12 was terminated due to signal 15
[2023-08-21 03:12:08 +0000] [8] [WARNING] Worker with pid 11 was terminated due to signal 15
[2023-08-21 03:12:08 +0000] [8] [WARNING] Worker with pid 10 was terminated due to signal 15
```

**Comment by matmair** [comment]
Seems to me that migrations are missing from the database. Have you performed the [database setup step](https://docs.inventree.org/en/latest/start/docker_prod/#initial-database-setup)?

**Comment by E-Hain** [comment]
I have, yes. It opened a docker container and ran everything successfully. Save for one thing it did say in the console something like "didn't recognize --no-frontend." However, it still opened a database container and created all of the required files from what I could tell. Then, it closed the initially opened container, leaving only a database container running. I then ran 'sudo docker compose up -d', and it spooled up the rest of the containers. Finally leading me to where I am now.

**Comment by E-Hain** [comment]
I have run through the whole thing again... something I never noticed before, tho. When I run 'sudo docker compose run inventree-server invoke superuser' I get this response. Any idea what I would do in this case? ![Screenshot_20230821_074259_Termius.jpg](https://github.com/inventree/InvenTree/assets/130486329/3bf27193-1141-4143-9db9-4d93749587d5)

**Comment by wolflu05** [comment]
Are you sure you run invoke update and all the relevant volumes are mounted in the update and production container. Also is your server using your database container and no internal SQLite?

**Comment by E-Hain** [comment]
I assigned a mount path in the .env file.

"INVENTREE_EXT_VOLUME=/home/*myuser*/*etc*/*etc*

That file doesn't contain anything until I run _sudo docker compose run inventree-server invoke update --no-frontend_ which then gives me this output ![Screenshot_20230821_083136_Brave.png](https://github.com/inventree/InvenTree/assets/130486329/54794067-a8b1-408d-853a-a2245c5c8297)

Afterward, the mount path fills with the above-mentioned directories. >*backup  config.yaml  media  pgdb  plugins.txt  secret_key.txt  static*<

**Comment by E-Hain** [comment]
This is the postgresql log output.

2023-08-21 11:41:41.237 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.237 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.237 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.237 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.237 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.237 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.238 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.238 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.238 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.238 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.239 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.239 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.240 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.240 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.241 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.241 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.242 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.242 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.242 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.242 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.244 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.244 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.244 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.244 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.246 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.246 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.246 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.246 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.247 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.247 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.247 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.247 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.248 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.248 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.248 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.248 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.253 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.253 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.253 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.253 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.254 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.254 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.254 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.254 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.254 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.254 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.254 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.254 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.255 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.255 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.255 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.255 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.255 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.255 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.255 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.255 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.255 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.255 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.256 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.256 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.256 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.256 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.256 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.256 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.256 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.256 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.257 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.257 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.257 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.257 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.257 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.257 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.258 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.258 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.258 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.258 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.259 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.259 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.260 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.260 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.261 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.261 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.262 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.262 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.265 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.265 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.265 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.265 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.270 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.270 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.272 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.272 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.274 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.274 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.276 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.276 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.277 UTC [71] ERROR:  relation "common_inventreesetting" does not exist at character 112
2023-08-21 11:41:41.277 UTC [71] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('INVENTREE_DEFAULT_CURRENCY') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1
2023-08-21 11:41:41.304 UTC [71] ERROR:  relation "auth_user" does not exist at character 280
2023-08-21 11:41:41.304 UTC [71] STATEMENT:  SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = 'root' LIMIT 21

**Comment by SchrodingersGat** [comment]
@E-Hain just run this command:

```
sudo docker compose run inventree-server invoke update
```

**Comment by E-Hain** [comment]
> @E-Hain just run this command:
> 
> ```
> sudo docker compose run inventree-server invoke update
> ```

This worked like a charm! For some reason, docker couldn't execute past the ```--no-frontend```

**Comment by wolflu05** [comment]
Maybe due to your version, this argument is a new one.
