### ISSUE TITLE
Plugin - admin.site.register() throws an error now

### ISSUE THREAD

**Issue by afkiwers** [inventree/InvenTree#5523]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

In 0.12.0 dev everything was working, However suddenly I can't access the admin backend anymore without getting an error. I have to remove admin.site.register(SelectedCategory, SelectedCategoryAdmin) from my admin.py to not run into an error.

![image](https://github.com/inventree/InvenTree/assets/42826581/9ac1a888-2bf2-4071-b49f-f9fa6ea1d7c7)

### It was working here
```
# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.19
Commit Hash: 6e64c27
Commit Date: 2023-06-28
Commit Branch: run-locally
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: Windows-10-10.0.22621-SP0
Installer: GIT

Active plugins: [{'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.0.0'}]

```

### Error message
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 3.2.20
Python Version: 3.11.4
Installed Applications:
['django.contrib.admin',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'plugin.apps.PluginAppConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'web',
 'generic',
 'InvenTree.apps.InvenTreeConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'user_sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'maintenance_mode',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownify',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools',
 'dbbackup',
 'taggit',
 'flags',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'allauth_2fa',
 'dj_rest_auth',
 'dj_rest_auth.registration',
 'drf_spectacular',
 'django_ical',
 'sslserver',
 'plugins.inventree_kicad']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'x_forwarded_for.middleware.XForwardedForMiddleware',
 'user_sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'InvenTree.middleware.InvenTreeRemoteUserMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'InvenTree.middleware.CustomAllauthTwoFactorMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'InvenTree.middleware.Check2FAMiddleware',
 'maintenance_mode.middleware.MaintenanceModeMiddleware',
 'InvenTree.middleware.InvenTreeExceptionProcessor']



Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\contrib\admin\sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\contrib\admin\sites.py", line 522, in index
    app_list = self.get_app_list(request)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\contrib\admin\sites.py", line 505, in get_app_list
    app_dict = self._build_app_dict(request)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\contrib\admin\sites.py", line 487, in _build_app_dict
    'app_url': reverse(
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\andre\PycharmProjects\InvenTree\venv\Lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /admin/
Exception Value: Reverse for 'app_list' with keyword arguments '{'app_label': 'inventree_kicad'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>exchange|build|common|company|plugin|label|order|part|report|stock|auth|users|user_sessions|sites|authtoken|error_report|django_q|taggit|flags|account|socialaccount|otp_totp|otp_static)/$']
```

### Steps to Reproduce

Use app mixin and register model in admin.py of your plugin

### Expected behaviour

Plugin models can be added to the admin backend

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20
Commit Hash: 00d4dfc
Commit Date: 2023-09-01
Commit Branch: run_locally_0_12_6
Database: sqlite3
Debug-Mode: True
Deployed using Docker: False
Platform: Windows-10-10.0.22621-SP0
Installer: GIT

Active plugins: [{'name': 'KiCadLibraryPlugin', 'slug': 'kicad-library-plugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by afkiwers** [comment]
Error is thrown here

![image](https://github.com/inventree/InvenTree/assets/42826581/7fa91606-3e50-4c84-b098-ec6296b3e23c)
