### ISSUE TITLE
[BUG] Exchange rate provider is closed now

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#5631]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Our current default exchange rate provider is closed now - and the change was not smooth either. See https://github.com/Formicka/exchangerate.host/issues/236#issuecomment-1738539199

We need to:
1) Disable the CI checks for now
2) Implement an alternative
3) (Optional) Bring down ApiLayer once and for all before they close all APIs we need

### Steps to Reproduce

Look at any current [CI](https://github.com/inventree/InvenTree/actions/runs/6333198194/job/17202067465?pr=5582)

### Expected behaviour

Updating exchange rates

### Deployment Method

- [X] Docker
- [X] Bare metal

### Version Information

Every version>0.6.0 and a couble before are probably effected.

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by matmair** [comment]
Switch to https://www.frankfurter.app

**Comment by matmair** [comment]
TODO: revert https://github.com/inventree/InvenTree/pull/5628/commits/8ed7fbcba5e190d58d7545efbc903e8f72ff1ac7

**Comment by mrtumnus** [comment]
Is there a workaround for production systems at the moment?  My docker container is failing to (re-)start.

**Comment by SchrodingersGat** [comment]
@mrtumnus can you please share the error logs? The broken exchange shouldn't stop your container from restarting.

And yes we have a fix in the works.

**Comment by mrtumnus** [comment]
I was running an older version of inventree (not sure what version).  After updating to latest stable (0.12.7), it started up just fine.

**Comment by mrtumnus** [comment]
Docker image hash is 2114e90a63c3 created on 2022-01-21T00:30:17.  Not sure how to find version from that.

**Comment by mrtumnus** [comment]
Here is the error message (from a restored backup):
```
[2023-10-03 03:15:13 +0500] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/inventree/InvenTree/InvenTree/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/inventree/.local/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/inventree/.local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/InvenTree/apps.py", line 27, in ready
    self.update_exchange_rates()
  File "/home/inventree/InvenTree/InvenTree/apps.py", line 142, in update_exchange_rates
    update_exchange_rates()
  File "/home/inventree/InvenTree/InvenTree/tasks.py", line 272, in update_exchange_rates
    backend.update_rates(base_currency=base)
  File "/home/inventree/InvenTree/InvenTree/exchange.py", line 32, in update_rates
    super().update_rates(base=base_currency, symbols=symbols)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/inventree/.local/lib/python3.8/site-packages/djmoney/contrib/exchange/backends/base.py", line 68, in update_rates
    for currency, value in self.get_rates(**params).items()
  File "/home/inventree/.local/lib/python3.8/site-packages/djmoney/contrib/exchange/backends/base.py", line 81, in get_rates
    return self.parse_json(response)["rates"]
KeyError: 'rates'
[2023-10-03 03:15:13 +0500] [14] [INFO] Worker exiting (pid: 14)
```

**Comment by SchrodingersGat** [comment]
@mrtumnus looks like that code is pretty outdated - I assume that with the upcoming fix in https://github.com/inventree/InvenTree/pull/5632 this will already be addresed

**Comment by matmair** [comment]
We addressed that bug a good while ago, the server wouldn't start if the exchange rate provider was unreachable.
