### ISSUE TITLE
Docker builds failing due to recent PR

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5825]
@30350n unfortunately merging this has broken our docker builds

```
2023-10-31T12:26:03.6320807Z ======================================================================
2023-10-31T12:26:03.6321472Z ERROR: test_ref_field (order.test_migrations.TestRefIntMigrations)
2023-10-31T12:26:03.6322398Z Test that the 'reference_int' field has been created and is filled out correctly.
2023-10-31T12:26:03.6323197Z ----------------------------------------------------------------------
2023-10-31T12:26:03.6323713Z Traceback (most recent call last):
2023-10-31T12:26:03.6324913Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/contrib/unittest_case.py", line 54, in tearDown
2023-10-31T12:26:03.6325843Z     self._migrator.reset()
2023-10-31T12:26:03.6326845Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/migrator.py", line 76, in reset
2023-10-31T12:26:03.6327879Z     call_command('migrate', verbosity=0, database=self._database)
2023-10-31T12:26:03.6329005Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
2023-10-31T12:26:03.6329928Z     return command.execute(*args, **defaults)
2023-10-31T12:26:03.6330878Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
2023-10-31T12:26:03.6331720Z     output = self.handle(*args, **options)
2023-10-31T12:26:03.6332763Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
2023-10-31T12:26:03.6333581Z     res = handle_func(*args, **kwargs)
2023-10-31T12:26:03.6334623Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
2023-10-31T12:26:03.6335540Z     post_migrate_state = executor.migrate(
2023-10-31T12:26:03.6338837Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
2023-10-31T12:26:03.6340225Z     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6341782Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
2023-10-31T12:26:03.6343351Z     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6344881Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
2023-10-31T12:26:03.6346136Z     state = migration.apply(state, schema_editor)
2023-10-31T12:26:03.6347321Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
2023-10-31T12:26:03.6348653Z     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
2023-10-31T12:26:03.6350341Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
2023-10-31T12:26:03.6351357Z     self.code(from_state.apps, schema_editor)
2023-10-31T12:26:03.6352521Z   File "/home/***/InvenTree/order/migrations/0079_auto_20230304_0904.py", line 50, in update_purchase_order_price
2023-10-31T12:26:03.6353540Z     order.total_price = total_price
2023-10-31T12:26:03.6354491Z   File "/usr/local/lib/python3.10/site-packages/djmoney/models/fields.py", line 111, in __set__
2023-10-31T12:26:03.6355454Z     and self.field._currency_field.null
2023-10-31T12:26:03.6356474Z AttributeError: 'InvenTreeModelMoneyField' object has no attribute '_currency_field'
```

and

```
2023-10-31T12:26:03.6213495Z ======================================================================
2023-10-31T12:26:03.6214442Z ERROR: test_po_migration (order.test_migrations.TestAdditionalLineMigration)
2023-10-31T12:26:03.6218592Z Test that the the PO lines where converted correctly.
2023-10-31T12:26:03.6219539Z ----------------------------------------------------------------------
2023-10-31T12:26:03.6230801Z Traceback (most recent call last):
2023-10-31T12:26:03.6232400Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/contrib/unittest_case.py", line 54, in tearDown
2023-10-31T12:26:03.6233453Z     self._migrator.reset()
2023-10-31T12:26:03.6234576Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/migrator.py", line 76, in reset
2023-10-31T12:26:03.6235724Z     call_command('migrate', verbosity=0, database=self._database)
2023-10-31T12:26:03.6237039Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
2023-10-31T12:26:03.6238038Z     return command.execute(*args, **defaults)
2023-10-31T12:26:03.6239094Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
2023-10-31T12:26:03.6240025Z     output = self.handle(*args, **options)
2023-10-31T12:26:03.6241046Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
2023-10-31T12:26:03.6241952Z     res = handle_func(*args, **kwargs)
2023-10-31T12:26:03.6243037Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
2023-10-31T12:26:03.6244024Z     post_migrate_state = executor.migrate(
2023-10-31T12:26:03.6245073Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
2023-10-31T12:26:03.6246307Z     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6247749Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
2023-10-31T12:26:03.6249947Z     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6251232Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
2023-10-31T12:26:03.6252179Z     state = migration.apply(state, schema_editor)
2023-10-31T12:26:03.6253385Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
2023-10-31T12:26:03.6254496Z     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
2023-10-31T12:26:03.6255893Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
2023-10-31T12:26:03.6257036Z     self.code(from_state.apps, schema_editor)
2023-10-31T12:26:03.6258039Z   File "/home/***/InvenTree/order/migrations/0079_auto_20230304_0904.py", line 50, in update_purchase_order_price
2023-10-31T12:26:03.6258883Z     order.total_price = total_price
2023-10-31T12:26:03.6260130Z   File "/usr/local/lib/python3.10/site-packages/djmoney/models/fields.py", line 111, in __set__
2023-10-31T12:26:03.6261078Z     and self.field._currency_field.null
2023-10-31T12:26:03.6261878Z AttributeError: 'InvenTreeModelMoneyField' object has no attribute '_currency_field'
```

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/5778#issuecomment-1787140954_

**Comment by 30350n** [comment]
Urgh, that's not good, sorry. I'll take a look at it! Any reason why this wouldn't have shown up in earlier pipeline runs?

**Comment by SchrodingersGat** [comment]
Actually, not just the docker build which is failing:

<img width="922" alt="Screenshot 2023-11-01 at 12 27 31 am" src="https://github.com/inventree/InvenTree/assets/10080325/bfc0223a-8944-4a5c-866e-4592bdf3531d">

**Comment by SchrodingersGat** [comment]
This link  may be very useful:

https://stackoverflow.com/questions/77199135/moneyfield-object-has-no-attribute-currency-field-in-django-money-when-runn

**Comment by SchrodingersGat** [comment]
A new update pushed only yesterday may be the cause here?

https://pypi.org/project/django-money/3.4.0/

**Comment by 30350n** [comment]
Oh, that'd make sense I guess. Maybe we should just "freeze" the version to 3.3 then?

**Comment by 30350n** [comment]
Althought actually ... well it should be set to 3.3 as that's whats defined in `requirements.txt`, right? Or does docker rebuild that from the `requirements.in`?

**Comment by 30350n** [comment]
Ah, I guess it's this: https://github.com/django-money/django-money/issues/731

**Comment by 30350n** [comment]
Seems to be unrelated to the latest release and just a 3.3 issue. I guess I'll make another PR and change the version to 3.2 and possibly rollback the migrations?
