### ISSUE TITLE
`invoke update` fails with `state value is not 0|1`

### ISSUE THREAD

**Issue by reitermarkus** [inventree/InvenTree#6066]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I think this is the same error as described in https://github.com/inventree/InvenTree/issues/3618 and supposedly fixed in https://github.com/inventree/InvenTree/pull/4148.

### Steps to Reproduce

Not sure how to reproduce. I assume `invoke update` being killed at exactly the moment it tries to write to `maintenance_mode.txt`.

It seems pretty obvious why this race condition can happen: 

`set_maintenance_mode` calls `file_write`:

https://github.com/fabiocaccamo/django-maintenance-mode/blob/main/maintenance_mode/io.py#L15

which in turn calls `futils.write_file` which is just your standard `open` + `write`:

https://github.com/fabiocaccamo/python-fsutil/blob/b1920f22c290f8f7b2e98d22f91d052b7d1dd2c7/fsutil/__init__.py#L1317-L1332a

i.e. not atomic.

Solution: An atomic write function should be used in `django-maintenance-mode`.

### Expected behaviour

No race condition.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Docker image @latest as of time of writing.

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/inventree/InvenTree/plugin/apps.py", line 46, in ready
    registry.reload_plugins(full_reload=True, force_reload=True, collect=True)
  File "/home/inventree/InvenTree/plugin/registry.py", line 265, in reload_plugins
    with maintenance_mode_on():
  File "/usr/local/lib/python3.10/site-packages/maintenance_mode/core.py", line 74, in __enter__
    self.old_value = get_maintenance_mode()
  File "/usr/local/lib/python3.10/site-packages/maintenance_mode/core.py", line 40, in get_maintenance_mode
    return backend.get_value()
  File "/usr/local/lib/python3.10/site-packages/maintenance_mode/backends.py", line 70, in get_value
    return self.from_str_to_bool_value(statefile.read())
  File "/usr/local/lib/python3.10/site-packages/maintenance_mode/backends.py", line 26, in from_str_to_bool_value
    raise ValueError("state value is not 0|1")
ValueError: state value is not 0|1
```
```

**Comment by SchrodingersGat** [comment]
@reitermarkus thanks for raising the issue. Can you determine what the actual file contents are?

**Comment by reitermarkus** [comment]
No file contents, `maintenance_mode.txt` was empty.

**Comment by SchrodingersGat** [comment]
@reitermarkus looks like your PR has made it into a new release:

https://github.com/fabiocaccamo/django-maintenance-mode/releases/tag/0.21.0

I'll update to the latest version
