### ISSUE TITLE
make backup - error

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#611]
I found [this](https://inventree.readthedocs.io/en/latest/backup.html) and thought it would be a good idea to cron job out a backup every few days. When I tired it I got the following errors on both my main instance and test instance
```
# make backup
cd InvenTree && python3 manage.py dbbackup
Backing Up Database: ../inventree_default_db.sqlite3
2020-01-06 23:48:08,171 INFO Backing Up Database: ../inventree_default_db.sqlite3
Writing file to default-InvenTree-2020-01-06-234808.dump
2020-01-06 23:48:08,198 INFO Writing file to default-InvenTree-2020-01-06-234808.dump
cd InvenTree && python3 manage.py mediabackup
FileNotFoundError: [Errno 2] No such file or directory: '/root/InvenTree/inventree_media'
  File "/usr/local/lib/python3.7/site-packages/dbbackup/utils.py", line 116, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 52, in handle
    self.backup_mediafiles()
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 93, in backup_mediafiles
    tarball = self._create_tar(filename)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 75, in _create_tar
    for media_filename in self._explore_storage():
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 65, in _explore_storage
    subdirs, files = self.media_storage.listdir(path)
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 315, in listdir
    for entry in os.scandir(path):

2020-01-06 23:48:10,026 ERROR FileNotFoundError: [Errno 2] No such file or directory: '/root/InvenTree/inventree_media'
  File "/usr/local/lib/python3.7/site-packages/dbbackup/utils.py", line 116, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 52, in handle
    self.backup_mediafiles()
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 93, in backup_mediafiles
    tarball = self._create_tar(filename)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 75, in _create_tar
    for media_filename in self._explore_storage():
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 65, in _explore_storage
    subdirs, files = self.media_storage.listdir(path)
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 315, in listdir
    for entry in os.scandir(path):

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/utils.py", line 116, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 52, in handle
    self.backup_mediafiles()
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 93, in backup_mediafiles
    tarball = self._create_tar(filename)
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 75, in _create_tar
    for media_filename in self._explore_storage():
  File "/usr/local/lib/python3.7/site-packages/dbbackup/management/commands/mediabackup.py", line 65, in _explore_storage
    subdirs, files = self.media_storage.listdir(path)
  File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 315, in listdir
    for entry in os.scandir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/root/InvenTree/inventree_media'
*** Error code 1

Stop.
make: stopped in /root/InvenTree
```

**Comment by a7hybnj2** [comment]
I am using the generic `manage.py runserver` because I am just a single user.

**Comment by SchrodingersGat** [comment]
You need to tell Inventree where to put the backup files. The default directory (`/root/InvenTree/inventree_media`) does not exist by the looks of things.

Set the `backup_dir` parameter in the `config.yaml` file and see if that works..

![image](https://user-images.githubusercontent.com/10080325/73604578-162c8600-45e7-11ea-90b8-85aec7bb2c86.png)

**Comment by a7hybnj2** [comment]
If you don't specify a location where does it go?
```
root@InvenTree:~/InvenTree # make backup
cd InvenTree && python3 manage.py dbbackup
Backing Up Database: ../inventree_default_db.sqlite3
2020-02-03 18:23:32,530 INFO Backing Up Database: ../inventree_default_db.sqlite3
Writing file to default-InvenTree-2020-02-03-182332.dump
2020-02-03 18:23:32,563 INFO Writing file to default-InvenTree-2020-02-03-182332.dump
cd InvenTree && python3 manage.py mediabackup
Writing file to InvenTree-2020-02-03-182334.tar
2020-02-03 18:23:34,601 INFO Writing file to InvenTree-2020-02-03-182334.tar
root@InvenTree:~/InvenTree # la
./				.travis.yml			docs/
../				CONTRIBUTING.md			images/
.coveragerc			InvenTree/			inventree_default_db.sqlite3
.git/				LICENSE				inventree_media/
.gitattributes			Makefile			inventree_static/
.gitignore			README.md			requirements.txt
.readthedocs.yml		ci/				setup.cfg
root@InvenTree:~/InvenTree # 
```

**Comment by a7hybnj2** [comment]
I did set a specific location and have a sucessful backup. I was just trying to find all the other backups to get rid of them.

**Comment by SchrodingersGat** [comment]
@a7hybnj2 it will be stored in your local temp directory (the exact location will depend on your OS, etc)
