### ISSUE TITLE
Server migration/JSON import results in "Key (key)=(BUILDORDER_REFERENCE_PATTERN) already exists"

### ISSUE THREAD

**Issue by n0xlf** [inventree/InvenTree#6127]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

As the title states, I'm trying to migrate a docker server to another docker server and getting the error "Key (key)=(BUILDORDER_REFERENCE_PATTERN) already exists" during the JSON import.

Thanks!

### Steps to Reproduce

1.  Update source server with **_docker-compose pull_**
2.  Update source server installation with **_docker-compose run inventree-server invoke update_**
3.  Export data on source server with **_docker-compose run inventree-server invoke export-records -f /home/inventree/data/export.json_**
4. Clean install on destination server, running **_docker-compose run inventree-server invoke update_** to initialize the DB
5. Copy data/media folder from source server to destination server
6. Copy esport.json from source to destination, in /data
7. Import data on destination server with **_docker-compose run inventree-server invoke import-records -f /home/inventree/data/export.json_**
8. See error

### Relevant log output

```bash
django.db.utils.IntegrityError: Problem installing fixture '/home/inventree/data/export.json.tmp.json': Could not load common.InvenTreeSetting(pk=1): duplicate key value violates unique constraint "common_inventreesetting_key_key"
DETAIL:  Key (key)=(BUILDORDER_REFERENCE_PATTERN) already exists.
```

**Comment by n0xlf** [comment]
Importing with the "-c" option fixed the above error, but now I'm getting:

django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "build_build" violates foreign key constraint "build_build_responsible_id_49af6fa1_fk_users_owner_id"
DETAIL:  Key (responsible_id)=(16) is not present in table "users_owner".

**Comment by SchrodingersGat** [comment]
The -c option will definitely be required to clear our existing data, as you have found. 

The next error may be due to how the "owner" data is constructed. Can you check in the exported data (text editor) to see if the "users_owner" data is there, and there is an entry for record 16?

**Comment by n0xlf** [comment]
I don't see anything for users_owner.  The users themselves seem to be there under the auth.user model.  I can change the responsible fields to null but that doesn't help obviously.

BTW, this is the best open source project I've ever seen!  Absolutely amazing!!

**Comment by SchrodingersGat** [comment]
@n0xlf thanks for you kind words :)

I think what you have uncovered is a bug in the importing process. The "owners" table is reconstructed after import, so if there are owners referenced in the data being imported, perhaps that is causing the reference error.

I am currently away on holiday, can look into this in a few weeks. One of the other devs may have some time to look into it before then.

Alternatively, we would happily receive a PR to address this  if you have some time to submit one. New contributors are always welcome!

**Comment by n0xlf** [comment]
No worries - I'm not quite talented enough to contribute to the code base, but thanks for the offer!

**Comment by SchrodingersGat** [comment]
@n0xlf are you able to provide the full error logs when you run the import command?

**Comment by n0xlf** [comment]
Following up on this - I was going to get you logs, updated everything first, and now get:

Backing up InvenTree database...
Python version 3.10.13 - /usr/local/bin/python3
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/root/.local/lib/python3.10/site-packages/allauth/account/apps.py", line 15, in ready
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: allauth.account.middleware.AccountMiddleware must be added to settings.MIDDLEWARE
ERROR: 1

**Comment by n0xlf** [comment]
Here ya go:

`[+] Creating 1/0
 ✔ Container inventree-production-inventree-db-1  Running                                                                                                                                                                               0.0s
Loading config file : /home/inventree/data/config.yaml
Deleting all data from InvenTree database...
Python version 3.10.13 - /usr/local/bin/python3
/root/.local/lib/python3.10/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Importing database records from '/home/inventree/data/export.json'
Python version 3.10.13 - /usr/local/bin/python3
/root/.local/lib/python3.10/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "build_build" violates foreign key constraint "build_build_responsible_id_49af6fa1_fk_users_owner_id"
DETAIL:  Key (responsible_id)=(21) is not present in table "users_owner".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 131, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 285, in check_constraints
    cursor.execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "build_build" violates foreign key constraint "build_build_responsible_id_49af6fa1_fk_users_owner_id"
DETAIL:  Key (responsible_id)=(21) is not present in table "users_owner".
`

**Comment by SchrodingersGat** [comment]
@n0xlf would you be willing to send through the exported dataset (`.json` file) to test with? This issue does not occur on my test dataset. If you are able, please send to `support @ inventree . org` - I understand if you are not willing though!

**Comment by n0xlf** [comment]
That would actually be great if you can test since I'm running it 
dockerized...I'll send shortly


------ Original Message ------
From "Oliver" ***@***.***>
To "inventree/InvenTree" ***@***.***>
Cc "n0xlf" ***@***.***>; "Mention" ***@***.***>
Date 1/14/2024 11:19:00 PM
Subject Re: [inventree/InvenTree] Server migration/JSON import results 
in "Key (key)=(BUILDORDER_REFERENCE_PATTERN) already exists" (Issue 
#6127)

**Comment by SchrodingersGat** [comment]
After receiving your data, I can confirm that the issue occurs with your dataset. To re-export this, from your "old" docker image, run the following steps:

### Login to Docker Container CLI

`docker compose run inventree-server sh`

### Edit tasks.py

- `nano tasks.py`
- Remove line `'users.owner'` in function `content_excludes()`
- save file and exit

### Export Data

You can now export the data using `invoke export-records` - and the exported data should now contain the required `users.owner` fields. Please confirm!

### Import Data

Now, you should be able to re-import the data into your *new* container!

**Comment by SchrodingersGat** [comment]
> Unfortunately no luck:

Not exactly - we have "fixed" one error, now onto the next one!

Unfortunately, the "next one" has broken import/export entirely. New patch incoming, hopefully tonight if I have time!

**Comment by n0xlf** [comment]
Assuming I'm doing this correctly (running the Docker version) I simply did a wget on apps.py in Inventree/Inventree and tasks.py in root from the RAW github both on the source and destination servers.  Then I re-ran the export/import, and get:

`Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "/root/.local/lib/python3.10/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/root/.local/lib/python3.10/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: Problem installing fixture '/home/inventree/data/export.json.data.json': Could not load users.Owner(pk=1): duplicate key value violates unique constraint "unique_owner"
DETAIL:  Key (owner_type_id, owner_id)=(85, 1) already exists.`

**Comment by SchrodingersGat** [comment]
@n0xlf ok, what version of InvenTree are you running? (ignoring your manual file changes)

If you want to re-send me the newly exported data file, I can use that locally to work out what is going on

**Comment by SchrodingersGat** [comment]
This should be addressed now in https://github.com/inventree/InvenTree/pull/6271

**Comment by n0xlf** [comment]
Success!!  You're awesome!!

**Comment by SchrodingersGat** [comment]
@n0xlf thanks for the confirmation that it works! That was a very tricky edge case, I'm glad that we have found and squashed it :)

If you are not already, please consider supporting the project so that we can continue to provide quick support like this!

**Comment by n0xlf** [comment]
Sent...thanks again!
