### ISSUE TITLE
Password authentication failed

### ISSUE THREAD

**Issue by SandraPartida** [inventree/InvenTree#6143]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Each time I run this command:
`docker compose run inventree-server invoke update`
I have the following error:

```
pg_dump: error: connection to server at "inventree-db" (172.23.0.2), port 5432 failed: FATAL:  password authentication failed for user "sandra"
```

I don't really see what I've missed, I've edited the `.env` file to set my `INVENTREE_EXT_VOLUME` persistent directory, the `INVENTREE_ADMIN_USER` and `INVENTREE_ADMIN_PASSWORD`and `INVENTREE_ADMIN_EMAIL`, `INVENTREE_DB_USER` and `INVENTREE_DB_PASSWORD`

All other config are defaults.

here is my .env:

```
# InvenTree environment variables for a postgresql production setup

# Location of persistent database data (stored external to the docker containers)
# Note: You *must* un-comment this line, and point it to a path on your local machine

# e.g. Linux
INVENTREE_EXT_VOLUME=$HOME/inventree/persistent

# e.g. Windows (docker desktop)
#INVENTREE_EXT_VOLUME=c:/Users/inventree/data

# Default web port for the InvenTree server
INVENTREE_WEB_PORT=1337

# Ensure debug is false for a production setup
INVENTREE_DEBUG=False
INVENTREE_LOG_LEVEL=WARNING

# InvenTree admin account details
# Un-comment (and complete) these lines to auto-create an admin acount
INVENTREE_ADMIN_USER=sandra
INVENTREE_ADMIN_PASSWORD=adminpassword
INVENTREE_ADMIN_EMAIL=san@gmail.com

# Database configuration options
# Note: The example setup is for a PostgreSQL database
INVENTREE_DB_ENGINE=postgresql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=inventree-db
INVENTREE_DB_PORT=5432

# Database credentials - These must be configured before running
# Uncomment the lines below, and change from the default values!
INVENTREE_DB_USER=sandra
INVENTREE_DB_PASSWORD=password

# Redis cache setup (disabled by default)
# Un-comment the following lines to enable Redis cache
# Note that you will also have to run docker-compose with the --profile redis command
# Refer to settings.py for other cache options
#INVENTREE_CACHE_HOST=inventree-cache
#INVENTREE_CACHE_PORT=6379

# Options for gunicorn server
INVENTREE_GUNICORN_TIMEOUT=90

# Enable custom plugins?
INVENTREE_PLUGINS_ENABLED=False

# Run migrations automatically?
INVENTREE_AUTO_UPDATE=False

# Image tag that should be used
INVENTREE_TAG=stable

COMPOSE_PROJECT_NAME=inventree-production
```

### Steps to Reproduce

set the .env file and run `docker compose run inventree-server invoke update`

### Relevant log output

```bash
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
    self._save_new_backup(database)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/management/commands/dbbackup.py", line 106, in _save_new_backup
    outputfile = self.connector.create_dump()
  File "/root/.local/lib/python3.10/site-packages/dbbackup/db/base.py", line 92, in create_dump
    return self._create_dump()
  File "/root/.local/lib/python3.10/site-packages/dbbackup/db/postgresql.py", line 112, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump --dbname=postgresql://sandra:password@inventree-db:5432/inventree --format=custom
pg_dump: error: connection to server at "inventree-db" (172.23.0.2), port 5432 failed: FATAL:  password authentication failed for user "sandra"
```
```

**Comment by SandraPartida** [comment]
Somehow solved the issue by wiping my persistent directory and `docker volume prune`

**Comment by matmair** [comment]
@SandraPartida this error message sounds like the database password was wrong - maybe that is helpful in the future
