### ISSUE TITLE
Removing a line from a BoM after a part is allocated can break the stock

### ISSUE THREAD

**Issue by JambonLeVrai** [inventree/InvenTree#6145]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When stock has been allocated to a build order for an assembly item, the BoM of the item can still be changed. However, removing an item from the BoM creates some unexpected behavior. The item stays allocated, and the stock becomes inaccessible, showing internal server error.
This can be "fixed" though, by simply removing the faulty stock object and recreating a new one.

### Steps to Reproduce

1. Create an assembly part with 2 different parts in its BoM
2. Create a build order for the assembled part
3. Allocate the stock
4. Remove one part from the BoM

### Expected behaviour

When removing an item from the BoM of an assembly, a check should be done to see if any build order for this assembly has stock allocated to the removed item. Then, I'd expect two different possible behaviours depending on what people here find better :
1. Either completely prevent the user from deleting the line until all stock has been deallocated
2. Or prompt the user whether all the allocated stock is deallocated, or removed, when removing the line

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.13.0

### Please verify if you can reproduce this bug on the demo site.

- [x] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Traceback (most recent call last):

File "/root/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
response = response.render()

File "/root/.local/lib/python3.10/site-packages/django/template/response.py", line 105, in render
self.content = self.rendered_content

File "/root/.local/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
return template.render(context, self._request)

File "/root/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 170, in render
return self._render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
return self.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
bit = node.render_annotated(context)

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 214, in render
nodelist.append(node.render_annotated(context))

File "/root/.local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
return self.render(context)

File "/root/.local/lib/python3.10/site-packages/django/template/library.py", line 192, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/home/inventree/InvenTree/part/templatetags/inventree_extras.py", line 542, in object_link
ref_url = reverse(url_name, kwargs={'pk': pk})

File "/root/.local/lib/python3.10/site-packages/django/urls/base.py", line 86, in reverse
return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)

File "/root/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
raise NoReverseMatch(msg)

django.urls.exceptions.NoReverseMatch: Reverse for 'build-detail' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['build/(?P<pk>[0-9]+)/.*$']
```

**Comment by SchrodingersGat** [comment]
@JambonLeVrai thanks for reporting, this is an edge case which we have not considered
