### ISSUE TITLE
Quick Script install failure on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by niccolodevries** [inventree/InvenTree#6148]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When doing a new install using the quick script installer on a Ubuntu 20.04 LTS droplet on Digital ocean the install completes successfully but the Inventree service does not work with the Nginx proxy returning 502.

A similar issue is mentioned in this discussion: https://github.com/inventree/InvenTree/discussions/6109. But after running the mentioned "inventree run cli update" the issue does not seem to be fixed. 

### Steps to Reproduce

0. Create a new droplet with Ubuntu 20.04 LTS on Digital ocean
1. Update all packages using apt
2. Run the one liner: "wget -qO install.sh https://get.inventree.org && bash install.sh"

### Relevant log output

```bash
Inventree logs after running the installer:
Jan 02 19:13:07 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: Stopped inventree-worker-1.service.
Jan 02 19:13:07 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: Started inventree-worker-1.service.
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: Traceback (most recent call last):
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]:   File "/opt/inventree/InvenTree/manage.py", line 9, in <module>
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]:     from django.core.management import execute_from_command_line
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: ModuleNotFoundError: No module named 'django'
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: During handling of the above exception, another exception occurred:
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: Traceback (most recent call last):
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]:   File "/opt/inventree/InvenTree/manage.py", line 15, in <module>
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]:     import django  # noqa: F401
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: ModuleNotFoundError: No module named 'django'
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: During handling of the above exception, another exception occurred:
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: Traceback (most recent call last):
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]:   File "/opt/inventree/InvenTree/manage.py", line 17, in <module>
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]:     raise ImportError(
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 inventree-worker-1.service[5591]: ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH >
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: inventree-worker-1.service: Main process exited, code=exited, status=1/FAILURE
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: inventree-worker-1.service: Failed with result 'exit-code'.
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: inventree-worker-1.service: Scheduled restart job, restart counter is at 7.
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: Stopped inventree-worker-1.service.
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: inventree-worker-1.service: Start request repeated too quickly.
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: inventree-worker-1.service: Failed with result 'exit-code'.
Jan 02 19:13:08 ubuntu-s-1vcpu-1gb-ams3-01 systemd[1]: Failed to start inventree-worker-1.service
```

**Comment by niccolodevries** [comment]
The issue seems to be already fixed in the main / development branch.
