### ISSUE TITLE
`invoke restore` fails

### ISSUE THREAD

**Issue by NidasioAlberto** [inventree/InvenTree#6377]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I was trying to restore a backup of my InvenTree installation but `invoke update` fails. The backup I'm trying to restore was made this morning.

### Steps to Reproduce

1. Prepare a directory with the `config.yaml`, `.env` and `docker-compose.yml` files
2. Run `docker compose run --rm server invoke update` to create the database tables
3. Remove the generate backup data and put the backup I want to restore in the `backup` directory
4. Run `docker compose run --rm server invoke restore`

### Expected behaviour

The bakup is restored

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

0.13.4

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Loading config file : /home/inventree/data/config.yaml
Restoring InvenTree database...
Python version 3.10.13 - /usr/local/bin/python3
/root/.local/lib/python3.10/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Finding latest backup
Restoring backup for database 'default' and server 'None'
Restoring: default-931c8db457e2-2024-01-31-010007.psql.bin.gz
Restore tempfile created: 936.1 KiB
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/management/commands/dbrestore.py", line 68, in handle
    self._restore_backup()
  File "/root/.local/lib/python3.10/site-packages/dbbackup/management/commands/dbrestore.py", line 118, in _restore_backup
    self.connector.restore_dump(input_file)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/db/base.py", line 105, in restore_dump
    return self._restore_dump(dump)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/db/postgresql.py", line 124, in _restore_dump
    stdout, stderr = self.run_command(cmd, stdin=dump, env=self.restore_env)
  File "/root/.local/lib/python3.10/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_restore --dbname=postgresql://webmaster:<db password>@db:5432/inventree --single-transaction --clean
pg_restore: error: could not execute query: ERROR:  relation "public.authtoken_token" does not exist
Command was: ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id;
```

**Comment by NidasioAlberto** [comment]
I did not mention that I used Google SSO. Also the `config.yaml`, `.env`are the same as were before

**Comment by SchrodingersGat** [comment]
You say that `invoke update` fails but you have posted log from `invoke restore`. Did the update process work? Can you please post the log from `invoke update` also

**Comment by SchrodingersGat** [comment]
Closing due to lack of feedback

**Comment by simoneamadori** [comment]
I have a similar problem, I'm trying to restore a backup but the problem is this:
```
root@srvgitlab:/home/inventree/docker# docker compose run inventree-server invoke restore --db-file=default-7c698afcf95c-2024-05-24-082119.psql.bin.gz
[+] Creating 1/0
 ✔ Container inventree-db  Running                                                                                              0.0s
Loading config file : /home/inventree/data/config.yaml
Restoring InvenTree database
Python version 3.11.9 - /usr/local/bin/python3
/root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
usage: manage.py dbrestore [-h] [--noinput] [-q] [-d DATABASE]
                           [-i INPUT_FILENAME] [-I INPUT_PATH] [-s SERVERNAME]
                           [-c] [-p PASSPHRASE] [-z] [--version]
                           [-v {0,1,2,3}] [--settings SETTINGS]
                           [--pythonpath PYTHONPATH] [--traceback]
                           [--no-color] [--force-color] [--skip-checks]
manage.py dbrestore: error: unrecognized arguments: --no-input
root@srvgitlab:/home/inventree/docker#
```
the problem is that the --no-input is used instead of the --noinput

How could be  fixed?

Thanks

**Comment by SchrodingersGat** [comment]
@simoneamadori your problem is a different one, it looks like we have a typo in the `invoke` call. I'll look into issuing a fix. For now you could always run the command manually, but you would need to run from a shell inside the docker container
