### ISSUE TITLE
Raspberry Pi Install issue with DB

### ISSUE THREAD

**Issue by reimannsum** [inventree/InvenTree#6385]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [ ] Docker Production
- [X] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

When I try to invoke update to instantiate the DB I get an error, probably because I had to use mariaDB as mysql would not install

### Steps to Reproduce

Fresh install of rasbian bullseye on a RPi2

followed the guide [Here](https://docs.inventree.org/en/latest/start/install/) https://docs.inventree.org/en/latest/start/install/ getting everything installed. I have crashed the invoke update 3 times, the first was an invoke version issue because I was not in the inventree user, the next was because I didn't have a config file, this last one is the one where it is mad about the DB

### Relevant log output

```bash
******* When installing a DB ******
pi@inventree:~ $ sudo apt-get install mysql-server libmysqlclient-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mariadb-server-10.0

Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb-dev-compat libmariadb-dev

E: Package 'mysql-server' has no installation candidate
E: Package 'libmysqlclient-dev' has no installation candidate
pi@inventree:~ $ sudo apt-get install mariadb-server libmariadb-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  galera-4 gawk libaio1 libcgi-fast-perl libcgi-pm-perl libclone-perl libconfig-inifiles-perl
  libdbd-mariadb-perl libdbi-perl libencode-locale-perl libfcgi-bin libfcgi-perl libfcgi0ldbl
  libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl
  libio-html-perl liblwp-mediatypes-perl libmariadb3 libsigsegv2 libsnappy1v5 libssl-dev
  libterm-readkey-perl libtimedate-perl liburi-perl lsof mariadb-client-10.5 mariadb-client-core-10.5
  mariadb-common mariadb-server-10.5 mariadb-server-core-10.5 mysql-common socat
Suggested packages:
  gawk-doc libmldbm-perl libnet-daemon-perl libsql-statement-perl libdata-dump-perl
  libipc-sharedcache-perl libssl-doc libwww-perl mailx mariadb-test
The following NEW packages will be installed:
  galera-4 gawk libaio1 libcgi-fast-perl libcgi-pm-perl libclone-perl libconfig-inifiles-perl
  libdbd-mariadb-perl libdbi-perl libencode-locale-perl libfcgi-bin libfcgi-perl libfcgi0ldbl
  libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl libhttp-message-perl
  libio-html-perl liblwp-mediatypes-perl libmariadb-dev libmariadb3 libsigsegv2 libsnappy1v5 libssl-dev
  libterm-readkey-perl libtimedate-perl liburi-perl lsof mariadb-client-10.5 mariadb-client-core-10.5
  mariadb-common mariadb-server mariadb-server-10.5 mariadb-server-core-10.5 mysql-common socat
0 upgraded, 37 newly installed, 0 to remove and 9 not upgraded.
Need to get 17.1 MB of archives.
After this operation, 150 MB of additional disk space will be used.
Do you want to continue? [Y/n] y

*******************



***** when running invoke update
Requirement already satisfied: setuptools in /home/inventree/env/lib/python3.9/site-packages (from django-money==3.2.0->-r requirements.txt (line 128)) (69.0.3)
Backing up InvenTree database...
2024-02-01 16:41:47,504 WARNING Plugin configuration file does not exist - creating default file
Python version 3.9.2 - /home/inventree/env/bin/python3
Traceback (most recent call last):
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/inventree/src/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/home/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/inventree/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/inventree/env/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/inventree/env/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inventree/src/InvenTree/build/models.py", line 8, in <module>
    from django.contrib.auth.models import User
  File "/home/inventree/env/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/inventree/env/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/inventree/env/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/home/inventree/env/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/inventree/env/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
(env) inventree@inventree:~/src $
```

**Comment by reimannsum** [comment]
this is the history of commands for the root user
`4  sudo apt-get update
    5  sudo apt-get install     python3 python3-dev python3-pip python3-invoke python3-venv     git gcc g++ gettext gnupg     poppler-utils libpango-1.0-0 libpangoft2-1.0-0     libjpeg-dev webp
    6  sudo useradd -m -d /home/inventree -s /bin/bash inventree
    7  sudo passwd inventree
    8  sudo su inventree
    9  sudo apt install python3-pip libpango-1.0-0 libpangoft2-1.0-0
   10  sudo su inventree
   11  sudo apt-get install mysql-server libmysqlclient-dev
   12  sudo apt-get install mariadb-server-10.0 libmariadb-dev
   13  sudo apt-get
   14  sudo apt-get check
   15  sudo apt-get clean
   16  sudo apt-get install libmariadb-dev
   17  sudo apt-get install mariadb-server libmariadb-dev
   18  sudo mysql -u root
`
And this is the history of the inventree user
`(env) inventree@inventree:~/src $ history
    1  cd
    2  git clone https://github.com/inventree/inventree src
    3  mkdir media static backups
    4  ll
    5  ls
    6  python3 -m venv env
    7  ls -la
    8  nano .bashrc
    9  source
   10  source .bashrc
   11  pip install weasyprint
   12  apt install python3-pip libpango-1.0-0 libpangoft2-1.0-0
   13  sudoapt install python3-pip libpango-1.0-0 libpangoft2-1.0-0
   14  sudo apt install python3-pip libpango-1.0-0 libpangoft2-1.0-0
   15  sudo -u pi apt install python3-pip libpango-1.0-0 libpangoft2-1.0-0
   16  cd
   17  nano .bashrc
   18  cd
   19  pip install weasyprint
   20  pip install -U -r src/requirements.txt
   21  pip install -U invoke
   22  invoke update
   23  nano /home/inventree/src/InvenTree/config.yaml
   24  invoke update
   25  history
(env) inventree@inventree:~/src $
`

**Comment by wolflu05** [comment]
Hello, have you also followed these steps? Especially installed the mysqlclient package? https://docs.inventree.org/en/latest/start/install/#install-python-bindings_1

**Comment by reimannsum** [comment]
> Hello, have you also followed these steps? Especially installed the mysqlclient package? https://docs.inventree.org/en/latest/start/install/#install-python-bindings_1

good catch, so I tried that and I got 

```
(env) inventree@inventree:/home/pi $ pip install mysqlclient mariadb
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mysqlclient
  Using cached https://www.piwheels.org/simple/mysqlclient/mysqlclient-2.2.1-cp39-cp39-linux_armv7l.whl (126 kB)
Collecting mariadb
  Using cached mariadb-1.1.9.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 2
  ╰─> [1 lines of output]
      MariaDB Connector/Python requires MariaDB Connector/C >= 3.3.1, found version 3.1.21
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(env) inventree@inventree:/home/pi $

```

**Comment by SchrodingersGat** [comment]
>  MariaDB Connector/Python requires MariaDB Connector/C >= 3.3.1, found version 3.1.21

So, you need to update your installed version of mariadb-connector

**Comment by reimannsum** [comment]
> > MariaDB Connector/Python requires MariaDB Connector/C >= 3.3.1, found version 3.1.21
> 
> So, you need to update your installed version of mariadb-connector

I tried but I can't seem to find it


```
(env) inventree@inventree:~ $ pip install -U mariadb-connector
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement mariadb-connector (from versions: none)
ERROR: No matching distribution found for mariadb-connector
(env) inventree@inventree:~ $ pip install mariadb-connector
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement mariadb-connector (from versions: none)
ERROR: No matching distribution found for mariadb-connector
(env) inventree@inventree:~ $
exit
pi@inventree:~ $ sudo apt install mariadb-connector
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package mariadb-connector
pi@inventree:~ $
```

**Comment by reimannsum** [comment]
@SchrodingersGat

**Comment by SchrodingersGat** [comment]
I am not experienced with installing Mariadb onto a raspberry pi - perhaps the [mariadb docs](https://mariadb.com/docs/server/deploy/) would be a good starting point

**Comment by reimannsum** [comment]
We can close this as it turns out not all of MariaDB is compatible with x32 architecture. So I had to go with postgress, also had to use pendulum 2.1.1 as 3.0 is also not compatible with x32 it seems.
