### ISSUE TITLE
Failed migration on new instance "Table 'inventree.common_inventreesetting' doesn't exist"

### ISSUE THREAD

**Issue by Zeigren** [inventree/InvenTree#647]
When running migrations on a new instance `common>apps.py` throws an error causing the migration to fail.

Here's the specific error:
`django.db.utils.ProgrammingError: (1146, "Table 'inventree.common_inventreesetting' doesn't exist")`

The quick fix is to remove `OperationalError` from line 46 in `common>apps.py`, run the migration, then add it back.

**Comment by SchrodingersGat** [comment]
Can you please post the full error trace? I have just tried to replicate this by creating a clean instance, and could not get the error you are seeing.

**Comment by Zeigren** [comment]
<details>
<summary>Log</summary>
make: Entering directory '/usr/src/app' 

cd InvenTree && python3 manage.py makemigrations 

DIA_ROOT: /usr/src/media 

Traceback (most recent call last): 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute 

 return self.cursor.execute(sql, params) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute 

 return self.cursor.execute(query, args) 

 File "/opt/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute 

 res = self._query(query) 

 File "/opt/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query 

 db.query(q) 

 File "/opt/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query 

 _mysql.connection.query(self, query) 

MySQLdb._exceptions.ProgrammingError: (1146, "Table 'inventree.common_inventreesetting' doesn't exist") 



The above exception was the direct cause of the following exception: 



Traceback (most recent call last): 

 File "manage.py", line 22, in <module> 

 execute_from_command_line(sys.argv) 

 File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line 

 utility.execute() 

 File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute 

 django.setup() 

 File "/opt/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup 

 apps.populate(settings.INSTALLED_APPS) 

 File "/opt/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate 

 app_config.ready() 

 File "/usr/src/app/InvenTree/common/apps.py", line 14, in ready 

 self.populate_default_settings() 

 File "/usr/src/app/InvenTree/common/apps.py", line 36, in populate_default_settings 

 if not InvenTreeSetting.objects.filter(key=key).exists(): 

 File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 766, in exists 

 return self.query.has_results(using=self.db) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 522, in has_results 

 return compiler.has_results() 

 File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1103, in has_results 

 return bool(self.execute_sql(SINGLE)) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql 

 cursor.execute(sql, params) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute 

 return super().execute(sql, params) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute 

 return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers 

 return executor(sql, params, many, context) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute 

 return self.cursor.execute(sql, params) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__ 

 raise dj_exc_value.with_traceback(traceback) from exc_value 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute 

 return self.cursor.execute(sql, params) 

 File "/opt/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute 

 return self.cursor.execute(query, args) 

 File "/opt/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute 

 res = self._query(query) 

 File "/opt/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query 

 db.query(q) 

 File "/opt/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query 

 _mysql.connection.query(self, query) 

django.db.utils.ProgrammingError: (1146, "Table 'inventree.common_inventreesetting' doesn't exist") 

make: *** [Makefile:14: migrate] Error 1
</details>

**Comment by SchrodingersGat** [comment]
@Zeigren I'm unable to test your configuration right now, but can you please test the following:

In `/common/apps.py`:

1. Change line *2* to ```from django.db.utils import OperationalError, ProgrammingError```
1. Change line *46* to ```            except (OperationalError, ProgrammingError):```

And see if the issue is resolved?

**Comment by Zeigren** [comment]
Hah just tested it, and it worked!
