### ISSUE TITLE
Inventree On Portainer can't execute invoke update

### ISSUE THREAD

**Issue by RedWillDev** [inventree/InvenTree#6628]
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hello, when i click on deploy stack on portainer its says me : 
Loading config file : /home/inventree/data/config.yaml

-c: line 0: gunicorn: not found

and i think its because i need to execute 'invoke update' but in portainer i tried some tricks to do it but not working 

does some one know how can i do it 

thanks for reading and thanks in advance

### Steps to Reproduce

1, open portainer
2, create stack with .env option
3, click on deplay stack
4, open console
5, see errors

### Relevant log output

```bash
Loading config file : /home/inventree/data/config.yaml

-c: line 0: gunicorn: not found
```

**Comment by wolflu05** [comment]
Sorry for the inconvenience with 0.14.0, there is currently a bug with the build of the docker image where we are already working on in #6621 and try to release a new version as soon as possible. For now best is to stay at 0.13.x and do the update when 0.14.1 is released.

**Comment by RedWillDev** [comment]
Thx for your response, but now i have another proble x)



Log viewer settings
Auto-refresh logs
Wrap lines
Display timestamps
Fetch
Search
Lines
Actions

      

    collector.collect(del_query)

  File "/root/.local/lib/python3.10/site-packages/django/db/models/deletion.py", line 243, in collect

    new_objs = self.add(objs, source, nullable,

  File "/root/.local/lib/python3.10/site-packages/django/db/models/deletion.py", line 107, in add

    if not objs:

  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 284, in __bool__

    self._fetch_all()

  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__

    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql

    cursor.execute(sql, params)

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute

    with self.db.wrap_database_errors:

  File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.ProgrammingError: relation "django_q_schedule" does not exist

LINE 1: ...", "django_q_schedule"."intended_date_kwarg" FROM "django_q_...

                                                             ^

Traceback (most recent call last):

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.UndefinedTable: relation "django_q_schedule" does not exist

LINE 1: ...", "django_q_schedule"."intended_date_kwarg" FROM "django_q_...

                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/root/.local/bin/gunicorn", line 8, in <module>

    sys.exit(run())

  File "/root/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run

    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()

  File "/root/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 236, in run

    super().run()

  File "/root/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run

    Arbiter(self).run()

  File "/root/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__

    self.setup(app)

  File "/root/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup

    self.app.wsgi()

  File "/root/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi

    self.callable = self.load()

  File "/root/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

    return self.load_wsgiapp()

  File "/root/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

    return util.import_app(self.app_uri)

  File "/root/.local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app

    mod = importlib.import_module(module)

  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/inventree/InvenTree/InvenTree/wsgi.py", line 15, in <module>

    application = get_wsgi_application()  # pragma: no cover

  File "/root/.local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application

    django.setup(set_prefix=False)

  File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate

    app_config.ready()

  File "/home/inventree/InvenTree/InvenTree/apps.py", line 51, in ready

    self.start_background_tasks()

  File "/home/inventree/InvenTree/InvenTree/apps.py", line 94, in start_background_tasks

    for existing_task in Schedule.objects.all():

  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__

    self._fetch_all()

  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

  File "/root/.local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__

    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

  File "/root/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql

    cursor.execute(sql, params)

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute

    with self.db.wrap_database_errors:

  File "/root/.local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/root/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.ProgrammingError: relation "django_q_schedule" does not exist

LINE 1: ...", "django_q_schedule"."intended_date_kwarg" FROM "django_q_...

**Comment by RedWillDev** [comment]
thx for your response this project is awesome and hope its get bigger

**Comment by RedWillDev** [comment]
i have another problem i use a version of inventree that use nginx and i dont know where to find config file

**Comment by SchrodingersGat** [comment]
@RedWillDev should be fixed now, but the docker images will take some time to build
