### ISSUE TITLE
Error object (ProgrammingError) after update to 0.14.0

### ISSUE THREAD

**Issue by JustusRijke** [inventree/InvenTree#6630]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

After updating from 0.13.3 to 0.14.0 (see #6629), the frontend shows an `Error object` notification. 
It's contents:

Change Error
Error object (12)

Type: `ProgrammingError`
Path: `/api/stock/`
Info:  ```
column stock_stockitemtestresult.template_id does not exist
LINE 1: ...ta", "stock_stockitemtestresult"."stock_item_id", "stock_sto...
^```

When: `March 4, 2024, 8:26 a.m.`

Data:
```
Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)

File "/opt/inventree/env/lib/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
raise ex.with_traceback(None)

psycopg.errors.UndefinedColumn: column stock_stockitemtestresult.template_id does not exist
LINE 1: ...ta", "stock_stockitemtestresult"."stock_item_id", "stock_sto...
^


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/opt/inventree/InvenTree/InvenTree/api.py", line 341, in get
return super().get(request, *args, **kwargs)

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/generics.py", line 239, in get
return self.list(request, *args, **kwargs)

File "/opt/inventree/InvenTree/stock/api.py", line 1055, in list
data = serializer.data

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
ret = super().data

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
self._data = self.to_representation(self.instance)

File "/opt/inventree/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
return [

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 398, in __iter__
self._fetch_all()

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 1883, in _fetch_all
self._prefetch_related_objects()

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 1273, in _prefetch_related_objects
prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 2321, in prefetch_related_objects
obj_list, additional_lookups = prefetch_one_level(

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 2463, in prefetch_one_level
) = prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level))

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 744, in get_prefetch_queryset
for rel_obj in queryset:

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 398, in __iter__
self._fetch_all()

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
self._result_cache = list(self._iterable_class(self))

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
results = compiler.execute_sql(

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
cursor.execute(sql, params)

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
return self._execute_with_wrappers(

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
return executor(sql, params, many, context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value

File "/opt/inventree/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)

File "/opt/inventree/env/lib/python3.9/site-packages/psycopg/cursor.py", line 723, in execute
raise ex.with_traceback(None)

django.db.utils.ProgrammingError: column stock_stockitemtestresult.template_id does not exist
LINE 1: ...ta", "stock_stockitemtestresult"."stock_item_id", "stock_sto...
^
```

```

### Steps to Reproduce

update to 0.14.0

### Expected behaviour

no errors

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.14.0
Django Version: 4.2.10
Commit Hash: f4fd84f5
Commit Date: None
Commit Branch: 0.14.x
stable
Database: postgresql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.10.0-27-amd64-x86_64-with-glibc2.31
Installer: PKG
Target: ubuntu:20.04
Active plugins: []


### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

_No response_

**Comment by SchrodingersGat** [comment]
@JustusRijke thanks for reporting - there was a problem with our docker image compiled for `0.14.0` - see https://github.com/inventree/InvenTree/pull/6621

Currently this is rebuilding, we should have a new image out for `0.14.1` very soon. Then the update procedure should go smoothly (fingers crossed!)

**Comment by JustusRijke** [comment]
Great! Should I run the update with 0.3.3 as a starting point, or is 0.4.0 ok to use?

**Comment by SchrodingersGat** [comment]
I would go from `0.13.3` to `0.14.1` and bypass `0.14.0` entirely

**Comment by JustusRijke** [comment]
Closed, see https://github.com/inventree/InvenTree/issues/6629#issuecomment-1980514108
