### ISSUE TITLE
Issue updating from 0.13.6 to 0.14.1.

### ISSUE THREAD

**Issue by Serious-Dave** [inventree/InvenTree#6645]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When I deployed v0.13.6, I used postgres v15 (initially tried v16, but ironically got the same issue I'm describing here, so rolled back a version and it worked) - apparently I missed #6407. With the update to v0.14, Inventree has pinned postgres to v13 (#6407) and the database backup (and who knows what else - I haven't yet tried to run the whole stack) fails.

 Am I out of luck, or is there a possibility you could bump postgres libs to v15?

### Steps to Reproduce

1. Deploy Inventree Docker Stack using `postgres:15`.
2. Pull new Inventree containers.
3. Run `docker compose run --rm inventree-server invoke update`.

### Expected behaviour

1. Deploy Inventree Docker Stack using `postgres:15` or `postgres:latest`.
2. Pull new Inventree containers.
3. Run `docker compose run --rm inventree-server invoke update` and live happily everly after.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

Obviously, this was the initial Version Information.

# Version Information:
InvenTree-Version: 0.13.6
Django Version: 3.2.23
Commit Hash: 0ab173d
Commit Date: 2024-02-22

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-18-amd64-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Backing Up Database: inventree
CommandConnectorError: Error running:  pg_dump --dbname=postgresql://inventree_user:Of5vZ40P9Sq3gqbhboPi9VdF9LqHunljCE8TcltO7GeSsaD6n6AG6ucIyG3QWYM@inventree-db:5432/inventree --format=custom
pg_dump: error: server version: 15.6 (Debian 15.6-1.pgdg120+2); pg_dump version: 13.14
pg_dump: error: aborting because of server version mismatch

  File "/root/.local/lib/python3.11/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
    self._save_new_backup(database)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 106, in _save_new_backup
    outputfile = self.connector.create_dump()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 92, in create_dump
    return self._create_dump()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/postgresql.py", line 112, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(

Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 93, in handle
    self._save_new_backup(database)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 106, in _save_new_backup
    outputfile = self.connector.create_dump()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 92, in create_dump
    return self._create_dump()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/postgresql.py", line 112, in _create_dump
    stdout, stderr = self.run_command(cmd, env=self.dump_env)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/db/base.py", line 171, in run_command
    raise exceptions.CommandConnectorError(
dbbackup.db.exceptions.CommandConnectorError: Error running:  pg_dump --dbname=postgresql://inventree_user:Of5vZ40P9Sq3gqbhboPi9VdF9LqHunljCE8TcltO7GeSsaD6n6AG6ucIyG3QWYM@inventree-db:5432/inventree --format=custom
pg_dump: error: server version: 15.6 (Debian 15.6-1.pgdg120+2); pg_dump version: 13.14
pg_dump: error: aborting because of server version mismatch
```

**Comment by matmair** [comment]
Not sure this is a bug; officially we target psql14 right now; would have to be determined if we can support more versions without problems.

Not entirely sure why we pinned the client down to 13 - do you have a recollection @SchrodingersGat?

**Comment by Serious-Dave** [comment]
> Not sure this is a bug

Agreed. Apologies - should've amended.

I have mostly come right by doing a manual dump, setting up a v13 db, and reinstating the dump. One issue I'm facing now is 403 errors when creating/updating parts, stock, etc; from the server: `inventree-server  | Forbidden: /api/stock/`. If I can fix this, then I should be alright.

**Comment by matmair** [comment]
this sounds like either CSRF or CORS

**Comment by Serious-Dave** [comment]
Ugh, my `INVENTREE_SITE_URL="..."` didn't have the double quotes. 

Going to close the issue now. 

> Not entirely sure why we pinned the client down to 13 - do you have a recollection @SchrodingersGat?

Would love some info on this, though! Thanks for good work! Cheers

**Comment by SchrodingersGat** [comment]
@Serious-Dave @matmair I do not recall a particular motivation to pin @ `postgresql:13`. We needed to pin the docker container at the *same* version that we run the postgresql libraries in our container - but nothing is stopping us upgrading it.

New issue here: https://github.com/inventree/InvenTree/issues/6648
