### ISSUE TITLE
ALLOWED_HOSTS Error when running Dev Container

### ISSUE THREAD

**Issue by XanderLuciano** [inventree/InvenTree#6870]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I just began getting ALLOWED_HOSTS errors in the dev container for Inventree. Possibly could be a configuration error on my end, I have not investigated my local copy, but I normally do not touch any of the backend code.

### Steps to Reproduce

Clone repo, open in VS Code on windows, connect to container, run server task, attempt to hit any API endpoint in Postman

### Expected behaviour

API Data should return to localhost

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

master

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
*  Executing task: inv server 

Python version 3.11.8 - /home/inventree/dev/venv/bin/python3
/home/inventree/dev/venv/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Waiting for database...
Database connection successful!
Python version 3.11.8 - /home/inventree/dev/venv/bin/python3
Python version 3.11.8 - /home/inventree/dev/venv/bin/python3
/home/inventree/dev/venv/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (2 silenced).
March 27, 2024 - 10:19:41
Django version 4.2.11, using settings 'InvenTree.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/inventree/dev/venv/lib/python3.11/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /api/barcode/
Bad Request: /api/barcode/
[27/Mar/2024 10:20:15] "POST /api/barcode/ HTTP/1.1" 400 92711
```

**Comment by XanderLuciano** [comment]
![image](https://github.com/inventree/InvenTree/assets/13877593/67793415-6178-4876-9d01-0a5bf9165a06)

Attempting to load the Web UI results in an error as well

**Comment by SchrodingersGat** [comment]
@XanderLuciano thanks for reporting - fix incoming in https://github.com/inventree/InvenTree/pull/6871

**Comment by SchrodingersGat** [comment]
Pull latest master and it should work for you again now.

**Comment by XanderLuciano** [comment]
Confirmed working now, thank you!
