### ISSUE TITLE
Error migrating manufacturer

### ISSUE THREAD

**Issue by chschlue** [inventree/InvenTree#717]
`make migrate` fails after merge of #716

Trace after "migration to company object requires user input" and so on.
Python 3.8.2

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/chschlue/.local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/chschlue/inventree/InvenTree/company/migrations/0019_auto_20200413_0642.py", line 262, in associate_manufacturers
    map_part_to_manufacturer(part, idx, part_count)
  File "/home/chschlue/inventree/InvenTree/company/migrations/0019_auto_20200413_0642.py", line 143, in map_part_to_manufacturer
    name = str(part.manufacturer_name)
AttributeError: 'SupplierPart' object has no attribute 'manufacturer_name'
make: *** [Makefile:15: migrate] Error 1
```

**Comment by SchrodingersGat** [comment]
@chschlue oops, I've worked out what's going on. I had a test database which I was using for the migrations but this fell through the cracks. I didn't know that this particular error could happen, but it makes a lot of sense in hindsight. Learned something new!

**Comment by SchrodingersGat** [comment]
Please pull down and try again. Hopefully this has fixed the issue for you.

If it does work, please let me know how the manual remapping of manufacturers goes for you.

**Comment by SchrodingersGat** [comment]
Actually please wait for a little bit, there might be another bug now... :|

**Comment by chschlue** [comment]
Too late...

**Comment by chschlue** [comment]
Seems to be working at first glance.

Heuristics are a little strange...
```
Select an option from the list below:
0) - Create new manufacturer 'Finder'

1) - Use manufacturer 'Infineon'
```

**Comment by SchrodingersGat** [comment]
Ok, wait for https://github.com/inventree/InvenTree/pull/720 to be merged before you run, otherwise the migration will "work" but the data won' be saved properly!

If you're midway through the migration just press "Ctrl-C" to cancel it.

**Comment by SchrodingersGat** [comment]
> Heuristics are a little strange...

It uses fuzzy match to try and "guess" which manufacturer you might mean. The match threshold is set pretty low so there may be some spurious matches.

**Comment by chschlue** [comment]
Suppose I already finished migration and ran. What then? :)

**Comment by SchrodingersGat** [comment]
Give me a few minutes ;)

**Comment by chschlue** [comment]
Just asking, it's not a production system so I don't actually lose much.

**Comment by SchrodingersGat** [comment]
Hypothetically the migration should have a "rollback" feature which performs the opposite operation. However I just found a separate bug in that. I need to fix it anyway, so I'll push something soon.

**Comment by SchrodingersGat** [comment]
Ok, after grabbing latest commit, you have two options:

1. Revert to a backup point on the database and simply run `make migrate`. The migrations should apply properly now.

2. Run the following sequence (not guaranteed if the initial migration has mucked up the data)

```
cd InvenTree
python manage.py migrate company 0017
python manage.py migrate
```

Please let me know how you go in either case.

**Comment by a7hybnj2** [comment]
Should I wait a bit to update? Can I get an 'ALL OKAY' when its good? I guess I will be doubly sure to do a backup before update this time.

**Comment by SchrodingersGat** [comment]
@a7hybnj2 what sort of database are you running? sqlite? mysql?

I am pretty sure the migration is working correctly now, but I'd recommend a database backup before updating, just to be sure.

**Comment by chschlue** [comment]
Reverse migration worked.

How is DB restore supposed to be done, BTW? I only used "backup" before, hoping for "restore" to be implemented by the time I need it ;)

**Comment by SchrodingersGat** [comment]
The "restore" functionality needs some work, I fear it depends on the particular database installation. Currently it is "left to the user" to manage sensible backup strategies...

In the long term I'd like to integrate a simpler and "safer" solution...

**Comment by a7hybnj2** [comment]
😬 I have been zfs snap shot-ting my whole InvenTree jail in the event I need to roll back.
