### ISSUE TITLE
File and command not found when upgrading

### ISSUE THREAD

**Issue by StormTrooper** [inventree/InvenTree#7236]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I've installed a new Ubuntu 20.04 server and used the install script to install Inventree using a mysql database. Yesterday I installed 0.15.0 and today upgraded to 0.15.1

The upgrade was successful however I noticed 2 errors in the upgrade when it was applied.

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/inventree/.github/requirements.txt'
/opt/inventree/contrib/packager.io/functions.sh: line 96: jc: command not found
```

There is no .github folder under /opt/inventree

Is jc also a requirement?

### Steps to Reproduce

Install 0.15.0 on Ubuntu 20.04 using the install script. 

Upgrade to 0.15.1

### Expected behaviour

Script is trying to load requirements.txt from /opt/inventree/.github/requirements.txt
On my installation the file is at /opt/inventree/requirements.txt

### Deployment Method

- [ ] Docker
- [X] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.1
Django Version: 4.2.12

Database: mysql
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-5.4.0-182-generic-x86_64-with-glibc2.31
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
user@inventree-clone:/etc/apt/sources.list.d$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libpython3.9-minimal libpython3.9-stdlib libpython3.9 python3.9
  python3.9-dev python3.9-minimal libpython3.9-dev python3.9-venv
Learn more about Ubuntu Pro at https://ubuntu.com/pro
The following packages will be upgraded:
  inventree
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.5 MB of archives.
After this operation, 4,096 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.packager.io/srv/deb/inventree/InvenTree/0.15.x/ubuntu 20.04/main amd64 inventree amd64 0.15.1-1715729109.be3b22ce.focal [64.5 MB]
Fetched 64.5 MB in 6s (10.1 MB/s)
(Reading database ... 89097 files and directories currently installed.)
Preparing to unpack .../inventree_0.15.1-1715729109.be3b22ce.focal_amd64.deb ...
Unpacking inventree (0.15.1-1715729109.be3b22ce.focal) over (0.15.0-1715695991.7df92aad.focal) ...
Setting up inventree (0.15.1-1715729109.be3b22ce.focal) ...
# Setting base environment variables
# Using existing config file: /etc/inventree/config.yaml
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/inventree/.github/requirements.txt'
/opt/inventree/contrib/packager.io/functions.sh: line 96: jc: command not found
# Collected environment variables:
#    INVENTREE_MEDIA_ROOT=
#    INVENTREE_STATIC_ROOT=
#    INVENTREE_BACKUP_DIR=
#    INVENTREE_PLUGINS_ENABLED=
#    INVENTREE_PLUGIN_FILE=
#    INVENTREE_SECRET_KEY_FILE=
#    INVENTREE_DB_ENGINE=
#    INVENTREE_DB_NAME=
#    INVENTREE_DB_USER=
#    INVENTREE_DB_HOST=
#    INVENTREE_DB_PORT=
# Getting the IP address of the server via web service
IP address is [removed]
# Setting up python environment
Requirement already satisfied: invoke in ./env/lib/python3.9/site-packages (2.2.0)
Requirement already satisfied: wheel in ./env/lib/python3.9/site-packages (0.43.0)
# Stopping nginx
# Setting up nginx to /etc/nginx/sites-enabled/inventree.conf
# Starting nginx
# (Re)creating init scripts
Nothing to do.
Nothing to do.
# Enabling InvenTree on boot
# Admin data already exists - skipping
# Stopping InvenTree
# Updating InvenTree
Requirement already satisfied: wheel in ./env/lib/python3.9/site-packages (0.43.0)
# inv update| Installing required python packages from 'src/backend/requirements.txt'
# inv update| Requirement already satisfied: pip in ./env/lib/python3.9/site-packages (24.0)
# inv update| Requirement already satisfied: setuptools in ./env/lib/python3.9/site-packages (69.5.1)
# inv update| Requirement already satisfied: asgiref==3.8.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 3)) (3.8.1)
# inv update| Requirement already satisfied: async-timeout==4.0.3 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 9)) (4.0.3)
# inv update| Requirement already satisfied: attrs==23.2.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 13)) (23.2.0)
# inv update| Requirement already satisfied: babel==2.15.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 19)) (2.15.0)
# inv update| Requirement already satisfied: bleach==6.1.0 in ./env/lib/python3.9/site-packages (from bleach[css]==6.1.0->-r src/backend/requirements.txt (line 23)) (6.1.0)
# inv update| Requirement already satisfied: brotli==1.1.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 27)) (1.1.0)
# inv update| Requirement already satisfied: certifi==2024.2.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 112)) (2024.2.2)
# inv update| Requirement already satisfied: cffi==1.16.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 118)) (1.16.0)
# inv update| Requirement already satisfied: charset-normalizer==3.3.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 174)) (3.3.2)
# inv update| Requirement already satisfied: coreapi==2.3.3 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 266)) (2.3.3)
# inv update| Requirement already satisfied: coreschema==0.0.4 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 269)) (0.0.4)
# inv update| Requirement already satisfied: cryptography==42.0.7 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 273)) (42.0.7)
# inv update| Requirement already satisfied: cssselect2==0.7.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 309)) (0.7.0)
# inv update| Requirement already satisfied: defusedxml==0.7.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 313)) (0.7.1)
# inv update| Requirement already satisfied: deprecated==1.2.14 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 319)) (1.2.14)
# inv update| Requirement already satisfied: diff-match-patch==20230430 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 326)) (20230430)
# inv update| Requirement already satisfied: dj-rest-auth==6.0.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 330)) (6.0.0)
# inv update| Requirement already satisfied: django==4.2.12 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 332)) (4.2.12)
# inv update| Requirement already satisfied: django-allauth==0.61.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 366)) (0.61.1)
# inv update| Requirement already satisfied: django-allauth-2fa==0.11.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 369)) (0.11.1)
# inv update| Requirement already satisfied: django-cleanup==8.1.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 372)) (8.1.0)
# inv update| Requirement already satisfied: django-cors-headers==4.3.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 375)) (4.3.1)
# inv update| Requirement already satisfied: django-crispy-forms==1.14.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 378)) (1.14.0)
# inv update| Requirement already satisfied: django-dbbackup==4.1.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 381)) (4.1.0)
# inv update| Requirement already satisfied: django-error-report-2==0.4.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 384)) (0.4.2)
# inv update| Requirement already satisfied: django-filter==24.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 387)) (24.2)
# inv update| Requirement already satisfied: django-flags==5.0.13 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 390)) (5.0.13)
# inv update| Requirement already satisfied: django-formtools==2.5.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 393)) (2.5.1)
# inv update| Requirement already satisfied: django-ical==1.9.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 396)) (1.9.2)
# inv update| Requirement already satisfied: django-import-export==3.3.7 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 399)) (3.3.7)
# inv update| Requirement already satisfied: django-js-asset==2.2.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 402)) (2.2.0)
# inv update| Requirement already satisfied: django-maintenance-mode==0.21.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 406)) (0.21.1)
# inv update| Requirement already satisfied: django-markdownify==0.9.3 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 409)) (0.9.3)
# inv update| Requirement already satisfied: django-money==3.2.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 412)) (3.2.0)
# inv update| Requirement already satisfied: django-mptt==0.16.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 415)) (0.16.0)
# inv update| Requirement already satisfied: django-otp==1.5.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 418)) (1.5.0)
# inv update| Requirement already satisfied: django-picklefield==3.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 422)) (3.2)
# inv update| Requirement already satisfied: django-q-sentry==0.1.6 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 426)) (0.1.6)
# inv update| Requirement already satisfied: django-q2==1.6.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 428)) (1.6.2)
# inv update| Requirement already satisfied: django-recurrence==1.11.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 431)) (1.11.1)
# inv update| Requirement already satisfied: django-redis==5.4.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 435)) (5.4.0)
# inv update| Requirement already satisfied: django-sesame==3.2.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 438)) (3.2.2)
# inv update| Requirement already satisfied: django-sql-utils==0.7.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 441)) (0.7.0)
# inv update| Requirement already satisfied: django-sslserver==0.22 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 444)) (0.22)
# inv update| Requirement already satisfied: django-stdimage==6.0.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 446)) (6.0.2)
# inv update| Requirement already satisfied: django-taggit==5.0.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 449)) (5.0.1)
# inv update| Requirement already satisfied: django-user-sessions==2.0.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 452)) (2.0.0)
# inv update| Requirement already satisfied: django-weasyprint==2.3.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 455)) (2.3.0)
# inv update| Requirement already satisfied: django-xforwardedfor-middleware==2.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 458)) (2.0)
# inv update| Requirement already satisfied: djangorestframework==3.14.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 460)) (3.14.0)
# inv update| Requirement already satisfied: djangorestframework-simplejwt==5.3.1 in ./env/lib/python3.9/site-packages (from djangorestframework-simplejwt[crypto]==5.3.1->-r src/backend/requirements.txt (line 467))
(5.3.1)
# inv update| Requirement already satisfied: drf-spectacular==0.27.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 470)) (0.27.2)
# inv update| Requirement already satisfied: dulwich==0.22.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 473)) (0.22.1)
# inv update| Requirement already satisfied: et-xmlfile==1.1.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 521)) (1.1.0)
# inv update| Requirement already satisfied: feedparser==6.0.11 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 525)) (6.0.11)
# inv update| Requirement already satisfied: fonttools==4.51.0 in ./env/lib/python3.9/site-packages (from fonttools[woff]==4.51.0->-r src/backend/requirements.txt (line 528)) (4.51.0)
# inv update| Requirement already satisfied: googleapis-common-protos==1.63.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 572)) (1.63.0)
# inv update| Requirement already satisfied: grpcio==1.63.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 578)) (1.63.0)
# inv update| Requirement already satisfied: gunicorn==22.0.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 626)) (22.0.0)
# inv update| Requirement already satisfied: html5lib==1.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 629)) (1.1)
# inv update| Requirement already satisfied: icalendar==5.0.12 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 633)) (5.0.12)
# inv update| Requirement already satisfied: idna==3.7 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 637)) (3.7)
# inv update| Requirement already satisfied: importlib-metadata==7.0.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 641)) (7.0.0)
# inv update| Requirement already satisfied: inflection==0.5.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 648)) (0.5.1)
# inv update| Requirement already satisfied: itypes==1.2.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 652)) (1.2.0)
# inv update| Requirement already satisfied: jinja2==3.1.4 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 656)) (3.1.4)
# inv update| Requirement already satisfied: jsonschema==4.22.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 660)) (4.22.0)
# inv update| Requirement already satisfied: jsonschema-specifications==2023.12.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 664)) (2023.12.1)
# inv update| Requirement already satisfied: markdown==3.6 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 668)) (3.6)
# inv update| Requirement already satisfied: markuppy==1.14 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 672)) (1.14)
# inv update| Requirement already satisfied: markupsafe==2.1.5 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 675)) (2.1.5)
# inv update| Requirement already satisfied: oauthlib==3.2.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 737)) (3.2.2)
# inv update| Requirement already satisfied: odfpy==1.4.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 741)) (1.4.1)
# inv update| Requirement already satisfied: openpyxl==3.1.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 744)) (3.1.2)
# inv update| Requirement already satisfied: opentelemetry-api==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 748)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-exporter-otlp==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 760)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 763)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 769)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-exporter-otlp-proto-http==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 773)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-instrumentation==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 777)) (0.45b0)
# inv update| Requirement already satisfied: opentelemetry-instrumentation-django==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 785)) (0.45b0)
# inv update| Requirement already satisfied: opentelemetry-instrumentation-redis==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 788)) (0.45b0)
# inv update| Requirement already satisfied: opentelemetry-instrumentation-requests==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 791)) (0.45b0)
# inv update| Requirement already satisfied: opentelemetry-instrumentation-wsgi==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 794)) (0.45b0)
# inv update| Requirement already satisfied: opentelemetry-proto==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 798)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-sdk==1.24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 805)) (1.24.0)
# inv update| Requirement already satisfied: opentelemetry-semantic-conventions==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 811)) (0.45b0)
# inv update| Requirement already satisfied: opentelemetry-util-http==0.45b0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 820)) (0.45b0)
# inv update| Requirement already satisfied: packaging==24.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 827)) (24.0)
# inv update| Requirement already satisfied: pdf2image==1.17.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 831)) (1.17.0)
# inv update| Requirement already satisfied: pillow==10.3.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 834)) (10.3.0)
# inv update| Requirement already satisfied: pint==0.21 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 910)) (0.21)
# inv update| Requirement already satisfied: pip-licenses==4.4.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 913)) (4.4.0)
# inv update| Requirement already satisfied: prettytable==3.10.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 916)) (3.10.0)
# inv update| Requirement already satisfied: protobuf==4.25.3 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 920)) (4.25.3)
# inv update| Requirement already satisfied: py-moneyed==3.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 935)) (3.0)
# inv update| Requirement already satisfied: pycparser==2.22 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 939)) (2.22)
# inv update| Requirement already satisfied: pydyf==0.10.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 943)) (0.10.0)
# inv update| Requirement already satisfied: pyjwt==2.8.0 in ./env/lib/python3.9/site-packages (from pyjwt[crypto]==2.8.0->-r src/backend/requirements.txt (line 947)) (2.8.0)
# inv update| Requirement already satisfied: pyphen==0.15.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 953)) (0.15.0)
# inv update| Requirement already satisfied: pypng==0.20220715.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 957)) (0.20220715.0)
# inv update| Requirement already satisfied: python-barcode==0.15.1 in ./env/lib/python3.9/site-packages (from python-barcode[images]==0.15.1->-r src/backend/requirements.txt (line 961)) (0.15.1)
# inv update| Requirement already satisfied: python-dateutil==2.9.0.post0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 964)) (2.9.0.post0)
# inv update| Requirement already satisfied: python-dotenv==1.0.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 970)) (1.0.1)
# inv update| Requirement already satisfied: python-fsutil==0.14.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 973)) (0.14.1)
# inv update| Requirement already satisfied: python3-openid==3.2.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 977)) (3.2.0)
# inv update| Requirement already satisfied: pytz==2024.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 981)) (2024.1)
# inv update| Requirement already satisfied: pyyaml==6.0.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 988)) (6.0.1)
# inv update| Requirement already satisfied: qrcode==7.4.2 in ./env/lib/python3.9/site-packages (from qrcode[pil]==7.4.2->-r src/backend/requirements.txt (line 1043)) (7.4.2)
# inv update| Requirement already satisfied: rapidfuzz==3.9.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1047)) (3.9.0)
# inv update| Requirement already satisfied: redis==5.0.4 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1138)) (5.0.4)
# inv update| Requirement already satisfied: referencing==0.35.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1142)) (0.35.1)
# inv update| Requirement already satisfied: regex==2024.4.28 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1148)) (2024.4.28)
# inv update| Requirement already satisfied: requests==2.31.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1228)) (2.31.0)
# inv update| Requirement already satisfied: requests-oauthlib==2.0.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1236)) (2.0.0)
# inv update| Requirement already satisfied: rpds-py==0.18.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1240)) (0.18.1)
# inv update| Requirement already satisfied: sentry-sdk==2.1.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1343)) (2.1.1)
# inv update| Requirement already satisfied: setuptools==69.5.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1347)) (69.5.1)
# inv update| Requirement already satisfied: sgmllib3k==1.0.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1353)) (1.0.0)
# inv update| Requirement already satisfied: six==1.16.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1356)) (1.16.0)
# inv update| Requirement already satisfied: sqlparse==0.5.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1363)) (0.5.0)
# inv update| Requirement already satisfied: tablib==3.5.0 in ./env/lib/python3.9/site-packages (from tablib[html,ods,xls,xlsx,yaml]==3.5.0->-r src/backend/requirements.txt (line 1369)) (3.5.0)
# inv update| Requirement already satisfied: tinycss2==1.2.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1373)) (1.2.1)
# Traceback (most recent call last):
  File "/opt/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/opt/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/inventree/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/inventree/env/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/inventree/src/backend/InvenTree/InvenTree/settings.py", line 124, in <module>
    STATIC_ROOT = config.get_static_dir()
  File "/opt/inventree/src/backend/InvenTree/InvenTree/config.py", line 261, in get_static_dir
    raise FileNotFoundError('INVENTREE_STATIC_ROOT not specified')
FileNotFoundError: INVENTREE_STATIC_ROOT not specified
inv update| Requirement already satisfied: typing-extensions==4.11.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1380)) (4.11.0)
# inv update| Requirement already satisfied: uritemplate==4.1.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1389)) (4.1.1)
# inv update| Requirement already satisfied: urllib3==2.2.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1395)) (2.2.1)
# inv update| Requirement already satisfied: wcwidth==0.2.13 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1402)) (0.2.13)
# inv update| Requirement already satisfied: weasyprint==61.2 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1406)) (61.2)
# inv update| Requirement already satisfied: webencodings==0.5.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1410)) (0.5.1)
# inv update| Requirement already satisfied: whitenoise==6.6.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1418)) (6.6.0)
# inv update| Requirement already satisfied: wrapt==1.16.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1421)) (1.16.0)
# inv update| Requirement already satisfied: xlrd==2.0.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1496)) (2.0.1)
# inv update| Requirement already satisfied: xlwt==1.3.0 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1500)) (1.3.0)
# inv update| Requirement already satisfied: zipp==3.18.1 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1504)) (3.18.1)
# inv update| Requirement already satisfied: zopfli==0.2.3 in ./env/lib/python3.9/site-packages (from -r src/backend/requirements.txt (line 1508)) (0.2.3)
# inv update| Installing plugin packages from '/etc/inventree/plugins.txt'
# inv update| Backing up InvenTree database...
# inv update| Python version 3.9.5 - /opt/inventree/env/bin/python3
# Set permissions for data dir and media: /opt/inventree/data
# Starting InvenTree
####################################################################################
This InvenTree install uses nginx, the settings for the webserver can be found in
/etc/nginx/sites-enabled/inventree.conf
```

**Comment by SchrodingersGat** [comment]
@matmair seems similar to yesterday's docker issue. Any insights here?

**Comment by SchrodingersGat** [comment]
Ref: https://github.com/inventree/InvenTree/discussions/7336

**Comment by matmair** [comment]
@StormTrooper can you confirm this can be closed after the recent release?

**Comment by StormTrooper** [comment]
Closing issue. Worked fine after the last upgrade.
