### ISSUE TITLE
Docker Install - Ensure that REDIS is not enabled in .env during DB Initialization

### ISSUE THREAD

**Issue by yodaphone** [inventree/InvenTree#7385]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When installing via Docker Compose, if the REDIS variables are enabled in `.env` file during the Initial DB Setup, the setup errors out & the fails. The documentation must make it clear NOT to enable REDIS cache before the DB Initialization is completed

When i moved my docker compose, .env & Caddyfile to another server, it failed to build & thats how I found out. I rebuilt the VM and when I disabled it in the `.env` file

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error -3 connecting to inventree-cache:6379. Try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/root/.local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/inventree/src/backend/InvenTree/InvenTree/apps.py", line 59, in ready
    InvenTree.tasks.offload_task(InvenTree.tasks.check_for_migrations)
  File "/home/inventree/src/backend/InvenTree/InvenTree/tasks.py", line 208, in offload_task
    if force_async or (is_worker_running() and not force_sync):
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/src/backend/InvenTree/InvenTree/status.py", line 21, in is_worker_running
    clusters = Stat.get_all()
               ^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_q/status.py", line 109, in get_all
    packs = broker.get_stats(f"{Conf.Q_STAT}:*") or []
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_q/brokers/__init__.py", line 131, in get_stats
    key_list = self.cache.get(Conf.Q_STAT)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 36, in _decorator
    raise e.__cause__
  File "/root/.local/lib/python3.11/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/redis/commands/core.py", line 1830, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/redis/client.py", line 542, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/redis/connection.py", line 1109, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.11/site-packages/redis/connection.py", line 282, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to inventree-cache:6379. Try again.
```

### Steps to Reproduce

If you enable

```
# Redis cache setup (disabled by default)
# Un-comment the following lines to enable Redis cache
# Note that you will also have to run docker-compose with the --profile redis command
# Refer to settings.py for other cache options
#INVENTREE_CACHE_HOST=inventree-cache
#INVENTREE_CACHE_PORT=6379
```

before the Initial Database Setup, it will throw an error

### Expected behaviour

assumed it will ignore the directive as its not called during Initial Database Setup docker setup/

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.15.1

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error -3 connecting to inventree-cache:6379. Try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/root/.local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/inventree/src/backend/InvenTree/InvenTree/apps.py", line 59, in ready
    InvenTree.tasks.offload_task(InvenTree.tasks.check_for_migrations)
  File "/home/inventree/src/backend/InvenTree/InvenTree/tasks.py", line 208, in offload_task
    if force_async or (is_worker_running() and not force_sync):
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/src/backend/InvenTree/InvenTree/status.py", line 21, in is_worker_running
    clusters = Stat.get_all()
               ^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_q/status.py", line 109, in get_all
    packs = broker.get_stats(f"{Conf.Q_STAT}:*") or []
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_q/brokers/__init__.py", line 131, in get_stats
    key_list = self.cache.get(Conf.Q_STAT)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django_redis/cache.py", line 36, in _decorator
    raise e.__cause__
  File "/root/.local/lib/python3.11/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/redis/commands/core.py", line 1830, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/redis/client.py", line 542, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/redis/connection.py", line 1109, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.11/site-packages/redis/connection.py", line 282, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to inventree-cache:6379. Try again.
```

**Comment by SchrodingersGat** [comment]
@yodaphone thanks for raising this issue, I will look into this. I think there is a way to automatically handle when the cache should be accessed. And the documentation should be clearer too.

**Comment by SchrodingersGat** [comment]
@yodaphone I have opened a new PR - https://github.com/inventree/InvenTree/pull/7388 - which will fix this entirely. As well as improve the documentation around cache support
