### ISSUE TITLE
MySQL: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by Mattie112** [inventree/InvenTree#7443]
### Deployment Method

- [ ] Installer
- [X] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

During the first initialization of the database on MySQL:

```
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")
```

### Steps to Reproduce

1. See my used docker-compose below, I already have the infra set-up for MySQL so I want to use that
2. Do a `docker compose run --rm inventree-server invoke update`
3. After installing the dependencies it will crash with a SQL error

### Relevant log output

```bash
`docker-compose.yaml` 


# https://raw.githubusercontent.com/inventree/InvenTree/master/contrib/container/docker-compose.yml

services:
  # redis acts as database cache manager
  inventree-cache:
    image: redis:7.0
    container_name: inventree-cache
    env_file:
      - .env
    expose:
      - ${INVENTREE_CACHE_PORT:-6379}
    restart: always

  # InvenTree web server service
  # Uses gunicorn as the web server
  inventree-server:
    # If you wish to specify a particular InvenTree version, do so here
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-server
    # Only change this port if you understand the stack.
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      # Data volume must map to /home/inventree/data
      - inventree-data:/home/inventree/data:z
    restart: unless-stopped

  # Background worker process handles long-running or periodic tasks
  inventree-worker:
    # If you wish to specify a particular InvenTree version, do so here
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-worker
    command: invoke worker
    depends_on:
      - inventree-server
    env_file:
      - .env
    volumes:
      # Data volume must map to /home/inventree/data
      - inventree-data:/home/inventree/data:z
    restart: unless-stopped

  # alternative: run nginx as reverse proxy
  inventree-proxy:
     container_name: inventree-proxy
     image: nginx:stable
     restart: always
     depends_on:
         - inventree-server
     ports:
         - ${INVENTREE_WEB_PORT:-80}:80
         - 443:443
     volumes:
         - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
         - inventree-data:/var/www:z
volumes:
  inventree-data:
```

Log file (error is on line 73):
```
Loading config file : /home/inventree/data/config.yaml
Installing required python packages from 'src/backend/requirements.txt'
Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (24.0)
Requirement already satisfied: setuptools in /root/.local/lib/python3.11/site-packages (69.5.1)
Collecting setuptools
  Downloading setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 kB 28.6 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 69.5.1
    Uninstalling setuptools-69.5.1:
      Successfully uninstalled setuptools-69.5.1
Successfully installed setuptools-70.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: asgiref==3.8.1 in /root/.local/lib/python3.11/site-packages (from -r src/backend/requirements.txt (line 3)) (3.8.1)
Requirement already satisfied: async-timeout==4.0.3 in /root/.local/lib/python3.11/site-packages (from -r src/backend/requirements.txt (line 9)) (4.0.3)
[...more dependencies...]
Requirement already satisfied: xlwt==1.3.0 in /root/.local/lib/python3.11/site-packages (from -r src/backend/requirements.txt (line 1500)) (1.3.0)
Requirement already satisfied: zipp==3.18.1 in /root/.local/lib/python3.11/site-packages (from -r src/backend/requirements.txt (line 1504)) (3.18.1)
Requirement already satisfied: zopfli==0.2.3 in /root/.local/lib/python3.11/site-packages (from -r src/backend/requirements.txt (line 1508)) (0.2.3)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 70.0.0
    Uninstalling setuptools-70.0.0:
      Successfully uninstalled setuptools-70.0.0
Successfully installed setuptools-69.5.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing plugin packages from '/home/inventree/data/plugins.txt'
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Backing up InvenTree database...
Python version 3.11.9 - /usr/local/bin/python3
/root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Backing Up Database: inventree
 mysqldump inventree --quick --host=xx.xx.xx --port=3306 --user=inventree --password=xx 
Backup size: 533.0 B
Writing file to default-a497d9bfc5c5-2024-06-14-131417.dump.gz
Backing up InvenTree media files...
Python version 3.11.9 - /usr/local/bin/python3
/root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Backup size: 80.0 B
Writing file to a497d9bfc5c5-2024-06-14-131422.tar.gz
Running InvenTree database migrations...
========================================
Python version 3.11.9 - /usr/local/bin/python3
/root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Failed to set maintenance mode state
No changes detected
Python version 3.11.9 - /usr/local/bin/python3
/root/.local/lib/python3.11/site-packages/allauth/exceptions.py:9: UserWarning: allauth.exceptions is deprecated, use allauth.core.exceptions
  warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
Failed to set maintenance mode state
Operations to perform:
  Apply all migrations: InvenTree, account, admin, auth, build, common, company, contenttypes, django_q, error_report, exchange, flags, label, machine, order, otp_static, otp_totp, part, plugin, report, socialaccount, stock, taggit, user_sessions, users
Running migrations:
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/root/.local/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 451, in create_model
    self.execute(sql, params or None)
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/root/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/root/.local/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/src/backend/InvenTree/InvenTree/management/commands/runmigrations.py", line 18, in handle
    check_for_migrations(force=True, reload_registry=False)
  File "/home/inventree/src/backend/InvenTree/InvenTree/tasks.py", line 700, in check_for_migrations
    call_command('migrate', interactive=False)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "/root/.local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 72, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1"))
```

`.env`
```
# https://raw.githubusercontent.com/inventree/InvenTree/master/contrib/container/.env
# InvenTree environment variables for docker compose deployment

# Specify the location of the external data volume
# By default, placed in local directory 'inventree-data'
INVENTREE_EXT_VOLUME=invtree-data

# Ensure debug is false for a production setup
INVENTREE_DEBUG=False
INVENTREE_LOG_LEVEL=WARNING

# InvenTree admin account details
# Un-comment (and complete) these lines to auto-create an admin acount
#INVENTREE_ADMIN_USER=
#INVENTREE_ADMIN_PASSWORD=
#INVENTREE_ADMIN_EMAIL=

# Database configuration options
INVENTREE_DB_ENGINE=mysql
INVENTREE_DB_NAME=inventree
INVENTREE_DB_HOST=xx.xx.xx
INVENTREE_DB_PORT=3306

# Database credentials - These should be changed from the default values!
INVENTREE_DB_USER=inventree
INVENTREE_DB_PASSWORD=xx

# Redis cache setup (disabled by default)
# Un-comment the following lines to enable Redis cache
# Note that you will also have to run docker-compose with the --profile redis command
# Refer to settings.py for other cache options
INVENTREE_CACHE_ENABLED=True
INVENTREE_CACHE_HOST=inventree-cache
INVENTREE_CACHE_PORT=6379

# Options for gunicorn server
INVENTREE_GUNICORN_TIMEOUT=90

# Enable custom plugins?
INVENTREE_PLUGINS_ENABLED=True

# Run migrations automatically?
INVENTREE_AUTO_UPDATE=True

# Image tag that should be used
INVENTREE_TAG=stable

# Site URL - update this to match your host
INVENTREE_SITE_URL="https://inventree.xx.xx.xx"

COMPOSE_PROJECT_NAME=inventree
```
```

**Comment by SchrodingersGat** [comment]
Have you created the database with correct permissions, etc, on your remote db host?

**Comment by Mattie112** [comment]
Yes I have an empty (e.g. no tables) database called `inventree` and an user (`inventree`) that haas ALL PRIVILEGES (no grant) on `inventree@'%'`.

The mysqldump command (line 36) works. I tried looking what query is done exactly but I have not been able to find it yet (my Python/Django knowledge is quite limited)

**Comment by Mattie112** [comment]
When I set the `INVENTREE_DEBUG=True` env var I do not get any more details. Do you know if there is a way for example to print all SQL queries in full?

**Comment by SchrodingersGat** [comment]
Can you enter the console of your "inventree-server" docker container, and run the following commands:

```bash
cd src/backend/InvenTree/
python ./manage.py showmigrations
```

And provide the output here

**Comment by SchrodingersGat** [comment]
Ok so none of the migrations are being run at all. There is a critical error connecting to or configuring the database. 

What version of mysql are you running? You will need [at least version 8](https://docs.djangoproject.com/en/4.2/ref/databases/#version-support)

**Comment by Mattie112** [comment]
That indeed was the problem. The server I choose was apparently not updated for a long time :) It was not really clear from the errors (as the whole query was not printed) that that was the problem. I used one of our other servers that had an actual recent version and it works. Thanks for the replies and I can hand it over to the team to try it out.
