### ISSUE TITLE
Failed to add parameter value that looks a little bit like a number

### ISSUE THREAD

**Issue by reid-p** [inventree/InvenTree#7593]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Adding the following value to a part parameter '88E6352' result in the following error:
ProgrammingError
inf can not be used with MySQL
URL: /api/part/parameter/

### Steps to Reproduce

Add any part paramter and use the value: 88E6352

### Expected behaviour

That the value is added as string.

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.15.4

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
Can you please provide the full error log? Should be logged in the admin page

**Comment by reid-p** [comment]
`Type: ProgrammingError
Path: /api/part/parameter/
Info: inf can not be used with MySQL
When: July 9, 2024, 12:20 p.m.
Data: Traceback (most recent call last):

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
return self.cursor.execute(query, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/cursors.py", line 176, in execute
mogrified_query = self._mogrify(query, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/cursors.py", line 198, in _mogrify
args = tuple(map(db.literal, args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/connections.py", line 290, in literal
s = self.escape(o, self.encoders)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/converters.py", line 76, in Float2Str
raise ProgrammingError("%s can not be used with MySQL" % s)

MySQLdb.ProgrammingError: inf can not be used with MySQL


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/rest_framework/generics.py", line 242, in post
return self.create(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/src/backend/InvenTree/InvenTree/mixins.py", line 22, in create
self.perform_create(serializer)

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
serializer.save()

File "/home/inventree/inventree/src/backend/InvenTree/InvenTree/serializers.py", line 294, in save
super().save(**kwargs)

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
self.instance = self.create(validated_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/src/backend/InvenTree/InvenTree/serializers.py", line 308, in create
return super().create(initial_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
instance = ModelClass._default_manager.create(**validated_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/query.py", line 658, in create
obj.save(force_insert=True, using=self.db)

File "/home/inventree/inventree/src/backend/InvenTree/part/models.py", line 3701, in save
super().save(*args, **kwargs)

File "/home/inventree/inventree/src/backend/InvenTree/InvenTree/models.py", line 146, in save
super().save(*args, **kwargs)

File "/home/inventree/inventree/src/backend/InvenTree/InvenTree/models.py", line 123, in save
super().save(*args, **kwargs)

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/base.py", line 814, in save
self.save_base(

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
updated = self._save_table(
^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
results = self._do_insert(
^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
return manager._insert(
^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
cursor.execute(sql, params)

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
return super().execute(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
return self._execute_with_wrappers(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
return executor(sql, params, many, context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
with self.db.wrap_database_errors:

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
return self.cursor.execute(query, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/cursors.py", line 176, in execute
mogrified_query = self._mogrify(query, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/cursors.py", line 198, in _mogrify
args = tuple(map(db.literal, args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/connections.py", line 290, in literal
s = self.escape(o, self.encoders)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/inventree/env/lib64/python3.11/site-packages/MySQLdb/converters.py", line 76, in Float2Str
raise ProgrammingError("%s can not be used with MySQL" % s)

django.db.utils.ProgrammingError: inf can not be used with MySQL`

**Comment by SchrodingersGat** [comment]
Ok, fix incoming in https://github.com/inventree/InvenTree/pull/7601
