### ISSUE TITLE
Install error: ModuleNotFoundError: No module named 'qr_code' when make migrations

### ISSUE THREAD

**Issue by DARELLEE** [inventree/InvenTree#766]
Hi，when i make migrations, turns out ModuleNotFoundError like:
`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alexli/.virtualenvs/inventree-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/alexli/.virtualenvs/inventree-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/alexli/.virtualenvs/inventree-env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alexli/.virtualenvs/inventree-env/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/alexli/.virtualenvs/inventree-env/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/alexli/.virtualenvs/inventree-env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'qr_code'
`

**Comment by SchrodingersGat** [comment]
The qr_code library recently got updated. Try running `make update` to ensure the library version is correct, and lmk how you go.

**Comment by DARELLEE** [comment]
I tried `make update ` , but turns out  the same error:
`ModuleNotFoundError: No module named 'qr_code'
Makefile:14: recipe for target 'migrate' failed
make: *** [migrate] Error 1`

**Comment by SchrodingersGat** [comment]
Odd.

1. What OS are you running?
1. What git commit of InvenTree are you running?
1. Are you running in a virtual environment?
1. What is the output of the command `pip show django-qr-code`?

**Comment by DARELLEE** [comment]
It worked, I downloaded the latest version and reinstalled it. Thanks a lot
