### ISSUE TITLE
Inventree Server API version (196) is older than minimum supported API version (206)

### ISSUE THREAD

**Issue by superbeppe98** [inventree/InvenTree#7935]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [X] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

Hello,
i have a problem running my usual script for checking some inventory, with this error:
"Server API version (196) is older than minimum supported API version (206)"

How can i update the API  version?

### Steps to Reproduce

Hello,
i have a problem running my usual script for checking some inventory, with this error:
"Server API version (196) is older than minimum supported API version (206)"

How can i update the API  version?

### Relevant log output

```bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
OK: 231 MiB in 103 packages
Requirement already satisfied: ebaysdk==2.2.0 in ./ebay-listing-matches/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: beautifulsoup4==4.12.3 in ./ebay-listing-matches/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (4.12.3)
Requirement already satisfied: bs4==0.0.2 in ./ebay-listing-matches/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (0.0.2)
Requirement already satisfied: python-dotenv==1.0.1 in ./ebay-listing-matches/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: requests==2.32.3 in ./ebay-listing-matches/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (2.32.3)
Requirement already satisfied: inventree==0.16.1 in ./ebay-listing-matches/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.16.1)
Requirement already satisfied: lxml in ./ebay-listing-matches/lib/python3.11/site-packages (from ebaysdk==2.2.0->-r requirements.txt (line 1)) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in ./ebay-listing-matches/lib/python3.11/site-packages (from beautifulsoup4==4.12.3->-r requirements.txt (line 2)) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in ./ebay-listing-matches/lib/python3.11/site-packages (from requests==2.32.3->-r requirements.txt (line 5)) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in ./ebay-listing-matches/lib/python3.11/site-packages (from requests==2.32.3->-r requirements.txt (line 5)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./ebay-listing-matches/lib/python3.11/site-packages (from requests==2.32.3->-r requirements.txt (line 5)) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in ./ebay-listing-matches/lib/python3.11/site-packages (from requests==2.32.3->-r requirements.txt (line 5)) (2023.7.22)

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/opt/cronicle/plugins/ebay-listing-matches/ebay-listing-matches/lib/python3.11/site-packages/inventree/api.py", line 120, in connect
    self.connected = self.testServer()
                     ^^^^^^^^^^^^^^^^^
  File "/opt/cronicle/plugins/ebay-listing-matches/ebay-listing-matches/lib/python3.11/site-packages/inventree/api.py", line 228, in testServer
    raise ValueError(f"Server API version ({api_version}) is older than minimum supported API version ({InvenTreeAPI.getMinApiVersion()})")
ValueError: Server API version (196) is older than minimum supported API version (206)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cronicle/plugins/ebay-listing-matches/ebay-listing-matches.py", line 35, in <module>
    inventree_api = InvenTreeAPI(SERVER_ADDRESS, username=MY_USERNAME, password=MY_PASSWORD, timeout=3600)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/cronicle/plugins/ebay-listing-matches/ebay-listing-matches/lib/python3.11/site-packages/inventree/api.py", line 77, in __init__
    self.connect()
  File "/opt/cronicle/plugins/ebay-listing-matches/ebay-listing-matches/lib/python3.11/site-packages/inventree/api.py", line 125, in connect
    raise ConnectionRefusedError("Could not connect to InvenTree server")
ConnectionRefusedError: Could not connect to InvenTree server

# Job failed at 2024/08/20 16:47:34 (GMT+2).
# Error: Script exited with code: 1: [notice] A new release of pip is available: 23.2.1 -> 24.2
# End of log.
```

**Comment by matmair** [comment]
Sounds like your inventree python library was updated. You can either pin it lower or update your inventree server.

**Comment by superbeppe98** [comment]
How can i do it?
My inventree server version is 0.15.8

**Comment by matmair** [comment]
That depends on how you deployed and is documented on the according docs pages.
installer https://docs.inventree.org/en/stable/start/installer/?h=upgrade#updating-inventree
docker https://docs.inventree.org/en/stable/start/docker_install/#updating-inventree

**Comment by superbeppe98** [comment]
i'm on the last version but i have api version set on 196 instead of 242.

![image](https://github.com/user-attachments/assets/328da9e9-d8d7-462a-811a-920ae5a2b1bf)

**Comment by matmair** [comment]
you are not on latest, latest has a version number of 0.17.0dev. Have you restarted the server after upgrading?

**Comment by superbeppe98** [comment]
yes i restarted the server and the containers

**Comment by SchrodingersGat** [comment]
You should downgrade your `inventree-python` version to `0.14.0` - the latest release is targetting a much newer API:

```
pip install inventree==0.14.0
```
