### ISSUE TITLE
Inventree S3 backup options syntax

### ISSUE THREAD

**Issue by yoxx** [inventree/InvenTree#8151]
### Deployment Method

- [ ] Installer
- [ ] Docker Development
- [x] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [x] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

We are trying to deploy inventree in our k8s cluster.
We want to store our backups in S3. 

Based on your documentation we do not find it clear how to provide a dict to this env variable -> https://docs.inventree.org/en/stable/start/backup/#configuration

Our deployement looks something like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventree-app
spec:
  template:
    spec:
      initContainers:
        - name: init-migrate
          env:
            - name: INVENTREE_BACKUP_STORAGE
              value: "storages.backends.s3boto3.S3Boto3Storage"
            - name: INVENTREE_BACKUP_OPTIONS
              value: '{"access_key": "xxxx","secret_key": "xxxx","bucket_name": "xxxx","default_acl": "private"}'
```

When deployed we get an error from the storage class :
```
TypeError: dbbackup.storage.Storage() argument after ** must be a mapping, not str
  File "/root/.local/lib/python3.11/site-packages/dbbackup/utils.py", line 120, in wrapper
    func(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/dbbackup/management/commands/dbbackup.py", line 80, in handle
    self.storage = get_storage()
                   ^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/dbbackup/storage.py", line 33, in get_storage
    return Storage(path, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^

Traceback (most recent call last):
  File "/home/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
```

So it appears it sees our dict as a string, what would be the correct syntax to fix this using enviroment variables?

### Steps to Reproduce

0. use  https://docs.inventree.org/en/stable/start/backup/#configuration for external providers which points to django-dbbackup
1. https://django-dbbackup.readthedocs.io/en/master/storage.html#amazon-s3
2. Shows a dict in the DBBACKUP_STORAGE_OPTIONS which as far as I understand translates to INVENTREE_BACKUP_OPTIONS in inventree
3. See above ^

**Comment by SchrodingersGat** [comment]
Looks like an issue with the way `DBBACKUP_STORAGE_OPTIONS` is being loaded.

See fix incoming in https://github.com/inventree/InvenTree/pull/8153

**Comment by SchrodingersGat** [comment]
@arladmin interesting, had not considered this use case - but nice to know that you found a work-around 👍

**Comment by Mattie112** [comment]
In k8s we do it like this:

```
      containers:
        - name: inventree-server
          image: inventree/inventree:stable
          envFrom:
            - configMapRef:
                name: inventree-config
          env:
            - name: INVENTREE_BACKUP_STORAGE
              value: "storages.backends.s3boto3.S3Boto3Storage"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accessKeyId
                  name: s3-creds
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretAccessKey
                  name: s3-creds
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: bucketName
                  name: s3-creds
            - name: INVENTREE_BACKUP_OPTIONS
              value: >
                {
                  "access_key": "$(S3_ACCESS_KEY)",
                  "secret_key": "$(S3_SECRET_KEY)",
                  "bucket_name": "$(S3_BUCKET_NAME)",
                  "default_acl": "private"
                }
          ports:
            - containerPort: 8000
          command: [ "/bin/sh", "-c" ]
          args: [ "pip install django-storages django-storages[boto3] && gunicorn -c ./gunicorn.conf.py InvenTree.wsgi -b ${INVENTREE_WEB_ADDR}:${INVENTREE_WEB_PORT} --chdir ${INVENTREE_BACKEND_DIR}/InvenTree" ]
       
```

Might help someone :) It does take quite some time to "start" using this method but we don't use persistent storage for inventree itself.
