### ISSUE TITLE
Upgrading `0.15.8` to `0.16.x` fails with "Template file with this name already exists" when template file name clashes

### ISSUE THREAD

**Issue by vrzh** [inventree/InvenTree#8208]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

Don't know if this is actually a bug, but hopefully can help if someone else bumps into this issue.

Background: I am trying to upgrade an InvenTree installation from `0.6.4` to the latest `0.16.3`. 

I can sucessfully upgrade to `0.15.8` but no further as the `invoke update` exits with the following exception:

```
Traceback (most recent call last):
  File "/home/inventree/src/backend/InvenTree/manage.py", line 24, in <module>
    main()
  File "/home/inventree/src/backend/InvenTree/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/root/.local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/inventree/src/backend/InvenTree/report/apps.py", line 44, in ready
    self.create_default_labels()
  File "/home/inventree/src/backend/InvenTree/report/apps.py", line 131, in create_default_labels
    report.models.LabelTemplate.objects.create(
  File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/inventree/src/backend/InvenTree/report/models.py", line 145, in save
    super().save()
  File "/home/inventree/src/backend/InvenTree/InvenTree/models.py", line 156, in save
    super().save(*args, **kwargs)
  File "/home/inventree/src/backend/InvenTree/InvenTree/models.py", line 119, in save
    super().save(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
                 ^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/root/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/root/.local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inventree/src/backend/InvenTree/report/models.py", line 60, in rename_template
    instance.check_existing_file(path, raise_error=True)
  File "/home/inventree/src/backend/InvenTree/report/models.py", line 118, in check_existing_file
    raise ValidationError({
django.core.exceptions.ValidationError: {'template': ['Template file with this name already exists']}
```

I noticed that my users (back in the `0.6.4` version) somehow had the following template defined:

```
  {
    "model": "label.partlabel",
    "pk": 1,
    "fields": {
      "metadata": null,
      "name": "Part Label",
      "description": "Simple part label",
      "label": "label/inventree/part/part_label.html",
      "enabled": true,
      "width": 60.0,
      "height": 30.0,
      "filename_pattern": "label.pdf",
      "filters": ""
    }
  },
```

If I rename the `label` field in the above before update (also renaming the actual file in the `media` folder), then everything works perfectly.

But, after the update, I notice that the `0.16.x` helpfully tries to add a new template with the same `part_label.html` name:

```
  {
    "model": "report.labeltemplate",
    "pk": 3,
    "fields": {
      "metadata": {},
      "name": "InvenTree Part Label",
      "description": "Sample part label",
      "revision": 2,
      "filename_pattern": "output.pdf",
      "enabled": true,
      "model_type": "part",
      "filters": "",
      "template": "report/label/part_label.html",
      "width": 50.0,
      "height": 20.0
    }
  },
```

Is this really the cause of the problem, even though the absolute paths are different?

### Steps to Reproduce

See above.

### Expected behaviour

See above.

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

0.16.x

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@vrzh thanks, fix is incoming in https://github.com/inventree/InvenTree/pull/8209
