### ISSUE TITLE
devcontainer: error while loading demo dataset (task "setup-test")

### ISSUE THREAD

**Issue by simonkuehling** [inventree/InvenTree#8303]
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

I'm trying to setup the InvenTree devcontainer in Visual Studio Code and ran the "setup-test" task to populate the database. This fails with an error (full traceback below):

```
django.db.utils.IntegrityError: Problem installing fixture '/workspaces/InvenTree/dev/inventree-demo-dataset/inventree_data.json.tmp.json': Could not load build.BuildItem(pk=11): NOT NULL constraint failed: build_builditem.build_id
```

Can anyone confirm that this is working in your dev setup?

### Steps to Reproduce

1. in vscode: "Run Task" --> "setup-test"

### Expected behaviour

(import the dataset without errors)

### Deployment Method

- [ ] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

current github master branch from today

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

Importing database records from '/workspaces/InvenTree/dev/inventree-demo-dataset/inventree_data.json'
Traceback (most recent call last):
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: build_builditem.build_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/InvenTree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: Problem installing fixture '/workspaces/InvenTree/dev/inventree-demo-dataset/inventree_data.json.tmp.json': Could not load build.BuildItem(pk=11): NOT NULL constraint failed: build_builditem.build_id

**Comment by simonkuehling** [comment]
nevermind, I'm an idiot. My fork just was not up-to-date...
