### ISSUE TITLE
Initial DB migrations fail

### ISSUE THREAD

**Issue by amishHammer** [inventree/InvenTree#835]
`
cd InvenTree && python3 manage.py makemigrations
InvenTree running in DEBUG mode
MEDIA_ROOT: /home/amishhammer/InvenTree-0.1.1/inventree_media
STATIC_ROOT: /home/amishhammer/InvenTree-0.1.1/inventree_static
2020-05-25 18:52:44,548 DEBUG Using selector: EpollSelector
InvenTree: Checking Part image thumbnails
Could not generate Part thumbnails
InvenTree: Checking Company image thumbnails
Could not generate Company thumbnails
Loading barcode plugins
Loading barcode plugins
Discovered 2 barcode plugins:
 - DigikeyBarcodePlugin
 - InvenTreeBarcodePlugin
Loading action plugins
Loading action plugins
Discovered 1 action plugins:
 - SimpleActionPlugin
Traceback (most recent call last):
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_static.py", line 5, in <module>
    from django.utils.deprecation import RemovedInDjango30Warning
ImportError: cannot import name 'RemovedInDjango30Warning'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/contrib/admin/checks.py", line 76, in check_dependencies
    for engine in engines.all():
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/amishhammer/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 125, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django.contrib.admin.templatetags.admin_static': cannot import name 'RemovedInDjango30Warning'
Makefile:14: recipe for target 'migrate' failed
make: *** [migrate] Error 1
`

**Comment by SchrodingersGat** [comment]
These errors indicate that you have django2 installed - InvenTree requires django3

You can confirm this by checking:

```
pip show django
```

To make sure you have all the correct python packages installed:

```
pip3 install -U -r requirements.txt
```

**Comment by amishHammer** [comment]
Seems django 3 is installed:


```
amishhammer@dev1:~/InvenTree-0.1.1$ pip3 show django
Name: Django
Version: 3.0.5
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: /home/amishhammer/.local/lib/python3.6/site-packages
Requires: pytz, asgiref, sqlparse
```

Trying in install the requirements:
```
amishhammer@dev1:~/InvenTree-0.1.1$ pip3 install -U -r requirements.txt
Collecting wheel>=0.34.2 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Collecting Django==3.0.5 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a9/4f/8a247eee2958529a6a805d38fbacd9764fd566462fa0016aa2a2947ab2a6/Django-3.0.5-py3-none-any.whl
Collecting pillow==6.2.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/8a/fd/bbbc569f98f47813c50a116b539d97b3b17a86ac7a309f83b2022d26caf2/Pillow-6.2.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting djangorestframework==3.10.3 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/33/8e/87a4e0025e3c4736c1dc728905b1b06a94968ce08de15304417acb40e374/djangorestframework-3.10.3-py3-none-any.whl
Collecting django-dbbackup==3.3.0 (from -r requirements.txt (line 5))
Collecting django-cors-headers==3.2.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/21/93/b1efe344f5b7e60ea2aa4e54f76d8b50c93d7db73d69dd95e9e97a696c96/django_cors_headers-3.2.0-py3-none-any.whl
Collecting django_filter==2.2.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/0a/c9/acc63b687002afae8b5137afd6230d88c99411aa2daedf07fed3f0913516/django_filter-2.2.0-py3-none-any.whl
Collecting django-mptt==0.11.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/83/86/78a64e1aa72dc6156a1a4f1f830564c932b0900460607def7ccd56a1df80/django_mptt-0.11.0-py2.py3-none-any.whl
Collecting django-markdownx==3.0.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/63/11/adcfa0b616d6feeea3a291d6b10f6ad4d7da9d21b6c737d2128912a153b7/django_markdownx-3.0.1-py2.py3-none-any.whl
Collecting django-markdownify==0.8.0 (from -r requirements.txt (line 10))
Collecting coreapi==2.3.0 (from -r requirements.txt (line 11))
Collecting pygments==2.2.0 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting tablib==0.13.0 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/7b/c7/cb74031b330cd94f3580926dc707d148b4ba9138449fc9f433cb79e640d8/tablib-0.13.0-py3-none-any.whl
Collecting django-crispy-forms==1.8.1 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/6e/27/9d6eef25ee96060b20a8df3cc6f6e5f98492900fada0b736767daf6f8f1c/django_crispy_forms-1.8.1-py2.py3-none-any.whlCollecting django-import-export==2.0.0 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/7b/dd/b782bedc11665297f89ee106ff53c8c2acbc5b73526f441a247f5fb77f45/django_import_export-2.0-py3-none-any.whl
Collecting django-cleanup==4.0.0 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/b8/68/9a36c11176b5cc07c65f8e603cbee83deb10fb952a995139f2886eb95f2c/django_cleanup-4.0.0-py2.py3-none-any.whl     
Collecting django-qr-code==1.2.0 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/e6/be/d98ed3062ba759ae3bebd3098e602c4beb0d7c47b93a5471df9452e4176c/django_qr_code-1.2.0-py3-none-any.whl
Collecting flake8==3.3.0 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/cd/a6/1fe37679be3b224c96d8b64782d724d6a2c4212c8ddd914572fb8317a298/flake8-3.3.0-py2.py3-none-any.whl
Collecting coverage==4.0.3 (from -r requirements.txt (line 19))
Collecting python-coveralls==2.9.1 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/2f/4a/0f776edd7d985e5fc456a8430bde69ce0701f6b6bae17586c74a309f89ae/python_coveralls-2.9.1-py2.py3-none-any.whl
Collecting rapidfuzz==0.7.6 (from -r requirements.txt (line 21))
Collecting django-stdimage==5.1.1 (from -r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/50/4c/e376ba44f7035dd86ff1f421cb4a4e05ff75687d467e6d922e99a257c40e/django_stdimage-5.1.1-py2.py3-none-any.whl
Collecting pytz (from Django==3.0.5->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting sqlparse>=0.2.2 (from Django==3.0.5->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/85/ee/6e821932f413a5c4b76be9c5936e313e4fc626b33f16e027866e1d60f588/sqlparse-0.3.1-py2.py3-none-any.whl
Collecting asgiref~=3.2 (from Django==3.0.5->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/68/00/25013f7310a56d17e1ab6fd885d5c1f216b7123b550d295c93f8e29d372a/asgiref-3.2.7-py2.py3-none-any.whl
Collecting six (from django-dbbackup==3.3.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting django-js-asset (from django-mptt==0.11.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/aa/2d/98089cf51c8e83bc70723021390b94a3638a4a0ce30a47e2e70476b2095d/django_js_asset-1.2.2-py2.py3-none-any.whl    
Collecting Markdown (from django-markdownx==3.0.1->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/a4/63/eaec2bd025ab48c754b55e8819af0f6a69e2b1e187611dd40cbbe101ee7f/Markdown-3.2.2-py3-none-any.whl
Collecting bleach>=2.0 (from django-markdownify==0.8.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/9a/1e/7d6cb3b27cd2c490558349ca5d5cc05b390b017da1c704cac807ac8bd9fb/bleach-3.1.5-py2.py3-none-any.whl
Collecting itypes (from coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/3f/bb/3bd99c7cd34d4a123b2903e16da364f6d2078b1c3a3530a8ad105c668104/itypes-1.2.0-py2.py3-none-any.whl
Collecting requests (from coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting uritemplate (from coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bf/0c/60d82c077998feb631608dca3cc1fe19ac074e772bf0c24cf409b977b815/uritemplate-3.0.1-py2.py3-none-any.whl        
Collecting coreschema (from coreapi==2.3.0->-r requirements.txt (line 11))
Collecting odfpy (from tablib==0.13.0->-r requirements.txt (line 13))
Collecting xlrd (from tablib==0.13.0->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl
Collecting pyyaml (from tablib==0.13.0->-r requirements.txt (line 13))
Collecting openpyxl>=2.4.0 (from tablib==0.13.0->-r requirements.txt (line 13))
Collecting backports.csv (from tablib==0.13.0->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
Collecting xlwt (from tablib==0.13.0->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl
Collecting diff-match-patch (from django-import-export==2.0.0->-r requirements.txt (line 15))
Collecting qrcode (from django-qr-code==1.2.0->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/42/87/4a3a77e59ab7493d64da1f69bf1c2e899a4cf81e51b2baa855e8cc8115be/qrcode-6.1-py2.py3-none-any.whl
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8==3.3.0->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/27/49/924098b3b85c286696f37e014475d79471ffc44509613af420645a3c12cb/pyflakes-1.5.0-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8==3.3.0->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8==3.3.0->-r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting progressbar2>=3.0.0 (from django-stdimage==5.1.1->-r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/cc/37/b6ec42c1c8521c083f21d5f5118ca4ffc438d4ad9dd8367638674ea0febd/progressbar2-3.51.3-py2.py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from Markdown->django-markdownx==3.0.1->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl
Collecting webencodings (from bleach>=2.0->django-markdownify==0.8.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl       
Collecting packaging (from bleach>=2.0->django-markdownify==0.8.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests->coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
Collecting jinja2 (from coreschema->coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting defusedxml (from odfpy->tablib==0.13.0->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting jdcal (from openpyxl>=2.4.0->tablib==0.13.0->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Collecting et-xmlfile (from openpyxl>=2.4.0->tablib==0.13.0->-r requirements.txt (line 13))
Collecting python-utils>=2.3.0 (from progressbar2>=3.0.0->django-stdimage==5.1.1->-r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/d9/ff/623dfa533f3277199957229f053fdb2c73a9c18048680e1899c9a5c95e6b/python_utils-2.4.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->Markdown->django-markdownx==3.0.1->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->bleach>=2.0->django-markdownify==0.8.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->coreschema->coreapi==2.3.0->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: wheel, pytz, sqlparse, asgiref, Django, pillow, djangorestframework, six, django-dbbackup, django-cors-headers, django-filter, django-js-asset, django-mptt, zipp, importlib-metadata, Markdown, django-markdownx, webencodings, pyparsing, packaging, bleach, django-markdownify, itypes, chardet, idna, urllib3, certifi, requests, uritemplate, MarkupSafe, jinja2, coreschema, coreapi, pygments, defusedxml, odfpy, xlrd, pyyaml, jdcal, et-xmlfile, openpyxl, backports.csv, xlwt, 
tablib, django-crispy-forms, diff-match-patch, django-import-export, django-cleanup, qrcode, django-qr-code, pyflakes, pycodestyle, mccabe, flake8, coverage, python-coveralls, rapidfuzz, python-utils, progressbar2, django-stdimage
Successfully installed Django-3.0.5 Markdown-3.2.2 MarkupSafe-1.1.1 asgiref-3.2.7 backports.csv-1.0.7 bleach-3.1.5 certifi-2020.4.5.1 chardet-3.0.4 coreapi-2.3.3 coreschema-0.0.4 coverage-4.5.4 defusedxml-0.6.0 diff-match-patch-20181111 django-cleanup-4.0.0 django-cors-headers-3.2.0 django-crispy-forms-1.8.1 django-dbbackup-3.3.0 django-filter-2.2.0 django-import-export-2.0 django-js-asset-1.2.2 django-markdownify-0.8.0 django-markdownx-3.0.1 django-mptt-0.11.0 django-qr-code-1.2.0 django-stdimage-5.1.1 djangorestframework-3.10.3 et-xmlfile-1.0.1 flake8-3.3.0 idna-2.9 importlib-metadata-1.6.0 itypes-1.2.0 jdcal-1.4.1 jinja2-2.11.2 mccabe-0.6.1 odfpy-1.4.1 openpyxl-3.0.3 packaging-20.4 pillow-6.2.2 progressbar2-3.51.3 pycodestyle-2.3.1 pyflakes-1.5.0 pygments-2.5.1 pyparsing-2.4.7 python-coveralls-2.9.1 python-utils-2.4.0 pytz-2020.1 pyyaml-5.3.1 qrcode-6.1 rapidfuzz-0.7.6 requests-2.23.0 six-1.15.0 sqlparse-0.3.1 tablib-0.14.0 uritemplate-3.0.1 urllib3-1.25.9 webencodings-0.5.1 wheel-0.34.2 xlrd-1.2.0 xlwt-1.3.0 zipp-3.1.0
```

Still get the same issue after running both of these commands.

**Comment by SchrodingersGat** [comment]
I would then suggest trying the following:

1. Make sure you have the latest version of InvenTree
1. Try installing [inside a virtual environment](https://inventree.github.io/docs/start/install#virtual-environment) - it is possible (perhaps) that there's a python package incompatibility going on?
1. What is the complete sequence of commands that you are running?

**Comment by SchrodingersGat** [comment]
@amishHammer did you have any luck with this?

**Comment by amishHammer** [comment]
Got it working had to clear out a bunch of files.  Also the instructions for virtual env instructions need updating to reference the fat they should be run from ~ not from the previous working directory (the git clone) as you follow through the instructions.

**Comment by SchrodingersGat** [comment]
Great to hear that you got it running!

> Also the instructions for virtual env instructions need updating to reference the fat they should be run from ~ not from the previous working directory (the git clone) as you follow through the instructions.

I *think* that the instructions do call this out, right?

![image](https://user-images.githubusercontent.com/10080325/90840051-50e7e700-e39c-11ea-9fa8-737105e0af80.png)
