### ISSUE TITLE
Stock creation via API fails

### ISSUE THREAD

**Issue by mariosk8s** [inventree/InvenTree#842]
In the quest for adding stock via API, the following script:

`import coreapi
auth = coreapi.auth.BasicAuthentication(
    username='user',
    password='pass',
)

client = coreapi.Client(auth=auth)
schema = client.get("http://test:8000/api-doc/")

action = ["stock", "add &gt; create"]
params = {
    "allocated": 0,
    # "batch": ...,
    # "build_order": ...,
    # "belongs_to": ...,
    # "link": ...,
    "location": 2,
    # "notes": ...,
    "part": 11,
    "quantity": 20,
    # "sales_order": ...,
    "serial": 0,
    # "supplier_part": ...,
    "status": 10,
    "tracking_items": 0,
    # "uid": ...,
}
result = client.action(schema, action, params=params)
`
produces:
`/usr/bin/python3.6 /d2/hm/mario/src/InvenTree/post.py
Traceback (most recent call last):
  File "/d2/hm/mario/src/InvenTree/post.py", line 8, in <module>
    schema = client.get("http://test:8000/api-doc/")
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/client.py", line 136, in get
    return transport.transition(link, decoders, force_codec=force_codec)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/transports/http.py", line 380, in transition
    result = _decode_result(response, decoders, force_codec)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/transports/http.py", line 294, in _decode_result
    result = codec.load(response.content, **options)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/base.py", line 24, in load
    return self.decode(*args, **kwargs)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 306, in decode
    doc = _primative_to_document(data, base_url)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 234, in _primative_to_document
    content = _get_content(data, base_url=url)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 132, in _get_content
    for key, value in item.items()
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 133, in <dictcomp>
    if key not in ('_type', '_meta')
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 276, in _primative_to_document
    content = _get_content(data, base_url=base_url)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 132, in _get_content
    for key, value in item.items()
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 133, in <dictcomp>
    if key not in ('_type', '_meta')
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 276, in _primative_to_document
    content = _get_content(data, base_url=base_url)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 132, in _get_content
    for key, value in item.items()
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 133, in <dictcomp>
    if key not in ('_type', '_meta')
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 267, in _primative_to_document
    for item in fields if isinstance(item, dict)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 267, in <listcomp>
    for item in fields if isinstance(item, dict)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 58, in _get_schema
    return decode_schema_from_corejson(schema_data)
  File "/d2/hm/mario/.local/lib/python3.6/site-packages/coreapi/codecs/corejson.py", line 48, in decode_schema_from_corejson
    return schema_cls(title=title, description=description)
TypeError: __init__() missing 1 required positional argument: 'enum'
`
It seems to choke on the Status enum.
I'm nt sure whether i did something wrong, but it seems to not work. As i'm new to django, i can't muster up a patch yet either.

**Comment by mariosk8s** [comment]
Trying the Python interface, i don't see any way to programmatically add stock.
Is there a way to do tis at all?

**Comment by SchrodingersGat** [comment]
Hey @mariosk8s yes this is possible, I'd strongly suggest using the [python API](https://github.com/inventree/inventree-python)

Please note that you should upgrade to the latest version (0.0.9) using pip:

```
pip install --upgrade inventree
```

Also make sure that you have the latest version of InvenTree too - I've literally just fixed a bug with stock-creation via the API.

Here is an example for creating new items using the API:
https://inventree.github.io/docs/extend/python#creating-new-items

**Comment by mariosk8s** [comment]
That is sweet.
