### ISSUE TITLE
[PUI] infinite loop if classic frontend is disabled

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8575]
### Steps to Reproduce

- Disable classic frontend (e.g. in `config.yaml`)
- Navigate to admin center
- View "plugins" table

![Image](https://github.com/user-attachments/assets/74d0a274-e8d5-46c2-aa2b-40da2e319582)

### Traceback

```python
Traceback (most recent call last):

  File "/home/inventree/dev/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/dev/venv/lib/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/dev/venv/lib/python3.11/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/dev/venv/lib/python3.11/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/dev/venv/lib/python3.11/site-packages/rest_framework/pagination.py", line 395, in paginate_queryset
    return list(queryset[self.offset:self.offset + self.limit])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 115, in __init__
    self.meta = {
                ^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 116, in <dictcomp>
    key: get_plugin_meta(key)
         ^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/models.py", line 108, in get_plugin_meta
    result = getattr(plugin, name, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 392, in settings_url
    config = self.plugin_config(force_reload=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/plugin.py", line 109, in plugin_config
    self._plugin_config = registry.get_plugin_config(self.plugin_slug())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/inventree/src/backend/InvenTree/plugin/registry.py", line 121, in get_plugin_config
    cfg = PluginConfig.objects.filter(key=slug).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^

RecursionError: maximum recursion depth exceeded
```

**Comment by turist79** [comment]
@SchrodingersGat probably not the same issue but i was able to totally "lock out" one of the stock items by adding/removing/editing test results to it. Stock item page was totally unresponsive (it rendered once accessed but it was not possible to perform any actions, the mouse pointer over anything did not register etc). This state was observed 100%, survived whole stack restart/redeployment. Happened on 0.16.8 as i remember. Was able to solve it only by going into Django control panel and deleting test results for affected item.

Which logs could diagnose such issue?
This happened way before i have discovered that i can contact you guys here :) so i did not report it properly.

**Comment by SchrodingersGat** [comment]
@turist79 probably best to raise a separate issue for that. Not sure what logs would help here but a clear description of the problem with some screenshots etc would be a great start
