### ISSUE TITLE
[UI] Auth Token Issues

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#8707]
Error message captured on the demo site (unsure of context)

![Image](https://github.com/user-attachments/assets/f24f340e-5054-49bd-8fb1-fa50da3d0b55)

```
Traceback (most recent call last):

  File "/root/.local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.local/lib/python3.11/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.local/lib/python3.11/site-packages/dj_rest_auth/registration/views.py", line 70, in create
    data = self.get_response_data(user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.local/lib/python3.11/site-packages/dj_rest_auth/registration/views.py", line 62, in get_response_data
    return api_settings.TOKEN_SERIALIZER(user.auth_token, context=self.get_serializer_context()).data
                                         ^^^^^^^^^^^^^^^

AttributeError: 'User' object has no attribute 'auth_token'
```

**Comment by matmair** [comment]
@SchrodingersGat you working on this or should I?

**Comment by SchrodingersGat** [comment]
If you can take a look into it, that'd be good

**Comment by matmair** [comment]
Can reproduce, working on solution
