### ISSUE TITLE
failed loading translations

### ISSUE THREAD

**Issue by ineselhajahmed11** [inventree/InvenTree#8730]
in google on my ip/platform i get :
### Body of the issue

vendor-B3_4iN-l.js:127 ERR: Failed loading translations Error: Unknown variable dynamic import: ../locales/en/messages.ts
    at BaseContext-BhSSG9lC.js:31:70403
    at new Promise (<anonymous>)
    at g0 (BaseContext-BhSSG9lC.js:31:70309)
    at fs (BaseContext-BhSSG9lC.js:31:72319)
    at BaseContext-BhSSG9lC.js:31:71596
    at rd (vendor-B3_4iN-l.js:62:24272)
    at ea (vendor-B3_4iN-l.js:62:42382)
    at vendor-B3_4iN-l.js:62:40700
    at k (vendor-B3_4iN-l.js:47:1553)
    at MessagePort.z (vendor-B3_4iN-l.js:47:1915)
BaseContext-BhSSG9lC.js:31 Uncaught (in promise) Error: Unknown variable dynamic import: ../locales/en/messages.ts
    at BaseContext-BhSSG9lC.js:31:70403
    at new Promise (<anonymous>)
    at g0 (BaseContext-BhSSG9lC.js:31:70309)
    at fs (BaseContext-BhSSG9lC.js:31:72319)
    at BaseContext-BhSSG9lC.js:31:71496
    at rd (vendor-B3_4iN-l.js:62:24272)
    at ea (vendor-B3_4iN-l.js:62:42382)
    at vendor-B3_4iN-l.js:62:40700
    at k (vendor-B3_4iN-l.js:47:1553)
    at MessagePort.z (vendor-B3_4iN-l.js:47:1915)

**Comment by matmair** [comment]
Please re-open with all information filled out. I do not know how you expect anyone to debug this

https://github.com/inventree/InvenTree/issues/new?template=bug_report.yaml
