### ISSUE TITLE
Clicking On Part Does Not Go to Supplier Part Details with Pricing Information

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#878]
The normal sequence is:
• Click on Part in the Parts Tab part list. This takes you to the Part screen.
• From here click on the Stock tab and see a row with the part listed.
• Click on the part, which takes you to the Supplier Part screen with Supplier Part Details and Pricing Information.

I have one problem part out of 274 that I now have entered:
• Click on Part in the Parts Tab part list. This takes me to the Part screen.
• From here click on the Stock tab and see a row with the part listed.
• Click on the part and it doubles back to the Part screen instead of going to the Supplier Part screen.
I don't know what I did to cause this operation. What do I need to do to correct it? I looked under Admin but didn't find anything.
--Thank you and regards, Larry

**Comment by SchrodingersGat** [comment]
Probably what is happening here is that this particular part does not have a SupplierPart associated with it. Can you check if this is the case?

**Comment by LarryJoy** [comment]
Oliver,
I found a 2nd part that I have the same problem with. The first part that I referred to did not have any Supplier information. I corrected this by entering the Supplier and information. The second part does have a supplier. Both of these items (parts) do the same thing as stated in my original posting. From the Part screen with sub tabs of Details, Parameters, Stock, Allocated, Used In, Suppliers, Purchase Orders, Attachments, and Notes:
• In both these cases the sub tab Suppliers shows "1".
• I click on the Stock sub tab which shows the part.
• I click on the part and it reverts to the Details sub tab instead of going to the Supplier Part screen.
Still need some help. Thank you and regards,
--Larry

**Comment by SchrodingersGat** [comment]
I think in this case the particular stock item has not had a "supplier part" assigned, 

Here's the snippet of code that displays the column in the table:

```javascript
if (row.supplier_part) {
    url = `/supplier-part/${row.supplier_part}/`;
    }
else {
    url = `/part/${row.part}/`;
}
```

**Comment by LarryJoy** [comment]
Oliver,
The snippet of code that you show doesn't mean anything to me. I am not a programmer or "software" person. Both of these parts that I have indicated have supplier and supplier part number assigned. And I was able to assign pricing/price breakdown originally.

Here is information for one of the parts starting at the initial/major information screen:
10159-473     CAP,47 nF,10%,X7R,50 V,Radial
CAP,47 nF,10%,X7R,50 V,LS5.00,Radial
IPN: 10159-473
External Link: https://www.vishay.com/docs/45171/kseries.pdf
Supplier: D-K BC1099CT-ND
Manufacturer: Vishay BC K473K15X7RF5TH5

Clicking the Dollar sign icon [Show pricing information] I get
Part Pricing
Pricing information for:
10159-473 | Capacitor 47 nF | 10159- - CAP,47 nF,10%,X7R,50 V,LS5.00,Radial
Quantity 1
Supplier Pricing:
Unit Cost     Min: $0.230 USD     Max: $0.230 USD
Quantity* 1
Input quantity for price calculation
Currency*
---------
Select currency for price calculation
In the lower right corner is "Close" and "Calculate". Clicking on Calculate doesn't do any thing and clicking on Close closes the screen.

For the Details tab it has:
Part Details
 Part name Capacitor 47 nF
 IPN 10159-473
 Revision 10159-
 Description CAP,47 nF,10%,X7R,50 V,LS5.00,Radial
 Category CAP/Radial
 External Link https://www.vishay.com/docs/45171/kseries.pdf
 Default Supplier Digi-Key | BC1099CT-ND
 Units EA
 Creation Date June 10, 2020
 Created by Larry

On the right hand side is:
Virtual     No     Part is not a virtual part
Template   No     Part is not a template part
Assembly     No     Part cannot be assembled from other parts
Component     Yes     Part can be used in assemblies
Trackable     No     Part stock is not tracked by serial number
Purchaseable     Yes     Part can be purchased from external suppliers
Salable     No     Part cannot be sold to customers
Active     Yes     Part is active

For the Stock tab (0) is:
Part Stock:  Lists the part
IPN: 10159-473
Part: 10159-473 | Capacitor 47 nF | 10159-
Descrip;tion: CAP,47 nF,10%,X7R,50 V,LS5.00,Radial
Stock: 0
Status: OK (green background)
Batch: -
Location: No stock location set
Notes: -
Note: clicking on the "Part" takes me to the Details tab instead of the pricing screen, like it does for all other parts.

Used In tab (1)
Assemblies
Part: 10140-1 | TARPN Pwr Sply | 10140-
Description: FINAL ASSY,TARPN PWR SPLY
Uses: 2

Suppliers tab (1)
Part Suppliers
Part: 10159-473 | Capacitor 47 nF | 10159-
Supplier: Digi-Key
Supplier Part: BC1099CT-ND
Manufacturer: Vishay BC
MPN: K473K15X7RF5TH5
Link: https:/www.vishay.com/docs/45171/kseries.pdf

I know this is an overwhelming amount of information, but I don't know what specific information you need to look at this farther. How would I get to the pricing screen independent of clicking on the part in the part stock tab?
--Regards, Larry
P.S. I don't know why my 3rd paragraph is in bold when I go to preview.

**Comment by eeintech** [comment]
@LarryJoy Can you send screenshot rather than text?

Is there anything different about that part compared to others that we should know in order to reproduce on our side?

**Comment by LarryJoy** [comment]
I can not log into InvenTree as the below shows. I have yet to carry out your instructions to save the directories/files I have and start again from scratch.
(inventree-env) larry@larry-MS-7693:~/InvenTree-master/inventree/InvenTree$ python manage.py runserver 127.0.0.1:8000
InvenTree running in DEBUG mode
MEDIA_ROOT: /home/larry/InvenTree-master/inventree/inventree_media
STATIC_ROOT: /home/larry/InvenTree-master/inventree/inventree_static
2020-09-09 21:33:50,092 DEBUG Using selector: EpollSelector
InvenTree running in DEBUG mode
MEDIA_ROOT: /home/larry/InvenTree-master/inventree/inventree_media
STATIC_ROOT: /home/larry/InvenTree-master/inventree/inventree_static
2020-09-09 21:33:50,760 DEBUG Using selector: EpollSelector
Watching for file changes with StatReloader
2020-09-09 21:33:51,070 INFO Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/larry/InvenTree-master/inventree/inventree-env/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/larry/InvenTree-master/inventree/InvenTree/label/models.py", line 11, in <module>
    from blabel import LabelWriter
ModuleNotFoundError: No module named 'blabel'
--Larry

**Comment by eeintech** [comment]
@LarryJoy You are missing the `blabel` pip package which indicates your copy of the InvenTree code is more recent than your initial/previous installation.

If you haven't setup a Python environment, here is a list of commands I believe can help you recover your current installation:
```
$ cd /home/larry/InvenTree-master/inventree/
$ pip install -U -r requirements.txt
$ cd InvenTree/
$ python manage.py migrate
$ python manage.py collectstatic
$ python manage.py runserver 127.0.0.1:8000
```

If you did have the chance to learn about Python virtual environments (**highly recommended**) and have set one up then you'll only need to follow the instructions to install invoke:  https://inventree.github.io/docs/start/install#invoke
And update your InvenTree instance: https://inventree.github.io/docs/start/update

**Comment by LarryJoy** [comment]
I have not setup a Python environment, I have no idea what it is. I tried your terminal commands and it didn't work. Here is what I got:
larry@larry-MS-7693:~/InvenTree-master/inventree$ pip install -U -r requirements.txt
Collecting wheel>=0.34.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Collecting Django==3.0.7 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement Django==3.0.7 (from -r requirements.txt (line 2)) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29)
No matching distribution found for Django==3.0.7 (from -r requirements.txt (line 2))

What next?
--Larry

**Comment by SchrodingersGat** [comment]
Larry, what version of python are you running?

Run `python --version` to determine this.

**Comment by LarryJoy** [comment]
larry@larry-MS-7693:~$ python --version
Python 2.7.17
--Larry

**Comment by SchrodingersGat** [comment]
Right, you'll need to be using python 3.6 or higher.

Instead of running the commands with `python` and `pip`, use `python3` and `pip3`

(This is why a [python environment](https://inventree.github.io/docs/start/install#python-virtual-environment) is recommended, is ensures that the correct versions of things are installed).

**Comment by LarryJoy** [comment]
Okay I went through the instructions and think I have downloaded Python3 into the right place, the InvenTree source directory--for me it is *~/InvenTree-master/inventree*. I then tried to update with the following results:
larry@larry-MS-7693:*~/InvenTree-master/inventree$ invoke update*
Command 'invoke' not found, but can be installed with:
sudo apt install python-invoke 
sudo apt install python3-invoke
larry@larry-MS-7693:*~/InvenTree-master/inventree$ sudo apt install python3-invoke*
[sudo] password for larry: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libaqbanking35 libaqbanking35-plugins libaqbanking43 libaqbanking43-plugins libaqebics0 libaqhbci24 libaqofxconnect7 libclang-common-9-dev libgwenhywfar60 libgwenhywfar78 libktoblzcheck1v5 libllvm9
Use 'sudo apt autoremove' to remove them.
Suggested packages:larry@larry-MS-7693:*~/InvenTree-master/inventree$ invoke update*

Command 'invoke' not found, but can be installed with:

sudo apt install python-invoke 
sudo apt install python3-invoke

larry@larry-MS-7693:*~/InvenTree-master/inventree$ sudo apt install python3-invoke*
[sudo] password for larry: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libaqbanking35 libaqbanking35-plugins libaqbanking43 libaqbanking43-plugins libaqebics0 libaqhbci24 libaqofxconnect7 libclang-common-9-dev libgwenhywfar60 libgwenhywfar78 libktoblzcheck1v5 libllvm9
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  python-invoke-doc
The following NEW packages will be installed:
  python3-invoke
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 45.9 kB of archives.
After this operation, 195 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-invoke all 0.11.1+dfsg1-1 [45.9 kB]
Fetched 45.9 kB in 1s (86.1 kB/s)       
Selecting previously unselected package python3-invoke.
(Reading database ... 564543 files and directories currently installed.)
Preparing to unpack .../python3-invoke_0.11.1+dfsg1-1_all.deb ...
Unpacking python3-invoke (0.11.1+dfsg1-1) ...
Setting up python3-invoke (0.11.1+dfsg1-1) ...
update-alternatives: using /usr/bin/python3-invoke to provide /usr/bin/invoke (invoke) in auto mode
update-alternatives: using /usr/bin/python3-inv to provide /usr/bin/inv (inv) in auto mode
larry@larry-MS-7693:~/InvenTree-master/inventree$ invoke update
'update' did not receive all required positional arguments!

  python-invoke-doc
The following NEW packages will be installed:
  python3-invoke
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 45.9 kB of archives.
After this operation, 195 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-invoke all 0.11.1+dfsg1-1 [45.9 kB]
Fetched 45.9 kB in 1s (86.1 kB/s)       
Selecting previously unselected package python3-invoke.
(Reading database ... 564543 files and directories currently installed.)
Preparing to unpack .../python3-invoke_0.11.1+dfsg1-1_all.deb ...
Unpacking python3-invoke (0.11.1+dfsg1-1) ...
Setting up python3-invoke (0.11.1+dfsg1-1) ...
update-alternatives: using /usr/bin/python3-invoke to provide /usr/bin/invoke (invoke) in auto mode
update-alternatives: using /usr/bin/python3-inv to provide /usr/bin/inv (inv) in auto mode
larry@larry-MS-7693:~/InvenTree-master/inventree$ invoke update
'update' did not receive all required positional arguments!
***********************************************************************
To log into InvenTree now I do the following commands:
• 'cd home/larry/InvenTree-master/inventree'
• 'source inventree-env/bin/activate'
Will see "(inventree-env)" at the beginning of the command line.
• 'cd InvenTree'
• 'python3 manage.py runserver 127.0.0.1:8000' [I'm not sure this is correct. Should there be an "invoke" in there?]
There will be several lines of code ending with "Ctrl-C to exit".
• Then go to web server and enter "http://127.0.0.1:8000".
This will open the InvenTree program.
*************************************************************************
All parts now do the following:
• Click on Part in the Parts Tab part list. This takes you to the Part screen.
• From here click on the Stock tab and see a row with the part listed.
• Click on the part, which now goes to the Stock Tracking Information.
This is what happens even with the two parts I was having trouble with. The question now is, how do I get to the price breakdown screen?
--Larry

**Comment by eeintech** [comment]
@LarryJoy Is this issue still current or have you figured it out?

**Comment by LarryJoy** [comment]
I have not figured it out. The issue is still open. The question is, how do I get to the price breakdown entry screen?
--Larry

**Comment by eeintech** [comment]
@LarryJoy Can you please specify what do you expect by "price breakdown entry screen"?
Are you expecting to see pricing for the current Stock information of a part?

**Comment by LarryJoy** [comment]
Yes, expecting to enter pricing levels: 1 @ $/each, 10 @ $/ea, 25 @ $/ea, etc. when first setting up a new inventoried part, when the pricing changes, or basically at any time needed.
--Larry

**Comment by LarryJoy** [comment]
Ok, that worked. Thank you! One last question. Is the "Price" the total cost of the quantity or is it the cost per each? In your example you have a "Quantity" of 10 and the "Price" is $1 USD". So the cost would be $0.10 per each and the InvenTree program figures it out? Or is the cost $1.00 per each. For the Quantity of 100 the Price is shown as $9.00 and that would be $0.09 per each. So the price looks like it is the total cost of the quantity and InvenTree figures out the cost per each when an assembly is built using the part?
--Larry

**Comment by eeintech** [comment]
@LarryJoy Actually good catch the price is price-per-unit, my quick test should have been set as:

![image](https://user-images.githubusercontent.com/4020546/95892271-e3c55200-0d4b-11eb-8b9f-36723ca697d1.png)

So `Price` should actually be `Unit Price` and is the cost for **one** component, not for the quantity listed.

On Digi-Key this part price breakdown is:

![image](https://user-images.githubusercontent.com/4020546/95892321-fa6ba900-0d4b-11eb-9b03-2fa88438912a.png)

**Comment by LarryJoy** [comment]
Okay on price per unit and how to get to the pricing screen. Thanks again.
--Larry
